### ISSUE TITLE
"New Image From Paste" Button

### ISSUE THREAD

**Issue by Ashedragon** [aseprite/aseprite#1024]
GraphicsGale has this handy feature where you can press a button and it will create a new image with the contents of your clipboard with the single press of a button. This would be an incredibly handy feature and would save a lot of time.

**Comment by oceanhahn** [comment]
This almost already exists with _Edit / New Sprite from Selection_ ([Ctrl] + [Alt] + N).
It's not the same, because it copies from whatever is selected (if anything) in your current viewport and not from the clipboard, so it won't _replace_ what you want. But it's close!

Hope it helps you, at least for now!

**Comment by dacap** [comment]
I thought about this feature several times, but I've never decided to include it as we can press `Ctrl+N` (the default size is the clipboard image size), `Enter`, `Ctrl+V`.

Anyway, sometimes I find a little uncomfortable to see the clipboard image size in `File > New` instead of the latest used image size.

I think that there are several things we can do with this:
- [ ] Add a command (that can be invoked with a keystroke) to create the new sprite with the clipboard content.
- [ ] If the clipboard contains an image, we might add a little clipboard tab so when it's pressed a new file is created with the clipboard content
- [ ] Add an option in settings to avoid changing the default size in `File > New` depending on the clipboard content

**Comment by oceanhahn** [comment]
Perhaps we can roll all of those together and add a check box to the **New Sprite** pane that gives the option to create _New from Clipboard_, which locks the width/height fields to the clipboard contents and pastes the clipboard contents automatically upon creation. This way, colour mode and background fill options could also be applied to the new image as well, possibly.
A hotkey could be created that calls *New Sprite* with that option checked and invokes it automatically, maybe.

It might be nice to roll in some of the things I mentioned in #996 as well, possibly?

**Comment by oceanhahn** [comment]
I do like the idea of a Clipboard tab, though! If you go that route, could the tab also be detachable/floating in the same way the _Preview_ pane is?

**Comment by dacap** [comment]
@oceanhahn I was thinking in something like this:

![clip](https://cloud.githubusercontent.com/assets/39654/13999986/cfffb37c-f11d-11e5-8562-3501305951d3.png)

instead of a tab. When the icon is clicked a new document with the clipboard content is created.

**Comment by dacap** [comment]
(and I have to review #996 yet)

**Comment by oceanhahn** [comment]
@dacap Aa, I see. That makes sense, although I worry slightly that it could get crowded in the tab bar if we keep a lot of projects open at once or keep Aseprite open in a smaller window, rather than fullscreen. Still, I like it!

Would there be an Edit menu option as well and that icon would be a shortcut to it, or were you thinking that the tab-bar icon would be the only means to paste directly to a new file?

**Comment by dacap** [comment]
> Would there be an Edit menu option as well and that icon would be a shortcut to it

Yes, at least the icon should be a shortcut for something else that might be called with a keyboard shortcut.

**Comment by dacap** [comment]
Maybe an `Edit > Paste as New Sprite` menu (related to #672 too)
