### ISSUE TITLE
AppImage / Flatpak / xdg-app support

### ISSUE THREAD

**Issue by rautesamtr** [aseprite/aseprite#1044]
Instead of distributing packages for various linux distributions ( #821, #240 ) for the commercial release, xdg-app probably is the way to go once it is available on major linux distros. As summarized by the [project](https://wiki.gnome.org/Projects/SandboxedApps) itself:

> There are two main goals with this project.
> - We want to make it possible for 3rd parties to create and distribute applications that works on multiple distributions.
> - We want to run the applications with as little access as possible to the host. (For example user files or network access)

xdg-app is already part of Fedora and will be probably part of [future debian releases](https://blogs.gnome.org/alexl/2016/03/22/xdg-app-landing-in-debian/).
So far aseprite seems to run fine with the minimal org.freedesktop.Platform 1.2, built with org.freedesktop.Sdk 1.2 and this [json file](https://github.com/aseprite/aseprite/files/195652/org.aseprite.Aseprite.json.txt)

**Comment by dacap** [comment]
I'm waiting for this kind of app bundle feature on Linux from long time ago. I didn't expect it was so advanced. I've to take a look to this technology. Also I'd love to see how Steam is going to use this.

**Comment by probonopd** [comment]
You might also be interested in http://www.appimage.org, a binary distribution format specifically geared toward upstream packaging. An AppImage is essentially a self-mounting ISO that contains an application and all dependencies it needs to run that cannot be assumed to be part of the base system (Linux distribution). The advantage is that it works already today on most not-too-outdated Linux distributions, and the user needs to download or install absolutely nothing besides the AppImage of the application in question.

Projects like MuseScore, Krita, and Scribus are already using it for distribution of nightlies and/or releases to users of various distributions.

**Comment by soycamo** [comment]
Has there been any progress on this front? I purchased the .deb recently but it doesn't work on Debian Stretch out of the box due to a dependency on `libssl-1.0.0`. I tried compiling from source but I'm not sure what dependencies are missing and which ones are just mismatched from Stretch. I would definitely appreciate a prepackaged app, whether it be xdg-app or AppImage or Flatpak.

**Comment by dacap** [comment]
I've to start working on an AppImage for the next version. Giving more priority to this one.

**Comment by bil-elmoussaoui** [comment]
I can help with the flatpak package if you want !

**Comment by nlordell** [comment]
I've had success repackaging the official `.deb` releases into `AppImage` with https://github.com/AppImage/pkg2appimage

The hardest part is setting up the `pkg2appimage` environment but then the AppImage generates auto-magically.

If anyone is interested here is my build script and Dockerfile (so I don't need to install `pkg2appimage` and friends on my actual system): https://github.com/nlordell/aseprite-build

**Comment by nlordell** [comment]
I dug a little deeper recently to try and further reduce friction for bundling an `Aseprite.AppImage`.

It turns out that using [`linuxdeploy`](https://github.com/linuxdeploy/linuxdeploy), which AFAICT is the [recommended way](https://docs.appimage.org/packaging-guide/from-source/native-binaries.html) of packaging native binaries built from source,
its trivial to create an app image from the Aseprite build output [from the Aseprite installation instructions in repo](https://github.com/aseprite/aseprite/blob/main/INSTALL.md).

Here is a sample script that bundles an AppImage from the build output:
<details><summary><code>package.sh</code></summary>

```bash
#!/usr/bin/env bash
# SPDX-License-Identifier: 0BSD

repo="$(realpath "${1:-aseprite}")"
build="${2:-"$repo/build"}"

pushd "$build" > /dev/null

echo "===> Fetching linuxdeploy"
if [[ ! -e linuxdeploy ]]; then
    curl -LO https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
    chmod +x linuxdeploy-x86_64.AppImage
    ./linuxdeploy-x86_64.AppImage --appimage-extract
    mv squashfs-root linuxdeploy
    rm linuxdeploy-x86_64.AppImage
else
    echo "nothing to do."
fi
linuxdeploy="$(pwd)/linuxdeploy/usr/bin/linuxdeploy"

echo "===> Installing AppDir"
rm -rf AppDir
"$linuxdeploy" --appdir=AppDir \
    --executable=bin/aseprite \
    --desktop-file="$repo/src/desktop/linux/aseprite.desktop" \
    $(ls bin/data/icons/ase*.png | sed 's/^/--icon-file=/') \
    --icon-filename=aseprite

echo "===> Patching AppDir"
mkdir -p AppDir/usr/share/aseprite
cp -r bin/data AppDir/usr/share/aseprite

echo "===> Packaging AppImage"
VERSION=${ASEPRITE_VERSION:-$(git -C "$repo" rev-parse --short HEAD)} \
"${linuxdeploy}-plugin-appimage" --appdir=AppDir

popd > /dev/null
```

</details>

Assuming the Aseprite source at `$ASEPRITE_SOURCE` and the build output at `$ASEPRITE_SOURCE/build` (which should be the case if the aforementioned Aseprite install instructions were followed), just:
```
[ASEPRITE_VERSION=vX.Y.Z] ./package.sh $ASEPRITE_SOURCE
```

As you can tell, I'm really keen on having an official AppImage build :wink:.

**Comment by mikoducky** [comment]
Has anything more happened on this front? I'm having a terrible time compiling on Fedora. Honestly, I'd pay for the app if it wasn't just a deb file. I WANT to pay for this program, but much like my beloved paint.net, it seems it's not in the cards.
I've found a handful of ways to compile, but:
- the official instructions from install.md do not work (saying you can just link to the uncompressed skia archive, which is wrong)
- some guy from Reddit has instructions to convert to .rpm don't work (the OP instructions are incomplete)
- skia has horrendous compilation instructions, not even mentioning linux at all
- a random script I found on addictivetips didn't work
- installing libwebp didn't work

**Comment by nlordell** [comment]
Tried it out yesterday and it worked like a charm. I'll let you know if I find any issues.

**Comment by v4u6h4n** [comment]
Are there any plans for a flatpak? I just purchased Asperite and although an AppImage will do, I would definitely prefer the option for a flatpak for more straightforward system integration.
