### ISSUE TITLE
Crash when º key is pressed in the app::SelectAccelerator dialog on Windows

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#1065]
Maybe other (unicode) keys crashes the program. I didn't check other platforms yet.

**Comment by dacap** [comment]
(Highly probable that this crash was introduced with 27b55030e26e93c5e8d9e7e21206c8709d46ff22 fix.)

**Comment by sirblackheart** [comment]
With current master on linux i do not get a crash with unicodes but for some i am not really able to set them. I can enter them but they do not show up in the keyboard shortcuts after pressing ok in the accelerator add dialog. For example i can not use  german umlaut characters `ö ä ü`. It should be also noted, that they show up when combing them with a modifier but do not trigger. This may be because for example `alt+ö` sends the character `;`. Not sure if this is related to this bug or if i should open another one. Could also be that this will be solved with skia?

**Comment by dacap** [comment]
Yeah, it's a known issue. Keyboard shortcuts with Unicode characters or special symbols aren't working as expected. I've a private branch that I've to bring back to `master` to continue. Anyway I want to finish the X11 Skia port first, remove Allegro back-end, and fix the keyboard. I'll write a task list in #139
