### ISSUE TITLE
Unified color picker..?

### ISSUE THREAD

**Issue by bodhiBit** [aseprite/aseprite#1102]
There seems to be two(ish) color picker windows in the app.. There's the one below the palette which you can use to add colors to the palette and then one to edit the colors already in the palette.. And I can only customize the first one to display as a colorwheel etc, which I really like, but most of the time I'm editing the colors I already have, so I can't use the colorwheel picker for that..

I don't really get why there has to be two different places to pick colors.. Why not just have one..? you can already expand the palette and copy colors around, so just have the main color picker edit the selected palette color instead of adding them..
Or maybe have the option to set the picker in either edit or add mode..

**Comment by dacap** [comment]
Hi @bodhiBit, I always wanted to unify both color selectors. The most "intuitive" behavior I thought about, is that when the Palette Editor is visible/enable, color selector/picker edits colors instead of selecting colors/showing warning icon to add colors. In this way we can switch between those two modes (edit/add as you said).

**Comment by bodhiBit** [comment]
I guess that could be a way to do it.. just seems a little redundant to have two color pickers (or up to four when you click the fore-/background colors below the wheel).. Is there any particular reason to have that many color pickers..?

**Comment by dacap** [comment]
> Is there any particular reason to have that many color pickers..?

Just legacy design decisions.

I'll be discussing a possible UI design to create the unified color selector. The only thing I'm sure right now is that F4 ("Edit Palette") should change the mode in color selectors behaves. E.g. When the "Edit Palette" button isn't activated, color selectors should behave as they behave right now. When the "Edit Palette" is activated, color selectors should change palette colors.

The only problem is to unify RGB and HSB sliders/text entries in the same color-bar widget.

**Comment by astraldata** [comment]
If we use any indexed-color picker, please allow us to use an HSL picker too. It's killing me to use HSB to do my indexed-color palettes, since I come from Gale and have always had access to the HSL slider in some form or another in all my other art/animation programs. 

It's the one thing that's really hurting my color-picking sensibilities in ASEsprite, and it's not something I think I can easily get over when working steadily with indexed palettes as I usually do. :(

--

And regarding the color-bar widget, it's a simple fix:

You could simply have a Radio button list of pickers in the picker window that changes the entire window's interface between the RGB/HSB/HSL (<-- yes, HSL) various picker bars, depending on which is selected.
