### ISSUE TITLE
File > Export resize destroys the redo buffer

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#1112]
This is similar to Issue #839 
1. Make a new document.
2. Make a stroke.
3. Make a second stroke.
4. Undo the second stroke.
5. Save Copy As using a resize value different from 100%
6. Redoing resizes instead of making the second stroke.
![redobufferdestroy](https://cloud.githubusercontent.com/assets/8582123/15008752/76ed17d0-11b0-11e6-809e-f84ce331c500.gif)
On Aseprite v1.1.4.1 on Windows Vista 32 Bit

I think I got burned on this once trying to save an earlier version of a file I was working on by using undo.
I'm trying to report some stuff I've known about but never bothered to report.

**Comment by dacap** [comment]
Here the problem is that Save Copy As uses the Resize command and then undo it to restore the sprite. I think this could be temporally fixed activating the nonlinear history:
![nonlinear](https://cloud.githubusercontent.com/assets/39654/15013816/3fe55ea0-11d8-11e6-8931-38864e344788.png)

The "real" fix is [commented here](https://github.com/aseprite/aseprite/issues/493#issuecomment-157234093)
