### ISSUE TITLE
Add Skia as a submodule, maybe?

### ISSUE THREAD

**Issue by OrenjiAkira** [aseprite/aseprite#1185]
Just a thought, a suggestion. You guys probably have thought of this already, but I didn't find any issues regarding this.

Since aseprite already uses submodules, why not add skia and one and make it a dependency with cmake? That would make compiling on Mac OSX incredibly easier, and one would not have to pass thousands of params to cmake; just one for "use skia", and cmake does the building, checking out, cloning, and all that.

**Comment by dacap** [comment]
Hi @OrenjiAkira, actually I don't include Skia as a submodule because these two reasons:

1. [We use cmake and Skia uses gyp](https://gyp.gsrc.io/docs/GypVsCMake.md). There is some work going on to [compile Skia with cmake](https://skia.googlesource.com/skia/+/master/cmake/), but it's experimental so I didn't give it a try yet. Even more, they use their own [depot_tools](https://www.chromium.org/developers/how-tos/install-depot-tools) (to sync sub-dependencies, building, etc.).
1. Skia is *too big* and I prefer to keep it outside the Aseprite compilation. (Skia depends on clang and llvm, huge dependencies, it takes a long time to clone the whole repository.)

Also big dependencies make the day-to-day compilation slower. So we should try to avoid adding more dependencies in `third_party/` directory. Anyway thanks for commenting about this issue 😉

**Comment by OrenjiAkira** [comment]
I did not know skia depended on llvm, so indeed checking for that and compiling it could potentially take many hours. I also see, looking a little further, that the skia website does not offer released compiled versions of it, so just downloading it in lib format is also not possible (to avoid user compilation). So no matter what the user has to compile skia on their own, and if they don't already have llvm it could take ages.

But anyone compiling aseprite with skia has to do all that anyways. I would suggest making a bash script for it all, but that wouldn't be compatible with windows users. Hmm, I guess I don't know if there is a better solution for this aside from the documentation that already exists.

Anyway, thanks for taking your time to explain this to me.

**Comment by dacap** [comment]
Actually there is a [step by step guide in INSTALL.md](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#building-skia-dependency) to compile Skia on Windows and OS X (which could be converted into a `.bat` or `.sh` files I guess). The Linux version isn't there because there are no Skia port on Linux yet, but I'll add it soon.
