### ISSUE TITLE
Feature Request : Hue/Saturation

### ISSUE THREAD

**Issue by kloworks** [aseprite/aseprite#1186]
Hi,
adding Hue/saturation will be nice and quick to adjust the color fast.
color curve still kind confuse.

something like Photoshop will be nice :
http://i.imgur.com/dRJMq1h.jpg

in Aseprite its already there but for color palette,if can be work in the canvas will bw nice :)
http://imgur.com/hYEEqCO

thanks

**Comment by astraldata** [comment]
Definitely would love this -- Got used to using the one in Gale for color selection, but any way to use HSL would be infinitely appreciated -- especially if it happens soon, and changes the sprite and palette indexes directly on low-color images!

**Comment by trollworkout** [comment]
I deff support this.

**Comment by bilgekaan** [comment]
+!

**Comment by MichelleJHowe** [comment]
This is such a core feature, I was surprised it wasn't already implemented. As is, I have to export my sprites, color adjust them, then import them whenever I find the colors are just a bit too bright or the colors are collectively off from what I'm going for. It can be time consuming, but not nearly as time consuming as replacing all the pixels one color at a time on a large project in Aseprite alone.

This is basically the one feature that's preventing me from fully embracing Aseprite and what put me on the fence about getting it at first.

When implemented, would be nice if you could adjust layer by layer or every layer.

**Comment by dacap** [comment]
This will be available in the next release. The only thing I have to think about now is a way to target filters/effects that modify color (like "Invert" or this new "Hue/Saturation") to pixels or to the color palette. For example, by default, it looks like this Hue/Saturation feature should modify pixels on RGB sprites, but should modify palette entries on Indexed sprites. Or if we are in an indexed image with an active pixels selection, the filter should modify pixels instead of palette entries.
