### ISSUE TITLE
Brush swap hotkey doesn't seem to work on one machine but works on another (Windows 10)

### ISSUE THREAD

**Issue by darthdeus** [aseprite/aseprite#1195]
I'm not really sure what's causing this, but I'm using Aseprite on two different Windows 10 machines, both running 1.1.6. On one machine I can simply press Alt+1, Alt+2, ... to swap brushes, but on the other it doesn't change them, and acts as if I only pressed Alt.

![](http://i.imgur.com/J4bN4km.gif)

Both use English US keyboard (the normal one).

I'm not really sure if there's another program interfering with this, but there shouldn't be, as both machines have very similar setup.

Changing the hotkey to something like `;` and `'` does help and it works after that, which would indicate that something is interfering with the hotkey. But if I press Alt+1 in the hotkey setup, it does detect it properly, which makes it seem that the key press gets to Aseprite, see

![](http://i.imgur.com/vyLeS4f.gif)

**Comment by dacap** [comment]
I think I've solved this issue. The problem is that `Alt` key switches to the eyedropper tool temporally, so the new brush is selected for the eyedropper, which doesn't make sense in the first place. It's strange that it works in one machine and in the other none. Anyway, v1.1.8 will show have this fix.
