### ISSUE TITLE
Commits after version 1.1.8 break license of previous versions

### ISSUE THREAD

**Issue by FOSSBOSS** [aseprite/aseprite#1257]
*commits after versions 1.1.8 break licenses of previous versions. 
*Contributors get a thanks, but are not listed by name, and are not appropraitely cited for their contributions to the project.

**Comment by dacap** [comment]
Hi @FOSSBOSS, we've changed the GPL to the new Aseprite EULA (there is a discussion about this in the comments section [in the same commit](https://github.com/aseprite/aseprite/commit/5ecc356a41c8e29977f8608d8826489d24f5fa6c) and in issue #1242).

About the contributions, I generally do a mention on each release in the [release notes](http://www.aseprite.org/release-notes/) (search for "thanks"). If you think that a specific contribution should have a special mention in the About dialog or README file, please let me know.

**Comment by jgyllinsky** [comment]
Hi @FOSSBOSS , @dacap 

I was just going to add to this project, and while searching through changes to see if the bugs had already been fixed, I noticed that too. It looks like there are two points here, so I've separated my responses out.

1.  I've just read through the change log, and this issue seems to originate in commits following commit 7750982af6159d0bcb01336da915d93c88318886 . To resolve this, the project should have really been forked at that point, creating a Aseprite 1 series and a Aseprite 2 series (or "sGplrite" and "Aseprite Pro", etc). I recommend checking out that commit and branching, although it seems a rebase or merge will not be possible.

2. At least for version 1.0.9-dev, I can confirm that contributers are not listed in the About section of the program. I am not sure about other versions. I have not found an existing issue # for this one yet.

**Comment by jgyllinsky** [comment]
For the first issue, I believe this is how one would go about this on a POSIX computer (switch out mkdir for md etc on windows, iirc):
```
mkdir ~/git/sGplrite
cd ~/git/sGplrite
clone https://github.com/aseprite/aseprite.git .
git checkout 7750982af6159d0bcb01336da915d93c88318886 .
```
Although I'm not sure how to rename the repo, to show that it is distinct from the modern, official aseprite. Someone on stackexchange probably knows.

**Comment by dacap** [comment]
Please check the [aseprite-gpl fork](https://github.com/aseprite-gpl/aseprite/), they already have done something like that.

**Comment by Skrylar** [comment]
This just tells me that we can't trust open source "products." They seem to inevitably backstep on their community when it becomes convenient to do so (DivX, NGINX Plus, now Aseprite.)

**Comment by dacap** [comment]
Hi @Skrylar, could you please tell me in who can I trust? Free Software Foundation? Linux distributions? All these years I've made everything to make a living from Aseprite, no one came to me and said "I think you've done a great work and I'd like to help you keeping Aseprite in the way it is." Also, I didn't (and don't) feel part of a community. I don't even know what this "community"  thing means (along this years, I was contacted by a specific "community" two times, just to be insulted).

I'm sorry if you lost the trust on me, I've lost the trust in the "community" (whoever it is, wherever it is, whatever that means). I trust in certain people that helped in these years and gave me encouraging words, people that want to create things and continue using Aseprite. I'll continue working for them.

**Comment by Skrylar** [comment]
@dacap 

They likely insulted you because your decision posts reads as an all-out attack against the Linux community.

> Linux Distributions vs. Developers

There is no "versus" here; if someone specifically asks to be excluded from distribution packaging then they will usually do so. See or contact **Paul Davis** about this; he authors the Ardour package, and he asks people _not_ to simply repack the product and distribute it. They still legally can, and PPAs/the KStudio distro does, but regular distros at large respect it.

> It looks like Aseprite is free just because the distribution made it free (and not because the developer’s decision, the developer is basically inexistent).

But you actually _did_.

> I’m not sure how is the review system for applications on Ubuntu or other Linux distributions, but I think they don’t have a way to contact the developer before the user makes the review, the review is just based on what was packaged.

Public repositories (the apt-get parts) don't have review systems, so you must be talking about software centers. If you want to be notified about those, you need to actually go ask them to transfer ownership of the repository over to you. This is not different than the marketplace environment--Apple isn't going to police your brand for you either.

If your name is trademarked (and it should be) then Debian et all as well as the Ubuntu Software Center aren't going to package it without permission. If they do, you can ask them to pull it (and opt to take over distribution yourself; where you could have put a price tag on it yourself, and you indeed would get the percentages that you posted a desire for.) You can ask any distro to pull it (because trademark) and simply ask people not to do it. If they do it, they have to "iceweasel" which still uses the GPL code while not affecting your brand.

> In an alternative world, open source programs that are being sold, could have a charge, and a % could be for the distribution, other % for the package maintainer, and other % for the developer.

As I just explained, _this already existed._ The community itself can't do this for you, because you are the one who owns the trademark and has power of attorney. Ubuntu allows you to charge a fee. elementary's upcoming Houston software center does too. 

> GPL is about “giving everything to the user” and asking for nothing. That kind of mentality might contribute to the destruction of the software (or destruction of people). Users have a responsibility, they should be encouraged to contribute as much information as possible to fix bugs, and we have the responsibility to facilitate this process as much as possible.

GPL doesn't stop you from charging (the FSF even advocates buying GPL stuff); what it stops is monopolistic ownership of source code. FSF itself has asked people to buy products from them. Linux distros ask people to buy products from them. **Open source GPL software has asked people to download stuff from them.** elementary asks people to "pay what they want" before supplying ISOs, Ardour asks people to sponsor them when they start it. So even if someone repackages binaries for another distro, the user still gets asked to support the original developer.

There are also other considerations, like getting in a Humble Bundle.

I'm sorry if you feel like the Linux community at large isn't something you can put faith it, though I don't seem to notice you actually did try to integrate with it.

Let me put it this way: If you didn't provide Apple binaries, and someone put the product on the App store, would it then be Apple's fault that you weren't listed as the developer?  That's exactly the same situation that's happening here. Yes Apple has a means to deal with this situation--others do too.

Here's what you should have done:

Get in touch with others who are in this space (ex. Paul Davis.) Ask the software centers to transfer ownership to you (Ubuntu Software Center.) Ask Debian et all to iceweasel (or, inform them the trademark exists.) Ask people to buy the program on the binary builds (repackagers don't actually cut this part out.)

**Comment by dacap** [comment]
> Get in touch with others who are in this space (ex. Paul Davis.) Ask the software centers to transfer ownership to you (Ubuntu Software Center.) Ask Debian et all to iceweasel (or, inform them the trademark exists.) Ask people to buy the program on the binary builds (repackagers don't actually cut this part out.)

Yes, I should have done that.
