### ISSUE TITLE
Add option for known number of elements in Import Sprite Sheet

### ISSUE THREAD

**Issue by guga2112** [aseprite/aseprite#1287]
When importing a sprite sheet, it would be nice being able to specify how many columns and rows the sprite sheet is, instead of the size of each frame.

It is especially useful when the spritesheet has a nime like "animationName_rowsXcolums.png" and moving the sliders or calculating the frame size takes way longer than just saying the number of elements in the file
### Aseprite and System version
- Aseprite (version number, installer/portable/Steam/beta/dev): 1.1.9
- System (Win/OSX/Linux, version, distribution): all

**Comment by dacap** [comment]
It looks like a nice (and pretty simple) addition to the Import Sprite Sheet UI.

**Comment by Gasparoken** [comment]
Related: https://github.com/aseprite/aseprite/issues/1586

**Comment by martincapello** [comment]
Is adding the columns and rows fields enough? Something like this:

![image](https://github.com/user-attachments/assets/732ba70d-5d3a-4f0e-bdeb-e4b945959304)

Not sure if rows should be at the left side instead...but since the rows affects height and height affects rows, I thought it actually makes sense to put it there.

**Comment by dacap** [comment]
https://github.com/user-attachments/assets/e111fd73-2f5f-4dda-a40a-d00c22c89e7f
