### ISSUE TITLE
Feature Request: Changing transparency color

### ISSUE THREAD

**Issue by TheSilvus** [aseprite/aseprite#1347]
I personally don't like the checkered background that represents transparency, especially when working on small grey sprites (the whole background will be the same color in 16x16 sprites). I had two ideas how to solve it:
1. Make the background square size relative to the screen size and not relative to the sprite size. This sounds complicated but is exactly how e.g. Gimp implements it (try it).
2. Make the background color configurable. Some people like to draw in front of colored backgrounds, it would be great for those people as well.

Of course it's a minor thing - but it would be great to have.

**Comment by dacap** [comment]
Hi @TheSilvus, actually from Edit > Preferences > Background, you can change the background settings:

![screen shot 2016-12-09 at 4 35 28 pm](https://cloud.githubusercontent.com/assets/39654/21062034/b96664d4-be2d-11e6-9719-3cc2a47eb0b6.png)

About point 1) I think unchecking "Apply Zoom" will behave as you expect, but I'm not 100% because I don't know how it's implemented on GIMP.

**Comment by TheSilvus** [comment]
Well, great! Didn't find that before for some reason. It sometimes behaves weird with the setting turned on (artifacts), I guess I'll open another issue for that though.
Thank you a lot!
