### ISSUE TITLE
Strange Menu Defect

### ISSUE THREAD

**Issue by Bobhostern** [aseprite/aseprite#1352]
There appears to be a strange little button over the flag whenever I open Aseprite.
Pictures speak more than words in this case, so here it is:

<img src="http://i.imgur.com/ExTkSrX.png"/>

It's in the top right corner.

Steps:
1. Build Aseprite.
2. Run Aseprite.

### Aseprite and System version

* Aseprite (dev): 4fada3aa00c9b35425913a5b318472d802030835
* System (Linux): Ubuntu 16.04.1 (Xenial)

**Comment by Bobhostern** [comment]
oddly enough, the problem disappears (so far) when using the beta version 6dc2b5284ec3ebd8066f0e1cfb5ec53b1290c6db, but maybe because it's at the edge, and there are no newer versions than it.

<img src="http://i.imgur.com/OEoHnvc.png"/>

**Comment by dacap** [comment]
Hi @Bobhostern, it's strange because 4fada3aa00c9b35425913a5b318472d802030835 just fixed that problem. In your first screenshot you might be running the commit related to v1.1.10 without the 4fada3aa00c9b35425913a5b318472d802030835 patch. Also 6dc2b5284ec3ebd8066f0e1cfb5ec53b1290c6db doesn't fix this problem, but it includes 4fada3aa00c9b35425913a5b318472d802030835 in a previous master -> beta merge (you can check that in the https://github.com/aseprite/aseprite/commits/beta commits history)

**Comment by Bobhostern** [comment]
The problem is that I literally had just pulled it yesterday. And the same problem appears in the beta if I edit config.h's VERSION constant from "1.2-dev" to "1.1.10-dev". Nothing's been fixed, just hidden.
