### ISSUE TITLE
issue /w shift + click and undo

### ISSUE THREAD

**Issue by shin197** [aseprite/aseprite#1353]
Shift + click will draw a straight line from the last point drawn to the mouse cursor.
using this function with ctrl + z will not undo the 'last point drawn'.
Action 1: drawn at point 1.
Action 2: shift+click at point 2, this will draw a line segment goes through point 1 to point 2.
Ctrl + Z, line segment erased.
Action 3: shift+click at point 3, this supposed to draw a line segment goes through point 1 to point 3, but it draws the line segment goes through point 2, and 3.

### Aseprite and System version

* Aseprite (version number, installer/portable/Steam/beta/dev): 1.19 Steam
* System (Win/OSX/Linux, version, distribution): Wind

**Comment by Bobhostern** [comment]
Interesting thing: If you ctrl-Z that, the original segment appears.

Video speaks louder:

<img src="https://zippy.gfycat.com/FixedHandyAsiaticgreaterfreshwaterclam.gif"/>

**Comment by dacap** [comment]
@Bobhostern that might happen if you have the non-linear undo history enabled:

![screen shot 2016-12-11 at 3 01 46 pm](https://cloud.githubusercontent.com/assets/39654/21082097/d01cd632-bfb2-11e6-91a0-51c8a04503f5.png)

**Comment by Bobhostern** [comment]
Went to the menu, turned it off, opened a new sprite, tried it again, the same thing happened. The original line doesn't reappear, though, so it may be that non-linear history is keeping all the branching, but not the information of each history.

tc;dr: The pencil tool is keeping the last point it was used at to make a line with Shift, even though it was removed by an undo. The expected behavior is to start from point 3 to create the line, but it instead starts from point 2. Non-linear history may or may not deal with this, but without non-linear history, the previous line doesn't appear.

**Comment by dacap** [comment]
Hi @Bobhostern, the original bug reported by @shin197 is still present (it's an actual problem), the non-linear undo history problem is just about your specific comment. But the original issue must be fixed yet.

**Comment by dacap** [comment]
Dup #1005
