### ISSUE TITLE
Replace Color dialog preview is crazy slow

### ISSUE THREAD

**Issue by oxysoft** [aseprite/aseprite#1400]
The preview when changing to another color in the Replace Color dialog is mind bogglingly slow compared to the fill bucket for example, which is almost instant. See for yourself in this webm

https://gfycat.com/DeficientFelineCowbird

### Aseprite and System version

* Aseprite version: v1.1.11-trial
* System: Windows 10

**Comment by KasumiArai** [comment]
Probably because the fill bucket is destructive and that preview is non destructive. i.e. using that preview won't destroy your redo buffer, but using the fill bucket will. It's doing it line by line in the preview so as not to use a lot of memory while not actually changing the image itself.

If you hit okay, it'd be instant.

**Comment by Tranberry** [comment]
how big is that canvas?

**Comment by dacap** [comment]
I'll try to improve the performance of filters (including Replace Color) for the next version.

**Comment by oliver-ruehl** [comment]
Amazing work. Aseprite is now killer on Mac.
