### ISSUE TITLE
Dragged windows lag and jump around

### ISSUE THREAD

**Issue by lonesurvivor** [aseprite/aseprite#1405]
When trying to move a window, like the palette editor or the layer property window, it lags behind the mouse movement and jumps back a bit a few times. Looks really glitchy. Windows are still movable, but it is very annoying. This bug does not occur in the stable version.

Aseprite version: 1.2 beta 7 (self compiled)
System: Arch Linux 64

**Comment by dacap** [comment]
Please refer to #1006

**Comment by dacap** [comment]
Just checking, it's strange that the bug doesn't occur on the stable version and only in the beta version. Did you compile the beta version? Are you compiling it with debug information?

**Comment by lonesurvivor** [comment]
Yes, I did compile it (recent beta version from Github). With debug info and without, doesn't make a difference. I use 

> -DUSE_SHARED_CURL=ON -DUSE_SHARED_ZLIB=ON

though because the builtin versions don't compile for me.

**Comment by lemonzap** [comment]
I believe this issue is actually a bit different from the one linked by Dacap. In the thread linked an image shows the issue and it is very reminiscent of windows xp or solitaire graphics. However the issue I'm having that I believe lonesurvivor is having to is more specifically a jumping around. Here's a gif of the issue, I moved my cursor in smooth motions and this lagging and jumping was the result. [https://i.imgur.com/RVA8iJk.gif](url)

**Comment by teleportingtortoise** [comment]
Yeah, also having exactly the issue that @lemonzap shows in the gif under arch linux. Very hard to resize windows for the same reason.
