### ISSUE TITLE
Marquee selectors are invisible on indexed pngs with #000000 α0 at Index 0

### ISSUE THREAD

**Issue by CuriouserThing** [aseprite/aseprite#1412]
Bug:
When using any marquee tool, the selector is invisible.

Conditions:
- File is a .png (couldn't replicate on a .gif or .ase; didn't try any other relevant formats)
- Color mode is Indexed
- The color at Index 0 is #000000 α0 (background/foreground colors don't seem to have any bearing)

Reference:
![selkie16](https://cloud.githubusercontent.com/assets/13986076/22860630/9bd166e0-f0d1-11e6-9ca7-8e93b23b07e3.png)

Version:
Aseprite v1.1.13, Windows 10

**Comment by dacap** [comment]
Hi @TheMostCuriousThing, thanks for reporting this error. It's a known issue but I've never create the issue on GitHub, it's good to have it here now. I'll try to fix this for the next release.

**Comment by oceanhahn** [comment]
I will copy my note from #1667 to here just so that you might be able to find it:

This is a weird problem that occurs when all of the following conditions are true:

 * The current file is in the **Indexed colour mode.**
 * The **Mask colour is set to Index 0** in Sprite properties.
 * **Index 0 has its alpha value set to exactly zero.**

If Index 0's alpha level is anything _other_ than zero, or the Mask is set to an _index value other than 0_, or the graphic is _not_ in indexed mode, the bug does not occur, even if the current mask index (which is not zero) _does_ have an alpha of exactly zero (ha ha what??).

It took a lot of fiddling to discover why, too, I will have you know! XD

**Comment by jtogrady** [comment]
I discovered a similar bug where the all the marquee tools are not visible when the sprite is in Grayscale mode. When I switch it over to RGB color or Indexed it appears just fine. Not a huge deal, because I can get the grayscale palette and move it to RGB, but I thought this should be noted. Nothing else appears to be unique besides the separate color mode
