### ISSUE TITLE
Can't re-bind ellipse tool, etc. to work like default

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1460]
By default the ellipse and filled ellipse tool is bound to Shift+U, and pressing it cycles between the two, but if you rebind them, this isn't possible to achieve, as it will just remove the conflicting bind instead.

Aseprite v1.2-beta9
Windows 7 x64

**Comment by KashouC** [comment]
I fixed it by editing the default key binds in the GUI file, but while this should maybe be it's own seperate feature request, it would be nice if setting ellipse and ellipse fill to "R" for example would ALWAYS select ellipse first, so you know that you always get fill by pressing R twice, instead of having to check every time.

**Comment by dacap** [comment]
Hi @KashouC, two things about this:

1. As you found, there is a bug were we cannot set the same keyboard shortcut to select a couple of tools (e.g. to restore the default behavior)
2. Yeah, I don't like the current way to select the tools when two or more tools share the same keyboard shortcut

To solve the second point we might:

1. Use the solution you proposed, but there are one problem: How do we know what is the first tool to be selected? For example, if ellipse and ellipse fill are associated to R key, should the first R select the ellipse or the ellipse fill? (this is already an actual problem, as by default the non-filled ellipse is selected first, and then the filled ellipse, by the order that these tools are listed in the gui.xml, so that might be the possible solution)
2. Other possibility is to have a keyboard shortcut to switch tools in the group (i.e. as Photoshop does), so for example (by default) the U key selects a tool in the rect/ellipse group, and Shift+U switch the icon in that group (between rect -> filled rect -> ellipse -> filled ellipse)

I'm not sure yet how to solve this in a proper way, maybe both possibilities.

**Comment by KashouC** [comment]
Yeah there are  a lot of different ways to do this, but you probably want it to be as intuitive as possible and not have to add a bunch of extra buttons and stuff so I'm not sure.


Personally I think it would be fine if it just depended on which tool comes first in the keybindings basically. Other options include adding a tab for multi-binds where you can select priority, being able to "re-order" the tools by dragging in the tool bar, adding some sort of order drop down menu behind the keybinding of binds that are bound to a key used by other tools. Problem is that all of these options are either arbitrary things you'd just have to know about, or overly invasive solutions.

Also for setting the same key binding on multiple tools or functions, it would be nice if the program prompted you when you tried to use an occupied key by asking to replace the other bind, keep it, or cancel.
