### ISSUE TITLE
[Bug] Aseprite don't open, just a white (Or black) screen

### ISSUE THREAD

**Issue by FogRyu** [aseprite/aseprite#1473]
Hi everyone. 

I get a bug on my Wacom Companion 2. Aseprite was working until last week but now, when i try to open it i get a white screen like on the screen i join to this message.  Sometime it's black also. And when i put the mouse on top of it, the mouse icon disappear. 

I got the biggest version of the companion 2, all drivers are up to date, and all the other softwares works fine like always, and windows 10 up to date also. So i don't get it.

I tried to uninstall my version, reinstall it. And then, to uninstall again and reinstall others versions, but that doesn't work. I tried with version 1 / 1.1.1 and 1.1.6. The bug it's just a bit different depending the version. 

Any ideas ?

...
![capture d ecran 2017-04-25 09 09 56](https://cloud.githubusercontent.com/assets/28006185/25385867/a3017c2a-29c5-11e7-83ea-f08178bc92b8.png)

...
...

### Aseprite version 1 / 1.1.1 / 1.1.6. install version and Portable version also.

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows 10

**Comment by dacap** [comment]
Hi @FogRyu, I'll reply here instead of your email at support@aseprite.org

Did you try the latest version v1.1.13 or v1.2-beta9 (v1.2-beta9 is preferred to  debug this situation as it logs more information about it)?

After installing v1.2-beta9, could you please try to execute Aseprite with the `--debug` parameter in the command line? https://www.aseprite.org/docs/debug/

This should generate a `Aseprite-v1.2-beta9-DebugOutput.txt` file in your desktop. I'd like to see the content of that file in case that Aseprite doesn't work.

**Comment by FogRyu** [comment]
Hi. And thank you for you Quick Answer. 

So yep, that worked with the latest version so i bought a new one. My windows 10 apparently did an update last week-end. That probably the reason. 

But with the newest version, everything look's good !

Thank you again.

**Comment by dacap** [comment]
@FogRyu all updates for v1.x series (v1.2, v1.3, etc.) are free for customers! If you bought for a second time I can refund your purchase and send you the original link to get the update. Contact me at support@aseprite.org

**Comment by FogRyu** [comment]
@dacap I don't have the download link anymore, a friend bought me this version almost two years ago so the link is lost :).

So keep the money for your good work ! ^^
You deserve it !
