### ISSUE TITLE
Frame tag metadata

### ISSUE THREAD

**Issue by mweitzel** [aseprite/aseprite#1514]
Feature Request:

I would really like metadata in the frameTags that allows you to determine which sprite is is for.

I get huge performance gains from using atlases, multiple sprites with multiple animations each, often with conflicting tag names. The problem is, when I export multiple sprites with animations into a single atlas, there is no way to tell which file they are from.

Currently when I run
```
aseprite \
  -b \
  --data media/compiled/atlas.json \
  --sheet media/compiled/atlas.png \
  --list-tags \
  media/sprites/*
```
the `atlas.json` file has frameTags data like the following:
```
  "frameTags": [
    { "name": "run", "from": 0, "to": 9, "direction": "forward" },
    { "name": "stand", "from": 10, "to": 10, "direction": "forward" },
    { "name": "slide", "from": 19, "to": 19, "direction": "forward" },
    ...
    { "name": "run", "from": 0, "to": 12, "direction": "forward" },
    { "name": "stand", "from": 13, "to": 17, "direction": "forward" },
    ...
  ]
```
This is great, but the "from" "to" are sprite/file specific, and there's nothing to associate the frame to the sprites/file. The best I can do is something like `--filename-format '{title}_#{tag}_{frame}'` and `--format json-array` to preserve order, and run through the array to associate the nth chuck of frames matching `*_#{tag}_*` with the nth frameTag with name `tag`. But it feels hacky and is a real pain to do.

It would be awesome if the frameTag just had the necessary data in it. One solution would be to have an optional `--tagname-format` flag.

I could then use the flags `--filename-format '{title}_{tag}_{frame}' --tagname-format '{title}_{tag}'`. I could then filter by the frame name prefix and wouldn't need to depend on `--format json-array` for order.

### Aseprite and System version
* Aseprite version: 1.2-beta9
* System: macOS 10.12

**Comment by dacap** [comment]
Hi @mweitzel, you can try using [--format json-array](https://www.aseprite.org/docs/cli/#format) to preserve the order of frames. I think that should work.

**Comment by niedzielski** [comment]
I have this same problem with both tags and slices. It's awesome that I can export a bunch of sprites, tags, and slices from multiple source Aseprite files into a single PNG sheet but there's no way to associate tag or slice names to frames per file except by user convention. Frame association works fine when only a single file is packed into the sprite sheet but that almost never happens since it defeats the point. For example, I use the convention in my tag and slice names of "a tag / slice name is a file stem followed by an animation name" with a `--filename-format '{tag} {frame}'`. This is super error prone though because I have to remember it when I'm drawing. I would much rather that each tag and slice include a filename property so that it's part of the format.

**Comment by yeonghoey** [comment]
+1. I wish I could separate animations in a robust way instead of using a kind of user convetion.

**Comment by natebot13** [comment]
I'm running into this issue now too. I need to associate the tag with the frames to get the animation direction. Currently I have the frames formatted with `{title}|{tag}|{frame}` and that works since I can split the name to get the tags, but associating the tag's animation direction is proving to be a huge pain. Is there a better way?
