### ISSUE TITLE
Intuitive opacity / alpha values in Cel properties and color pickers

### ISSUE THREAD

**Issue by enol** [aseprite/aseprite#1544]
Adding alpha effects with the current Opacity bar when double-clicking over a Cel is not very efficient because you have to make an approximation to the desired level of opacity from 0 to 255.

I think that adding a box to change the percentage of the opacity with the keyboard can be very handful and people would be able to obtain a more precise effect on the range between 0% and 100% (more common values for drawing programs).

**Comment by dacap** [comment]
Requested here too: https://community.aseprite.org/t/100-instead-of-256/1916

**Comment by dacap** [comment]
Something requested in [ticket 3452](https://igarastudio.zendesk.com/agent/tickets/3452) is the same 0%-100% range for RGB values.

**Comment by martincapello** [comment]
1. a. For the color selection dialog we could add another textbox at the side having the percentage value:
![image](https://github.com/aseprite/aseprite/assets/5520828/280b3972-e714-4876-b6d7-cbf6b2de6978)

Both textboxes should be in sync, so when one changes the other updates automatically at the same time. We could do this for R, G, and B as well.

1. b. Another alternative would be to keep the dialog as is, but add some logic to the textboxes to show and parse the text to display/enter the values:
![image](https://github.com/aseprite/aseprite/assets/5520828/bf3b5796-8da8-4b6a-80c9-3c30c040335a)

Then the logic should take care of where to position the cursor depending of which part is the user editing, the value part or the percentage part, and how to update the part not being modified as the user types.

2) For sliders we could use a similar approach, so we show both, value and percentage (in the following image I used "|" instead of "/" as the separator just to see how it looks, at the end we should make a choice and use the same in all cases, or even use a different format, like 255 (100%) or whatever makes sense):
<img width="578" alt="Screen Shot 2023-12-26 at 14 41 36" src="https://github.com/aseprite/aseprite/assets/5520828/614e9a96-61cc-4159-802d-ac14f983d67f">

We should also add logic to let the user double click the slider to allow the user enter the value or percentage as text, in a similar fashion as described for the textbox in 1.b.

@dacap Let me know what do you thing, of if you had something in mind already.

**Comment by dacap** [comment]
@martincapello I think we should be able to configure if we should use 100% or 255 values for Alpha. By default the values should use 0-100% as it's the most common option in graphics software (and that's why the change is requested).

Anyway from *Edit > Preferences > Color* (?) we should be able to go back to the previous 0-255 range for Alpha. I'm not sure if we should offer some right-click popup to quickly change the same configuration too.

**Comment by dacap** [comment]
Just in case, we shouldn't offer both values at the same time in the UI, it will make things confusing for most users (I guess).

**Comment by martincapello** [comment]
Okay, then:
1) Add a configuration parameter  for displaying opacity / alpha values as a number or percentage. 
2) No changes for RGB values.
3) Depending on the config parameter the value entered in the color dialog for the alpha channel (or in any other place that let the user enter a value for the alpha) should be interpreted accordingly.

Did I miss something?

What do you think about putting the configuration option in _Edit > Preferences > Editor_ or _Edit > Preferences > General_ instead?

**Comment by dacap** [comment]
> Did I miss something?

No, that's how it should work. (At the moment the most critical thing is the alpha values which is the most common to have 0%-100% range in graphics software, RGB values usually have 0-255 so I think it's not a priority now).

> What do you think about putting the configuration option in _Edit > Preferences > Editor_ or _Edit > Preferences > General_ instead?

It could be the General section but I prefer to avoid adding more stuff there. I think I'dprefer the Color selection (with a specific subsection for Alpha). The Editor section is about specific options for the sprite editor/canvas.

**Comment by martincapello** [comment]
Does something like this would do it?
<img width="836" alt="Screen Shot 2023-12-27 at 12 16 00" src="https://github.com/aseprite/aseprite/assets/5520828/b39c0c63-f521-4ccc-9b2b-fd26ef798a6f">

Also let me know if you want to use different terms/words for the labels.

**Comment by dacap** [comment]
Probably something like `Range:` and using `0%-100%` and `0-255` as combobox items would be enough (and less strings to translate).

**Comment by martincapello** [comment]
Sounds good

**Comment by dacap** [comment]
One thing I forgot, remember that this is for Alpha and Opacity fields (not sure if the "Alpha" section makes that clear 🤔 ).

**Comment by martincapello** [comment]
What about replacing "Alpha" by "Alpha & Opacity" (or "Alpha / Opacity")? Or any other you have in mind.

**Comment by dacap** [comment]
Any of them are fine 👍
