### ISSUE TITLE
pencil/spray brush switches to default when using eyedropper tool

### ISSUE THREAD

**Issue by kyrieru** [aseprite/aseprite#1557]
If you select a user made brush, switch to the eyedropper tool and pick up a color, and then switch back, the brush will be reset to whichever default brush you used last (square, line, etc).

This makes it seemingly impossible to use the eyedropper to pick a color for custom brushes, as even if you switch to the custom brush, it will default to the color of the brush, rather than the currently selected color.

In addition to fixing the problem of it switching back, I think that there could be a checkbox for using the brush color vs using the currently selected color.

**Comment by dacap** [comment]
Actually this was implemented in this way by design just to have a way to discard the custom brush. Anyway I guess the expected behavior would be to keep the custom brush and change its color.

Related: We should have a button in the context bar to discard the custom brush and go back to normal brushes (the same that `Esc` keyboard shortcut does).
