### ISSUE TITLE
Ctrl+A does not re-enable Selection Edges

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1614]
As the title says, select all doesn't re-enable Selection Edges in View -> Show if it's turned off. Not really a big deal since, well, it selects all, but it leaves you a bit confused to if the program reacted to your input or not.

Sometimes I would prefer this functionality however, as selecting large amounts of individual pixels with the wand for example makes the program chug down to a crawl. (But remarkably it doesn't crash even after the program goes black for 6 seconds while loading.)

Aseprite v1.2.4-x64
Windows 7 x64

**Comment by dacap** [comment]
Hi @KashouC, actually, there is no selection command that re-enable the *View > Show > Selection Edges* option automatically.

This brings several issues:

1. The edge boundaries generation is slow/locks the UI when the selection is too irregular (this might be fixed calculating the boundaries in a **background thread**, long time ago I tried to do this, but never finish the implementation)
2. If the resulting edges are too irregular, it will be too visually noisy to work with (this might be a case for a **new option** to show the selection only when it is simple enough, e.g. one or two rectangles)
3. I was just testing and found a **crash** selecting with the magic wand and using an undo limit of 1MB (the crash happens when the undo history is too big and we have to start deleting old undo states).

So several things to be fixed.

**Comment by dacap** [comment]
Thanks for that video! My mistake here. It looks like I tried to replicate the Photoshop behavior, and now I'm not sure if that should work in that way 😅 

Let's make Ctrl+A re-enable the selection as you said originally. And maybe a new option to disable this "show selection edges automatically".

**Comment by KashouC** [comment]
Showing is easier than describing, especially when English is a second language for both of us. ^^

Yeah, I think that is the best solution.
