### ISSUE TITLE
ALT Key doesn't work with (Quick) tool shortcuts on Linux

### ISSUE THREAD

**Issue by jaggygames** [aseprite/aseprite#1621]
The default quick binding of ALT (eyedropper) doesn't work. After trying to set ALT to different tools, they also do not work.

The eyedropper (Quick) does work with Shift.

### Aseprite and System version

* Aseprite version: v1.2.4, aseprite_1.2.4-1_i386.deb
* System: Linux Lubuntu 17.04

**Comment by dacap** [comment]
I think this is because the Window Manager is using Alt key to do other thing. Can you confirm me if Alt key does change to the tool but then clicking in the window just move the window? Or the Alt key does absolutely nothing?

In my Ubuntu installation, I've set the Windows key to be the key to move/resize windows with the mouse (so Win+mouse buttons will modify the window position/size, this by default is Alt+mouse buttons on Ubuntu).

**Comment by jaggygames** [comment]
Hi! I think you're right. The ALT key changes the cursor icon to eyedropper but when the mouse is clicked and dragged, the window is moved instead.

I'm quite new to Linux and this behavior is not intuitive to me so I'm looking at ways to have it more like your system and free up the ALT key.

**Comment by jaggygames** [comment]
I can confirm that the ALT key now works as intended in Aseprite after following these steps:

https://stackoverflow.com/questions/29198864/lubuntu-disable-alt-drag-move-window

I'll close this now as it's not an issue with Aseprite :)
