### ISSUE TITLE
Relicense Aseprite back under GPL

### ISSUE THREAD

**Issue by yegortimoshenko** [aseprite/aseprite#1666]
Hi, hope this will start discussion instead of being instantly closed.

First off, I understand you want to make money off Aseprite, and you don't like it to be distributed for free without much return money-wise. 

Yet, not being able to distribute compiled copies of the software doesn't respect users' freedoms. It is a fatal, overreaching flaw and makes many reasonable use cases a violation of the EULA, for example fixing a bug for someone and sharing a prebuilt executable with them, or building Aseprite for friends and family. There is also a non-enforceable restriction on reverse engineering (I don't know the rationale behind having it in the EULA).

The intent of EULA that you have placed on Aseprite can be easily circumvented by e.g. distributing snap or AppImage that would build Aseprite directly on user's machine and start it, treating compiled executable merely as a cache.

A smaller issue is that source-based distribution systems (AUR, Gentoo, Nix) negate the restrictions entirely, and there is no user-facing reason why it would be harder to install Aseprite that way than fetching a prebuilt binary.

I think that if you were to place a donation request after Nth time Aseprite has been opened (meaning, it's being actively used), that would solve the issue of users of freely distributed versions not paying money. That could be turned off for M$/Steam/etc. builds. I think GPL'd version of Aseprite does very little to ask its users for money.

Hope you'll reconsider the decision.

**Comment by dacap** [comment]
This was already discussed [a couple of years ago](https://dev.aseprite.org/2016/09/01/new-source-code-license/) and at the moment I'm not planning to make any change in the short term.

> There is also a non-enforceable restriction on reverse engineering (I don't know the rationale behind having it in the EULA).

This is because it's a generic EULA. I use the official distributed `Aseprite-v...-Source.zip` files to compile official distributions anyway so there is no extra code in the binary.

> e.g. distributing snap or AppImage that would build Aseprite directly

The automatic compilation process by third party scripts (this is, if you don't follow the INSTALL.md guide) is not considered that *you* have compiled the source code. This is a weak point in the EULA which is not well defined (i.e. what does it means that "*you* may only *compile*" in the 2.g point?).

At the moment I don't want to make a great deal about it. So if some distribution or people are using these "shortcuts" to compile Aseprite, it's ok.

> Hope you'll reconsider the decision.

At the moment I'll not use the GPL. (I've switched all my open source projects from GPL to MIT too, more freedom for the user *and* the developer.)

Maybe in a far future this will be converted to a fully open source license, but that might means something like "I've just stopped working on this, so now it's all yours", which could be the worst possible signal for the users (i.e. the program has been abandoned). My plans right now: continue working on Aseprite as much as possible (maybe 10, 15, or 20 years more with this).

The EULA might change in the future for the better, so it includes your use cases e.g. personal usage might include family usage too, so you can distribute in your family circle. Something to be considered.

**Comment by yegortimoshenko** [comment]
> This is because it's a generic EULA. I use the official distributed Aseprite-v...-Source.zip files to compile official distributions anyway so there is no extra code in the binary.

This is a dangerous restriction. For example, it is not clear whether one can use `gdb` to trace down a bug without breaking the EULA (probably not, that might count as reverse engineering). It's also not clear whether this clause is compatible with availability of the source code at all.

> The automatic compilation process by third party scripts (this is, if you don't follow the INSTALL.md guide) is not considered that you have compiled the source code. This is a weak point in the EULA which is not well defined (i.e. what does it means that "you may only compile" in the 2.g point?).

This EULA builds up on point that compilation is a time investment. No EULA can enforceably prohibit automated compilation. You could make source code non-redistributable and place somewhere where it can't be automatically fetched, but that would mean abandoning GitHub, and would only add an extra step to automated compilation process.

> At the moment I don't want to make a great deal about it. So if some distribution or people are using these "shortcuts" to compile Aseprite, it's ok.

Given that it's easy to legally circumvent, perhaps it would make sense to not pursue the restriction on distribution at all.

Clearly, people don't distribute such self-compiling version not because of legal reasons, but because they honor your work, and while mostly ignoring your EULA, they respect your intent and want to pay money to the originating developer, i.e. you.

It would be nice if you were to respect the users as well.

> At the moment I'll not use the GPL. (I've switched all my open source projects from GPL to MIT too, more freedom for the user and the developer.)

GPL gives freedom to everyone, users and developers alike. Freedom to deny others from freely distributing programs is not really a freedom, it's an exercise of power over other people. See: https://www.gnu.org/philosophy/freedom-or-power.html

> Maybe in a far future this will be converted to a fully open source license, but that might means something like "I've just stopped working on this, so now it's all yours", which could be the worst possible signal for the users (i.e. the program has been abandoned). My plans right now: continue working on Aseprite as much as possible (maybe 10, 15, or 20 years more with this).

When software is free, it doesn't mean it has been abandoned and author is no longer interested in enforcing his monopoly on it because it won't be of monetary benefit to him, it only means that author treats users with respect.

Aseprite was under GPL for most of its existence, and no one thought it was abandoned.

> The EULA might change in the future for the better, so it includes your use cases e.g. personal usage might include family usage too, so you can distribute in your family circle. Something to be considered.

GPL is the better EULA. It lifts the circumventable fatal flaw of current EULA, the restriction on distribution of prebuilt binaries, and unlke MIT license, makes sure no one can take business away from you by forking away your code and adding proprietary features.

---

I hate to be so blunt, but do understand that you are forcing users not to redistribute prebuilt binaries, via state (armed people), because users might suffer consequences if they do. There are numerous alternatives to doing that: for example, ask people not to distribute (and most will respect your request), or make distribution work to your advantage (described above).

Free software builds on mutual respect and trust, and non-free software builds on power. By imposing EULA, you push the relationship with your users from the former to the latter.

Also, I would like to note that I've bought two copies of the program (on Steam), and I wouldn't have bought it if it was proprietary. It saddens me that it has become proprietary, which is why I'm trying to change your mind.

**Comment by dacap** [comment]
A couple of years ago I've already took a decision about this issue. And I don't think you are in the position to say that GPL is the best EULA for Aseprite (or for any kind of software where you were not involved). If you want, you can license your own software with whatever license you want, and that is just fine, because you wrote your software, but you have to respect the decision of other developers.

And *personally*, I don't think that writing non-free software is a way to disrespect your users, there are a lot of way to respect and disrespect users. That's the FSF point of view, and I don't agree with it. I guess the FSF should start respecting developers first.
