### ISSUE TITLE
Use default file format for sprite sheets

### ISSUE THREAD

**Issue by goobliata** [aseprite/aseprite#1683]
Haven't really thought this through but I think it'd be nice if saving a spritesheet defaulted to your default format. Now it is defaulting to PNG. Aseprite 1.2.7.

**Comment by dacap** [comment]
Hi @goobliata, I'll add another default extension for sprite sheets (and maybe for File > Export too). The issue here is that (I guess) most people will like to default to .ase (or .aseprite) in File > Save, and to .png in File > Export Sprite Sheet.

About File > Export, at the moment it uses png when we're trying to export a static file, or .gif when we try to export an animation. I guess this should be configurable too.

**Comment by dacap** [comment]
![screen shot 2018-03-19 at 19 41 41](https://user-images.githubusercontent.com/39654/37626174-91460588-2bad-11e8-8fcf-a7d37c8a43b0.png)

**Comment by goobliata** [comment]
Thanks!

**Comment by Torguen** [comment]
Hi.
What is the difference between the ASE and ASEPRITE extensions?

**Comment by dacap** [comment]
@Torguen there is not difference (just like .jpeg and .jpg), but .aseprite is preferred because Photoshop uses .ase for its Adobe Swatch Exchange file.
