### ISSUE TITLE
Show current color with new color side to side on color editor

### ISSUE THREAD

**Issue by npinochet** [aseprite/aseprite#1696]
Theres currently no easy way to clearly view the changes you are making to colors, other graphics editors use this simple yet effective window where you can see the current color you're modifying and the new color you will be using: ![other editor](https://i.imgur.com/yZazAQX.jpg)
I think a lot of people can benefit with this feature, there's even some space left on the color editor UI to add something like this: ![feature](https://i.imgur.com/cf26C9T.png)
If there's already a way to see the color change, then I apologize for making this issue, but I really searched for this feature on the docs and issues but couldn't find any.

On a side note: [The sliders are 1px shorter for HSV](https://i.imgur.com/FDgxCnd.gif) (I didn't wanted to create another issue for such a small bug)
### Aseprite and System
* Aseprite version: v1.3-dev
* System: macOS

**Comment by dacap** [comment]
I'll see if I can add something in the next release. Sometime ago I thought about this but delay the feature until some user ask for it 😅 

About this bug:
> On a side note: The sliders are 1px shorter for HSV (I didn't wanted to create another issue for such a small bug)
Actually that is because the "V" key of HSV is a little bigger than the other letters, and the layout of labels+sliders is automatically calculated with the width of the letters, something tricky to fix in this case. (I might fix it making RGB and HSL sliders shorter 😬)

**Comment by npinochet** [comment]
Awesome! that was really fast, thanks!

**Comment by dacap** [comment]
![screen shot 2018-04-03 at 20 58 32](https://user-images.githubusercontent.com/39654/38281613-c8c28506-3781-11e8-9580-060df8387f0d.png)
