### ISSUE TITLE
It's possible a version for armhf (armv7) for raspberry pi?

### ISSUE THREAD

**Issue by nenodias** [aseprite/aseprite#1735]
It's possible a version for armhf (armv7) for raspberry pi?
I made a try to compile on it, but fails.

**Comment by KashouC** [comment]
Hi there, you can try this and see if it's a solution for you:

https://github.com/aseprite/aseprite/issues/1652#issuecomment-377441600

**Comment by dacap** [comment]
hi @nenodias, could you please include the output from the console?

@KashouC I think I should add an option to completely ignore libcurl and all code that depends on libcurl.

**Comment by efornara** [comment]
I've just compiled v1.2.15 on buster / armhf. It was on a Pi 3B+ running raspbian, but it shouldn't matter. These notes might also be relevant for buster / arm64.

I confirm that you need to install libcurl4-gnutls-dev and add something like:

    -DUSE_SHARED_CURL=yes

to the aseprite cmake command.

I had a couple of problems compiling skia that I don't see reported here. It looks like both depot_tools and skia itself ship with some "linux64" binaries. They are in fact x86_64 binaries.

It is ninja (in depot_tools) and gn (in skia, directory buildtools/linux64).

For ninja, on the first complain, I just changed the order in the PATH, moving depot_tools at the end, so that the native ninja binary could be found. 

For gn, I compiled it manually from https://gn.googlesource.com/gn and copied it over the x86_64 binary in skia/buildtools/linux64.

Finally, I have no idea if it was because I messed up my environment with my previous attempts, but I got a complain that gn/gn/is_clang.py couldn't be found.

I quickly and brutally did this (in skia):

    cp -r gn gn_copy
    mv gn_copy gn

and I finally managed to get skia compiled.

Also relevant for https://github.com/aseprite/aseprite/issues/1652
