### ISSUE TITLE
Ability to display aspect ratio of current selection/shape tool in the bottom info panel

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#1769]
When making circles and boxes in different sizes it would be handy to be able to tell if they're the same aspect ratio instead of having to count the steps yourself. Not sure if this is as simple to implement as it sounds, since I don't know if aspect ratios might end up really strange and large values, but I don't think it would be too much of an issue.

If there are any good tricks to do this or think about it otherwise I'm open to suggestions.

**Comment by rezaarifandee** [comment]
i dont know about you, but i use the steam version and when i make a circle or rectangle, it display the size while i am dragging on the bottom status bar.

**Comment by KashouC** [comment]
Absolutely, but I guess I mean something more like relative size. So a 1x3 circle shows 1:3, and a 3x9 circle also shows 1:3, and a 30x90 circle also shows 1:3.

**Comment by dacap** [comment]
When the issue was implemented by @Gasparoken, he told me about the randomness of the aspect ratio values when the line is too big, which is true. The numbers jumps like crazy:

![aspect-ratio](https://user-images.githubusercontent.com/39654/53106504-f86b2b80-3511-11e9-82cf-7b2ec53bc107.gif)

I don't know what to show in these cases, but from the regular user standpoint, it looks like a bug. Anyway maybe we cannot do nothing about it (or add an option to show/hide the aspect ratio and hide it by default).
