### ISSUE TITLE
trim command doesn't work in some cases

### ISSUE THREAD

**Issue by daisyowl** [aseprite/aseprite#1840]
As far as i've been able to figure out, if the top left pixel of an image is filled, the trim command won't do anything? You can reproduce this by making a new completely transparent file and painting the top left pixel white. The other corners don't seem affected.

ase v1.2.9
macos 10.13.5

**Comment by KasumiArai** [comment]
The top left pixel is used as the color to trim away. Any color that's not that color is not trimmed. So all transparent pixels to the right and below your white pixel keep the image from being trimmed. 

If you made the top row and left column entirely white, they would would get trimmed because there are no longer pixels that aren't the top left color preventing that row and that column from being removed. 

To see how this ends up working out, try trimming this image multiple times:
![image](https://user-images.githubusercontent.com/8582123/44278200-43328080-a21b-11e8-9373-f48b9355d599.png)
It keeps getting smaller because the top left pixel (the color to be trimmed) keeps changing.

**Comment by daisyowl** [comment]
hmm, ok, makes sense
