### ISSUE TITLE
Extrude spritesheet option on export

### ISSUE THREAD

**Issue by fazzamatazz** [aseprite/aseprite#1890]
Tile bleed is a very common problem, which padding alone does not solve. Extruding the edge pixels into the padding does solve this. I believe the addition of an 'extrude' option when padding spritesheets on export would be very popular when creating tilesets.

[Extruding is a common step when creating tilesets and there are a number of tools out there to do it](https://medium.com/@michaelwesthadley/modular-game-worlds-in-phaser-3-tilemaps-1-958fc7e6bbd6#3919), but why waste time and effort with an extra tool and an additional step when Aseprite's padding options are already half way there.

Interface-wise it would only require a simple tickbox under the existing trim option. There is a convenient little space for it already!

Thanks for reading!

### Aseprite and System version

* Aseprite version: 1.2.9, Steam
* System: Windows 10

**Comment by lrasomattos** [comment]
Extruding Tilesets as well (extrude each grid tile)!! 

We work with Aseprite + Tiled + Unity, and need to go through the whole development with glitchy tiles in Unity, because, although Tiled works with extruded tilesets, it is impossible to edit them quickly and see them updating into our maps. 

For now we have to use external tools that only extrude the tiles for us. And when we do it, we have to update all the references for Tiled, which is cumbersome during development. So we can only do it before releases.

It would be great to just open a tileset.ase edit it, export it and see it update into Tiled already extruded and non glitchy! I have been looking for good editors for tileset textures, and the only reason I'm still looking is because Aseprite doesn't have this option yet.

**Comment by dacap** [comment]
👍 I'm linking a screenshot from [tile-extruder](https://github.com/sporadic-labs/tile-extruder):

![Screenshot](https://github.com/sporadic-labs/tile-extruder/blob/master/images/explanation.png?raw=true)
