### ISSUE TITLE
Can't build skia with clang (Unexpected token)

### ISSUE THREAD

**Issue by DuendeInexistente** [aseprite/aseprite#1939]
I am trying to compile skia with clang as recomended, but it looks like I can't even get past my shell for gn:
```
▶ gn gen out/Release --args="is_debug=false cc=clang cxx=clang++ is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"

ERROR at the command-line "--args":1:35: Unexpected token '+'
is_debug=false cc=clang cxx=clang++ is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false
                                       ^
```
The error persists even if I escape the + characters.
If I remove  clang++, the error changes to
```
▶gn gen out/Release --args="is_debug=false cc=clang is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false"

ERROR at the command-line "--args":1:19: Undefined identifier
is_debug=false cc=clang is_official_build=true skia_use_system_expat=false skia_use_system_icu=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_system_libwebp=false skia_use_system_zlib=false
                  ^----
```
I tried doing it in bash and zsh, but I keep getting these errors.
### Aseprite and System version

* Aseprite version: https://github.com/aseprite/skia/commit/84d90d4f7c7f958f60f819503fa8ce57d3257082
* System: Ubuntu 17

**Comment by KashouC** [comment]
I don't know much about this topic or Linux distros, but all I can find is people using single " tags for the things that need it on Debian. cc="clang". I've also seen the argument is_clang=true and using target_os as well but you'll have to test em out yourself and see, but unless they're in the instructions I doubt they would change anything since this seems to be a syntax error. 

Also seen people use --args='args here' instead of "args here" in relation to debian so I guess that's something you could try but not sure it even matters lmao, but I had issues with simple stuff like spaces after the = so you never know. :man_shrugging: .

**Comment by DuendeInexistente** [comment]
I *think* I might have solved this, the ghetto way. I added the arguments to args.gn manually, single ticks.
Ninja is executing clang now, although I'm not sure if one of the previous commands might have set up something else for me too.

**Comment by KashouC** [comment]
If you got it to work properly I'd be interested in what you put in the args.gn file, if you don't mind.

**Comment by DuendeInexistente** [comment]
Yup, it compiled fine.

**Comment by donovan-digital** [comment]
For reference, this is args.gn file inside of out/clang, yes?
