### ISSUE TITLE
Feature Request: Support for Pixaki filetype

### ISSUE THREAD

**Issue by xentripetal** [aseprite/aseprite#1947]
Wondering if it would be possible to eventually add support for Pixaki filetypes so that it would be possible to work with both as they use the same concepts for Frames and Layers.

The Pixaki filetype is a zip containing UUID named PNG's of each layer for each frame with an XML description of the data called "DocumentInfo.plist".
Example Folder Structure

- DocumentInfo.plist
- LayerD549EA51-7B9B-4554-9994-19EBC8B5FEB2.png
- ...
- LayerEBF3A5F1-30E8-4643-B619-1A02E236C85D.png

 The XML structure is using Apples Property List shown here https://www.apple.com/DTDs/PropertyList-1.0.dtd 

The  general structure is a dictionary containing the current color pallet, brush sizes, the height and width, and a list of all frames along with all the layers inside that frame. I have attached a sample of the file format below.

[Example Format.pixaki.zip](https://github.com/aseprite/aseprite/files/2661123/Example.Format.pixaki.zip)

I will attempt to make a FileFormat class for it in the future if this is outside the scope of currently supported features. However I have very little experience with C++ so there is no guarantee of this.

**Comment by dacap** [comment]
Hi @xentripetal, there are no plans to add support to other file formats of third-party sprite editors (at least not formats that are not widely used, maybe in the future I could add support for TiledMap or PyxelEdit formats).

My recommendation for this case is that you could create [a .lua script](https://github.com/aseprite/api) to load/save pixaki files (using [io.open()](https://www.lua.org/manual/5.3/manual.html#pdf-io.open)), that would be easier to program (because you don't need to use C++).
