### ISSUE TITLE
Adjustments>Brightness/Contrast does not apply changes correctly to selections of indexed images.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#1959]
The changes are correctly applied to the preview area, but when it comes time to apply the adjustment to the image permanently, the entire selected area is set to the same index value.

![brightcontrast bug idx select](https://user-images.githubusercontent.com/11544843/50366928-a0806a80-054a-11e9-8905-e1d9a54c37a5.gif)

_Only relevant when there is an active selection; without one, the function operates correctly, although it works on the palette and not on pixel indices._

Thanks for looking into it! :D 

..using ASEprite 1.2.9-x86 on Win10.

**// UPDATE:**

It looks like it works if you set the _Timeline selection mode_ to "Selected" instead of "All," it can manage it. I am not sure why. ^^;

![image](https://user-images.githubusercontent.com/11544843/50367138-218c3180-054c-11e9-9e58-bbf612731acb.png)

Hope that helps!

**Comment by dacap** [comment]
Hi @oceanhahn, this might be because the filter is being applied in an empty cel (or a cel that is almost transparent in the area).

Does your sprite contains several layers? or just one layer? is the brightness/contrast filter applied to several layers (e.g. when "All" option is selected).

It might happen that the preview layer is displayed correctly and applied correctly because the filter is applied to just one layer, but after applying the filter, if there is another layer above, maybe all its pixels are set to a black color. (check if you can remove the content of the other layer and leave only the content in the layer that you was previewed correctly).

**Comment by oceanhahn** [comment]
It looks like that got it!
I did not know what the [Selected/All] switch did but it makes sense now. I cannot remember which layer I had selected when I made the .gif but it looks like your instructions solved it.

I will keep an eye on it and let you know if there are any exceptions, but for not it looks like I was just using the tool incorrectly (wrong layer selected? / incorrect layer selection mode).

Will reopen if I rediscover the problem later.
Thanks again! :D
