### ISSUE TITLE
Issue with double clicking to open files

### ISSUE THREAD

**Issue by FrezCold** [aseprite/aseprite#1992]
Describe your bug report or feature request here
I can't double click to open a file, but rather I need triple click to open it. Is this a bug or a feature?

### Aseprite and System version 
1.3

**Comment by dacap** [comment]
I'll need more information about what specific version you are using. As "1.3" was not yet release, I guess that you are using a compiled version, do you know what specific commit did you compile? and what operating system are you using (Windows, macOS, Linux)?

**Comment by FrezCold** [comment]
I'm not that sure about the specific commit I compile because I took it from someone else who compiled it already. I'm using Window.

**Comment by dacap** [comment]
Ok, I'll close this issue at the moment, but if in the future you know this information we can continue testing this issue and re-open it.

**Comment by andyroiiid** [comment]
Got the same problem.

### Aseprite and System version

* Aseprite version: [GitHub Release Tag v1.2.9](https://github.com/aseprite/aseprite/releases/tag/v1.2.9), the compiled executable has a title "Aseprite v1.3-dev", though.
* System: Microsoft Windows 10 Enterprise LTSC 10.0.17763 Build 17763

Compiled with Visual Studio 2019 Version 16.0.2.

I modified the `gn/BUILDCONFIG.gn` in skia so that it can find the correct `win_vc` path for VS2019, but I think that's irrelevant to the triple clicking problem.

The steam version on my computer doesn't have this problem, but I don't want to launch steam every time I use aseprite...

**Comment by andyroiiid** [comment]
And I noticed that the title problem was also mentioned in #1991.

**Comment by dacap** [comment]
@andyroiiid you got the same problem about the double-click not working on the file selector? could you please try the latest `master` branch?

**Comment by hsandt** [comment]
Linux Mint 19.2 Cinnamon
Aseprite v1.2.21-x64

No double click, no triple click opens any file nor folder.
Preferences > Experimental > use native file dialog doesn't change the file dialog at all

I can also check on Windows 10.

Is that enough to reopen the issue? If you don't because it's technically not the OP's issue (who uses Windows and succeed with triple-click), I'll open another one for Linux. But the issue title is currently generic enough to apply to all of our cases, so you would have to update this issue's title as well.

**Comment by dacap** [comment]
The native file dialog is not available on Linux (but it should work on Windows).

About the double-click, do you mean double-clicking in the Aseprite file dialog is not working or double-clicking in the file explorer of Linux (e.g. trying to open a .aseprite file from the native Linux file explorer)?

**Comment by hsandt** [comment]
Double-clicking in the Aseprite file dialog. I expect to it behave similarly to the system file explorers.

Maybe we should indicate that "native file dialog" is not available on Linux, gray it out or remove it completely on Linux builds?
