### ISSUE TITLE
Issues with drawing tablet.

### ISSUE THREAD

**Issue by Axteus** [aseprite/aseprite#2068]
I installed Aseprite yesterday and at that moment it used to work perfectly fine, though I find now that whenever my pen touches my tablet the pointer just sits there not moving. I've already tried
reinstalling, switching to another version, and unplugging my tablet and plugging it in again.

The tablet I'm using: Wacom Intuos PT M

**Comment by KashouC** [comment]
Hmm, well, you said you've tried switching versions, but the only thing I can think of is to try this specific version: WacomTablet_6.3.29-6
Anything after that has had issues for me. Not in Aseprite, but in other programs, but I've met people who had issues in Aseprite too.

**Comment by Axteus** [comment]
I meant switching versions of Asperite, not the tablet itself. The tablet works just fine on other programs, it seems to be Asperite itself that's not working.

**Comment by KashouC** [comment]
I recommend trying the version I mentioned. Newer versions have a lot of random problems with seemingly random programs.

**Comment by Axteus** [comment]
Weird, since it seems to be Asperite and Only Asperite where I'm having this issue, and seeing how in other threats people have been having this exact problem I somehow doubt it's the table's problem. But if it really is the tablets problem then I might just go search for another sprite-making program since I'm definitely not going to get a new tablet for this specific program.

**Comment by Axteus** [comment]
Alright, I fixed it. Turns out I had to go to my "Wacom Tablet Properties" then going to "Mapping" and turning off the "Digital Ink" box.

**Comment by KashouC** [comment]
Well, like I said, Wacom drivers are notorious for having issues in the newer versions. That's why I recommend the one I posted. For me, Aseprite worked fine but neither GIMP nor Krita worked properly, and I've seen the driver issue many many times in the past.

But glad you fixed it. Just remember what I said if it ever starts acting out again.

**Comment by Kuuze** [comment]
> Alright, I fixed it. Turns out I had to go to my "Wacom Tablet Properties" then going to "Mapping" and turning off the "Digital Ink" box.

THANK YOU SOOO MUCH!!! I had the same problem with my huion tablet but I could fix it thanks to you.

**Comment by Jwebbe512** [comment]
Update
Drawing tablet:Gaomon PD16111 ($200 on amazon)
I had the same issue for about 4 minutes and then I read these comments.
Go into your setting and at the bottom right may have a key saying activate administration or something like that. Once you click that it should work. If it doesnt work after that, at the top in the search bar, search up the program you are trying to use it for (i.e: aseprite for me) and it select it (click other programs and search it by files). I understand if your confused because I didnt have to do this for blender or gimp but had to do it for aseprite, however, came here before I did anything that may cost and it paid off a lot. Hope this helps with other tablets.
