### ISSUE TITLE
Undo hotkey issue (macOS)

### ISSUE THREAD

**Issue by sumibi-yakitori** [aseprite/aseprite#2069]
![AsepriteUndoIssue mov](https://user-images.githubusercontent.com/1794232/57582336-5cdccc00-74fe-11e9-92fb-bc338c9381c3.gif)

When I use Asprite and want to undo, after pressing Cmd + Z, the actual process won't run until I release the key.
This problem does not exist with redo.
This problem does not exist in Aseprite v1.2.9

### Aseprite and System version

* Aseprite version: v1.2.11 and v1.2.10 (Steam)
* System: macOS High Sierra 10.13.6

**Comment by dacap** [comment]
I'll take care of this one. The issue here is that the macOS events queue is not being processed because Aseprite thinks that there is no more messages to process so it can take a nap to wait for macOS events.

1) If you move the mouse while pressing Cmd+Z, you will see that the update works in the moment without releasing Cmd+Z
2) If you play an animation in a side in other sprite (or the preview), and try to undo things in the first sprite, the undo will be immediately too (because playing an animation makes Aseprite listen the macOS events queue actively while processing internal timer messages to play the animation).
