### ISSUE TITLE
4mb file crashes Aseprite

### ISSUE THREAD

**Issue by Hearthing** [aseprite/aseprite#2079]
Describe your bug report or feature request here

I've been working on a 128 x 128 animation for the past few weeks. It has 4 layers and 32 frames. I haven't had any issues at all with exporting the file before at 200% to 500% of its normal size. Today, I tried rendering it at 500% of its size and set the tick boxes to export for twitter and keep the pixel ration. The program froze up and I received an insufficient memory error. I've rendered it at that size before and didn't have any problems. I restarted my PC and opened up Aseprite. Usually the program loads up very quickly, but now it took almost 15 seconds to load. I opened up my file and it took 30 seconds to load whereas it used to be instantaneous. I decided to render it at the 200% size I had been using for weeks, and again my program crashed and I got the same error message. I deleted Aseprite and re-installed it and still the issue is persisting.

### Aseprite and System version

* Aseprite version: Aseprite v1.2.11-x64
* System: Ubuntu 18.04

**Comment by dacap** [comment]
Hi @Hearthing, would it possible if you can share some files privately with us for testing to support@aseprite.org?

When Aseprite crashes, it generates some files in the `sessions` folder inside the preference folder (`~/.config/aseprite/sessions` on Linux):

  https://www.aseprite.org/docs/data-recovery/

If you can compress that folder and share it with us at support@aseprite.org we can take a look to test this "15 seconds to start the program" issue. After that, you can try to delete this folder and see if Aseprite starts faster again.

About the Resize to 500% issue, there is an issue at the moment that the operation requires a lot of RAM because the sprite is temporarily resized, saved, and then undone. In future versions the operation should be on-the-fly (in the same save operation, instead of doing this resizing on memory).

**Comment by Hearthing** [comment]
Hi @dacap. I figured out the issue. Somehow one of my layers (the background one) got accidentally resized to 4k and my computer couldn't handle rendering 32 frames at that resolution. I'm not sure how that happened, but after I resized the layer properly, all of my issues stopped. I'd sure like to know how that specific layer and none of the others got resized, but for now everything is back to normal.
