### ISSUE TITLE
Significant UI lag when dragging any tool over a large area (Linux)

### ISSUE THREAD

**Issue by dpacbach** [aseprite/aseprite#2089]
Hello,

There seems to be a major issue where performance suddenly drops to a point where Aseprite because unresponsive for about 30 seconds when zooming in and then selecting a square using the rectangular selection tool.  To be specific, here is how I reproduce it:

1) Open new sprite 128x128
2) Zoom in to zoom level = 4800
3) Choose the Rectangular Marquee Tool
4) Start dragging a selection box around some pixels (opaque or transparent)
5) Once the box gets bigger than ~ 16x16 the UI starts to increasingly slow down.
6) Once the box gets to be about 32x32 pixels then the UI becomes unresponsive and I have to wait about 30 seconds for it to be responsive again.

Please tell me that I am doing something wrong and/or how to fix this, since it is making Aseprite somewhat unusable for me!  If it is in fact a bug with a simple fix then I can try to submit a PR for it myself since I am a developer.

Thanks
David

### Aseprite and System version

* Aseprite version: 1.3-dev (built from latest commit in repo), although I've had the same issue with previous versions, so it has existed for a while.  4k monitor, with UI scaling to 200% (though not sure if that is relevant).

* System: Linux Mint 19.1 / Cinnamon desktop.  Power machine with 8 cores and 64GB memory (i.e., a program like Aseprite should have no problem doing basically anything on this system).

**Comment by dpacbach** [comment]
This also happens when drawing a rectangle (under the same conditions, i.e. zoomed in).  I think something is very wrong here.  If you are unable to reproduce this (which is what I'm assuming, since I trust that if you had noticed it then it would have been fixed) then, if it helps, I can rebuild my copy with any logging or diagnostic statements inserted in the code that you recommend.

**Comment by dpacbach** [comment]
Just confirmed that this is also happening on Pop!_OS 19, which is essentially Ubuntu, and so I would assume it is happening on Ubuntu as well (i.e., it is happening on two of the most common Linux distros).

**Comment by dodobyte** [comment]
I have this issue on Ubuntu 19.04, zoomed in or not, while selecting a large area, it uses too much CPU and hangs.

**Comment by dpacbach** [comment]
@dacap Any chance that you can take a look at this?  It really makes useing Aseprite hard on Linux... can you at least confirm that you can reproduce it?  Thanks

**Comment by dpacbach** [comment]
Also, if you succeed in reproducing it and you can suggest where in the code base the problem might be, then I can take a look at trying to fix it myself and sending a PR, but I would first like you to confirm that you can reproduce it.

**Comment by dpacbach** [comment]
@dacap I spent some time looking at the code and I think that this is caused by the following two issues:

1. In `ToolLoopManager::CalculateDirtyArea` is creates a dirty area that includes too many pixels when e.g. dragging a rectangular marquee (it includes all pixels inside the box which probably it doesn't have to).  This causes all of those screen pixels inside the box to have to be updated on each mouse movement, which causes the slowdown I believe.

2. If the behavior in (1) is expected, then perhaps the graphics code that redraws the dirty region is running too slow, and is not able to keep up with a smooth mouse drag when the dirty area is large.

I guess that, e.g. when the user is dragging the mouse to create a rectangular selection, the dirty region should be only consist of the boundaries of the old/new box and not all pixels inside.  What do you think?

**Comment by pavelbrn** [comment]
I can confirm, I have Ubuntu running. Every single time I use the Gradient Tool in Aseprite I see a very large performance drop, it lags to the point of being unusable.

**Comment by dpacbach** [comment]
Noticed in the release notes for v1.2.19 it says: "Improve performance drawing selection boundaries"... does that address this issue?

**Comment by dacap** [comment]
@dpacbach I don't think so, I've to review this a profile the tool loop, taking note about your previous comment to review later

**Comment by dpacbach** [comment]
@dacap Thanks that will be greatly appreciated

**Comment by kpcftsz** [comment]
So my issue isn't _just_ making the selection itself, but also dragging the selection afterwards (and rotating, and scaling...) 

Probably a shot in the dark but I did notice that removing the KeyAction from `MovingPixelsState::onMouseMove` improved performance while dragging a bit, so as an experiment I setup `x11_is_key_pressed` from LAF to just return false (so `XKeysymToKeycode`, `XQueryKeymap`, etc. aren't called at all) and saw a massive boost.

Obviously this is a hack and causes many hindrances like not being able to lock to a certain axis while dragging or snapping to a certain angle while rotating, but it does reduce the lag enough to the point where the editor is usable. I still doubt it's the actual culprit, but if anybody else is reading this and (like me) just needs the editor to work well for small sprites and doesn't need all the bells and whistles, it's a fine hack ¯\\\_(ツ)\_/¯

A couple other things:
 - The selection size doesn't seem to matter as much as zoom level does, i.e. a 250x250 selection on a 500x500 image won't lag at all when I'm zoomed in 25%, but at 100% it lags a lot.
 - This isn't exclusive to just dragging out boundaries, I get the same behavior (on Arch Linux using 1.2.25) when trying to scale or rotate the selection as well.
 - It seems very time sensitive? It feels like less movements (or pixels) per second = less lag. If I drag a 250x250 selection on a 500x500 image at 100% scale, at a steady rate of 20px a second or so (relative to the image, not the window), it finishes quicker than if I did that same drag operation at twice the rate. In other words it's faster for me to drag slowly than drag quickly and wait on the drag to finish, or "the slow and steady wins the race". It's like the editor gets overwhelmed and has to calm down.
 - The move tool is completely unaffected by any of this, it works perfectly.

Another minor semi-related note:
 - Some windows such as the new sprite window can be resized fine without any issues, but others like the preferences window stutter while being dragged much like the selection tools do.

**Comment by insertable** [comment]
Just wanted to chime in and say I've had a similar problem with both Arch and Ubuntu. Trying to gradient fill a 1920x1080 canvas froze Aseprite for a good 20 seconds. I even had problems at 800x600. The Arch version was built from source, and for Ubuntu I was using the deb package from Humble Bundle.
As kpcftsz mentioned, zooming out significantly increased performance and made it somewhat usable.

**Comment by mttkay** [comment]
Same problem here. I'm on Pop_OS 20.10 (Ubuntu based) and am using an HP 4k monitor. Laptop is a DELL Precision with 8 i9 cores and 32 GB of RAM.

Even simple things such as using the marquee tool to select a rectangular area on a small-ish canvas (512x320) is unusable.

I noticed the same issue with the color replace tool. Replacing colors of larger areas such as the entire canvas is unbearably slow, often 10 seconds or more.

That said I am using `libresprite` but I'm assuming they use the same rendering stack since they derive from the same code base?

**Comment by dacap** [comment]
Please I would appreciate if all bugs reported are related to the official releases of Aseprite (and latest version / distributed .deb files). And not from other versions of the programs or personal compilations (we've changed the Linux back-end from v1.1 -> v1.2.10-beta1)

**Comment by mttkay** [comment]
> Please I would appreciate if all bugs reported are related to the official releases of Aseprite (and latest version / distributed .deb files). And not from other versions of the programs or personal compilations (we've changed the Linux back-end from v1.1 -> v1.2.10-beta1)

That's fair enough. If there's a trial available I'm more than happy to test it and see if the problem persists, though according to other reports here it does appear to affect both LibreSprite and Aseprite. If there is anything else you would like me to include in the test reports, please let me know.

**Comment by dacap** [comment]
The trial is available in the website: https://www.aseprite.org/trial/ (just in case the .deb file can be uncompressed and executed almost on any Linux distro)

**Comment by mttkay** [comment]
@dacap The problem remains, unfortunately. I pulled a CPU profile for 30 seconds and this is what it was doing as I was dragging the marquee frame (which is what is slow for me):

![Screenshot from 2021-05-19 14-59-23](https://user-images.githubusercontent.com/102802/118817009-0fe11c80-b8b3-11eb-9819-2fce095e962e.png)

Does that help?

**Comment by dacap** [comment]
Thanks @mttkay, the issue is in the rendered, it's strange if this problem appears in small images, but it's common if you are editing large canvases. What canvas size are you editing? Anyway we have plans to re-write the whole rendering process in a near futuro.

**Comment by mttkay** [comment]
> @mttkay Thanks for that, that was a good idea to do the CPU profiling, hopefully it will help the developer(s) to identify the problem! Out of curiosity, what program did you use to do that profiling?

Ah sorry -- I should have mentioned that. This is just `perf`, it's a sampling profiler (and more, kind of a swiss army knife for better or worse) and it comes with the Linux kernel packages I think. I ran it like so:

```shell
sudo perf record -p $(pgrep aseprite) -- sleep 30
```
This will dump the profile into `perf.data`. You can then look at it via `perf report`.

It's not the best way to look at this data, however. There are ways to turn this into a flame graph for instance. I'm at work now but I can have a look later if it helps.

**Comment by mttkay** [comment]
> What canvas size are you editing?

This was on 512x320, which I suppose is large-ish for pixel art. But it's necessary when sketching out game UI, for instance, or background art that is not tiled, so not outlandish I would say.

**Comment by dacap** [comment]
Oh 512x320 is not large at all. One possible issue I can think of might be related to high-precision mouse events. Maybe the mouse is generating too many events and it fills the events queue.

Anyway there are 3 refactors that I'm planning to do in a near future (in this order):

1. A background thread to process mouse events / drawing loop
2. A background thread to improve the rendering pipeline (cache all the images that are rendered, etc.)
3. Improve the internal image representation (to use internal tiles/chunks of memory to sub-divide the canvas)

**Comment by mttkay** [comment]
OK I pulled something a bit more useful. I ran the same profile, just for 15 seconds, but with call-graph info enabled and converted it to a format that can be ingested by a flamegraph viewer such as SpeedScope (my favorite, personally):

```shell
sudo perf record -g -p $(pgrep aseprite) -- sleep 15
sudo perf script -i perf.data > aseprite-linux.txt
```

This makes it easier for others to work with this data, too.

I have attached an archive that contains a text file with the stack frames in a format SpeedScope understands. You can just download it, unzip it, and throw the text file at SpeedScope to see what I am seeing: https://www.speedscope.app/

This is what I got:

![Screenshot from 2021-05-19 20-02-48](https://user-images.githubusercontent.com/102802/118862227-bf32e900-b8dd-11eb-8239-bb07289c5868.png)

The first thing of note is that about a 3rd of all time was spent in a function for which there is no symbol data available; I'm not sure why. It could be that Aseprite is linking a library that was compiled without debug symbols. The Aseprite authors might recognize it for what it does, I hope. I'm suspicious of this section since down the stack it calls the same functions that also appear again top-of-stack to the right, it could be that they were called recursively, or maybe the missing symbols are tripping up the profiler.

Anyway, at least a good third was spent in the two methods I had mentioned before: `rgba_blender_normal_dst_over` and `rgba_blender_normal`. It is interesting to see that this is the whole "layer cake": self-time = total time means this CPU time was actually spent _inside_ these methods, not somewhere further down the stack. This was something I wasn't sure about earlier.

It also spent quite a bit of time in system calls: over a second. Is this an input event loop maybe? You mentioned mouse events, so this could be it. I'm not sure.

Anyway, I thought it might help. I'm hoping that maybe there is some low hanging fruit here and we don't have to wait for a refactor of the entire rendering stack :crossed_fingers: 

[aseprite-linux.txt.gz](https://github.com/aseprite/aseprite/files/6510854/aseprite-linux.txt.gz)

**Comment by mttkay** [comment]
Hah, now that I look at the timeline view (I usually don't, since usually it doesn't matter in which order stuff is called, just how much CPU is spent on it), you can clearly see how Aseprite ran fluently at first (this is where the event loop was operational), then it spend 10 seconds in these two `rgba_*` offenders not processing any events, then finally settled down again. So @dacap hit the nail on the head when he said that this seems to suffer from a lack of multi-threading; input should not block on rendering routines or vice versa, since that's what makes a UI janky. :+1:

**Comment by mttkay** [comment]
Another take-away and then I'm going to leave it at that: the timeline-view also reveals that these functions are actually reasonably fast, about 1.5-3 ms per call. It is the sheer number of calls that add up to so much CPU time. They are likely called in a loop, perhaps when iterating canvas w*h (that would support my observation that performance degrades exponentially the larger the canvas and/or marquee rectangle?) If it is at all possible to memoize these calls and reduce the number of invocations, then this would probably fix the issue. But making them faster will likely not help.

(I suppose timeline view is more useful than I gave it credit for! :grimacing:)

**Comment by mttkay** [comment]
I compiled aseprite from latest `main` and had another look. I ran a profiling session repeatedly and verified that a lot of time is spent in system calls; this is bad, because system calls such as `readv` / `writev` require a mode switch from user to kernel space. In the profiles I pulled, most of the time was spent in system calls like `writev` and `poll`, apparently to manage timers and do UNIX socket I/O (?). I am not sure why it's doing that, is that a Skia thing?

![Screenshot from 2021-05-29 16-40-40](https://user-images.githubusercontent.com/102802/120074342-a88a5000-c09c-11eb-8b6f-d1f83514463a.png)

As mentioned before already, the timeline view shows that these system calls are very frequent and interleaved with "actual" work Aseprite needs to do such as calling the rendering methods mentioned above. However, since the application is suspended while waiting for the result of those system calls, it results in very choppy UX.

When I trace the system calls the app issues, I notice that they are very frequent, and are mostly reads, writes and polls as well as occasional sleep timers:

```shell
$sudo strace -p $(pgrep aseprite)
...
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\16\2\2\0\1\0\200\6", iov_len=8}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 8
poll([{fd=3, events=POLLIN}], 1, -1)    = 1 ([{fd=3, revents=POLLIN}])
recvmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="\1\30|\321\0\0\0\0}\t\0\0\1\0&\0\200\7\370\3\0\0\0\0\0\0\0\0\0\0\0\0", iov_len=4096}], msg_iovlen=1, msg_controllen=0, msg_flags=0}, 0) = 32
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="H\2B\377\1\0\200\6\2\0\200\6\336\3B\0\6\1b\0\0\30\200\6", iov_len=24}, {iov_base="XXY\377XXY\377XXY\377XXY\377XXY\377XXY\377XXY\377XXY\377"..., iov_len=261360}, {iov_base="", iov_len=0}], 3) = 219264
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="\322\322\322\377\322\322\322\377\322\322\322\377\322\322\322\377baa\377baa\377=<<\377=<<\377"..., iov_len=42120}, {iov_base="", iov_len=0}], 2) = 42120
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="H\2B\377\1\0\200\6\2\0\200\6\336\3B\0\6\1\244\0\0\30\200\6", iov_len=24}, {iov_base="\305\305\305\377\305\305\305\377\305\305\305\377\305\305\305\377\305\305\305\377\305\305\305\377\305\305\305\377\305\305\305\377"..., iov_len=261360}, {iov_base="", iov_len=0}], 3) = 261384
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="H\2B\377\1\0\200\6\2\0\200\6\336\3B\0\6\1\346\0\0\30\200\6", iov_len=24}, {iov_base="\270\270\270\377\270\270\270\377\270\270\270\377\270\270\270\377\270\270\270\377\270\270\270\377\270\270\270\377\270\270\270\377"..., iov_len=261360}, {iov_base="", iov_len=0}], 3) = 261384
poll([{fd=3, events=POLLIN|POLLOUT}], 1, -1) = 1 ([{fd=3, revents=POLLOUT}])
writev(3, [{iov_base="H\2\306{\1\0\200\6\2\0\200\6\336\3 \0\6\1(\1\0\30\200\6", iov_len=24}, {iov_base="\35\35\35\377\35\35\35\377\35\35\35\377\35\35\35\377\35\35\35\377\35\35\35\377\35\35\35\377\35\35\35\377"..., iov_len=126720}, {iov_base="", iov_len=0}], 3) = 126744
clock_nanosleep(CLOCK_REALTIME, 0, {tv_sec=0, tv_nsec=2556000}, ^Cstrace: Process 175037 detached
...
```

I don't understand Aseprite's rendering stack or Skia yet, but I am wondering why Skia or the app spend so much time in socket I/O? Is there something that can be done to free up CPU for actual rendering routines, since this really makes the app painful to use.

**Comment by dacap** [comment]
@mttkay there is an huge hack in [ui::MessageLoop](https://github.com/aseprite/aseprite/blob/main/src/ui/message_loop.cpp#L39), mainly for Linux (using `usleep()`) but it's used in all platforms, to avoid a 100% CPU, but I have an on-going patch to replace all event queues with timeouts (in case of Linux, we should use [XtAppAddTimeOut](https://www.x.org/releases/X11R7.5/doc/man/man3/XtAppAddTimeOut.3.html)). The idea is that when Aseprite needs a timer (i.e. wakeup the "event waiting", for example to play an animation or blink the text cursor) we could wait for an event but with a timeout. This is something I have been working on but it's not yet ready, anyway I'm not sure if it's related to this issue.

**Comment by mttkay** [comment]
Ah interesting! Thanks for the links as well. Great to hear it's being worked on, appreciate the effort. Feel free to throw any patches my way if you need help testing!

**Comment by dpacbach** [comment]
@dacap I checked out the `main` branch of Aseprite, then updated the laf submodule to the `beta` branch which appears to contain commit aseprite/laf@f443e19 (and updated its own submodules) and then did a full build of Aseprite, but I'm getting various compile errors.  Can you give instructions on how to checkout/build it?

**Comment by dacap** [comment]
Sorry @dpacbach, both branches are incompatible (the beta branch of laf has several refactors), at the moment you can only try this change in the v1.3-beta2 on Steam. But next week I'll try to back-port the change from aseprite/laf beta branches to the main public branches. So at the moment, if you are compiling Aseprite, you will not be able to access the change yet.

**Comment by dpacbach** [comment]
Ok thanks for the quick reply.  Since I build Aseprite myself and don't have access to the Steam version, I will wait for you to back-port it to github.  Thanks

**Comment by dodobyte** [comment]
@dacap sadly the issue persist. Here's a video.
https://streamable.com/vy7lm8

**Comment by dacap** [comment]
Thanks for the video @dodobyte! we'll try to continue improving it. Will comment again when have some news about it.

**Comment by dpacbach** [comment]
If it helps, I will point out that the UI lag becomes "exponentially" worse as the size of the dragged rectangle increases; for small areas it is not so noticeable, but when the rectangle becomes larger, the lag quickly increases to the point that the rectangle stops dragging.  This is what I observe and that you can also observe in the video above.

@dacap Have you yet been able to reproduce this yourself?  If not, then I might recommend just downloading Linux and running in a virtual machine such as VirtualBox (both are free), and hopefully you will be able to reproduce it there.

**Comment by mttkay** [comment]
I can also confirm that the problem persists in the beta version.

I also realized meanwhile that it's more pronounced and easier to reproduce when you zoom in closely on a large sprite, and then perform some kind of area operation such as marquee selection. Especially when both dragging the selection and scrolling simultaneously to extend the selection beyond the current view boundaries, it becomes very noticeable. Conversely, it is much faster or barely an issue when zoomed out all the way and being able to select the same region of pixels without panning. That leads me to conclude it is not just a function of pixel counts selected in a given rect, but something else is at play.

**Comment by nonetrix** [comment]
Linux has generally been extremely laggy for me I think I might just use proton

**Comment by not-surt** [comment]
This seems to be fixed for me in v1.3-beta8.

**Comment by dacap** [comment]
Thanks @not-surt and @dpacbach to give it a try to the fix.

I'll close it but we can continue commenting and we can re-open the issue if needed.

The solution was given by [this patch](https://github.com/aseprite/aseprite/commit/26c1a94b833c2e0b56ea6300f8b14e14ada58c62), basically "grouping" several mouse movement events in just one, i.e. do not process mouse movement immediately but [wait 5 milliseconds](https://github.com/aseprite/aseprite/commit/26c1a94b833c2e0b56ea6300f8b14e14ada58c62#diff-cf9ab518a4be1b716ceb4827d24e1d6a7c4e9b0c1aa8c0ba5650e6c87b0c8c3aR65) before we process the mouse event as input. This is because Linux likes to flood the event queue with mouse events a lot, so processing all the events don't make sense for tools like rectangle, line, etc. if we only need the latest/newest mouse coordinate.

If you've just compiled it, you can try changing 5 to 1 [here](https://github.com/aseprite/aseprite/commit/26c1a94b833c2e0b56ea6300f8b14e14ada58c62#diff-cf9ab518a4be1b716ceb4827d24e1d6a7c4e9b0c1aa8c0ba5650e6c87b0c8c3aR65), and it might look more responsive (I guess).

**Comment by dpacbach** [comment]
@dacap Thanks for the explanation, glad that we finally have a fix.
