### ISSUE TITLE
Create palette creates duplicated black color

### ISSUE THREAD

**Issue by l-Marty-l** [aseprite/aseprite#2109]
<img width="747" alt="Screenshot 2019-07-14 at 21 27 21" src="https://user-images.githubusercontent.com/24259245/61188376-66a9b980-a67e-11e9-8507-543c1d3580cc.png">

When I select "Create Palette from current Sprite", it will add black twice. Both are #000000 with Alpha 255.

### Aseprite and System version

* Aseprite version: v1.3-dev
* System: macOS, 10.14.5

**Comment by dacap** [comment]
Do you have a transparent layer using the black color? in that case this might be because the first black color (palette entry number zero) is used as transparent color for transparent layers, and the second black color is the black color used in transparent color when a solid black pixel is needed.

**Comment by l-Marty-l** [comment]
> Do you have a transparent layer using the black color? in that case this might be because the first black color (palette entry number zero) is used as transparent color for transparent layers, and the second black color is the black color used in transparent color when a solid black pixel is needed.

My transparent layers use transparent as color, so a second black color makes no sense to me.

**Comment by dacap** [comment]
I've seen the file you sent me (only transparent layers, with black color on some of the layers), and it looks like a bug, mainly because Aseprite generates the first black palette entry with alpha = 255 (100%) even when the "Create entries with alpha component" checkbox is selected.

So my conclusion is:

1) If you use the dialog with the options given as in the screenshot, two black color entries will be generated anyway (because entries with alpha cannot be generated)
2) If you check the "Create entries with alpha component" option, instead of two black colors you should see the first palette entry (index 0) with alpha=0 (which this is not happening, so here is the bug).

**Comment by l-Marty-l** [comment]
> 1. If you use the dialog with the options given as in the screenshot, two black color entries will be generated anyway (because entries with alpha cannot be generated)

Ah, that explains the 2nd black color, indeed.

> 2. If you check the "Create entries with alpha component" option, instead of two black colors you should see the first palette entry (index 0) with alpha=0 (which this is not happening, so here is the bug).

Yes, I experience the same, I tried to check the check box before as well and still two colors. Glad you can reproduce the issue.
