### ISSUE TITLE
App doesn't start

### ISSUE THREAD

**Issue by riivia** [aseprite/aseprite#2131]
I have Aseprite on Steam on Windows 10. It's the most actual version at the moment, but changing to any betatest option doesn't help.
I was using it, and everything worked. Yesterday it just stopped opening. I don't think that it even appears in program manager for a second. Restarting the PC doesn't help. As well as reinstalling and deleting files in %appdata%. I even tried installing it on another drive, but that didn't work too.

**Comment by KashouC** [comment]
Mmm, you said you already tried deleting the appdata files so this is probably not helpful, but I'll link it anyway in case you did something differently: https://www.aseprite.org/docs/reset-preferences/

You can also try this if you are using a tablet, or just try unplugging it. https://www.aseprite.org/docs/wintab/

**Comment by riivia** [comment]
I deleted the files again, didn't help. I had my tablet unplugged all the
time, so I tried connecting it, repeated everything, didn't help as well.

wt., 6 sie 2019 o 14:02 Kashou <notifications@github.com> napisał(a):

**Comment by KashouC** [comment]
I've seen people have issues launching it for no reason on Windows 10 multiple times and every time it's resolved itself for no reason as well. I'm not sure what the problem is. There's some Scooby Doo stuff going on and I wish I knew what was the culprit.

The only thing I can think of is that there's some background process in Windows 10 that's knocking out Aseprite's ability to launch, and when W10 is finally done it starts working again.

**Comment by riivia** [comment]
So I keep on trying an write back when it'll work again (or when it doesn't
for a long time)

**Comment by dacap** [comment]
Hi @riivia, please try the https://www.aseprite.org/docs/troubleshooting/ guide, step by step. Sometimes tablets driver (wintab32.dll) doesn't respond well so it has to be (temporarily) disabled or you have to just restart Windows.

**Comment by riivia** [comment]
Thank you. "Disable WinTab" worked.

wt., 6 sie 2019 o 14:55 David Capello <notifications@github.com> napisał(a):
