### ISSUE TITLE
CMake configure error due to Skia folder structure change

### ISSUE THREAD

**Issue by dpacbach** [aseprite/aseprite#2132]
Latest version of Aseprite fails to configure because latest Skia version has a change to folder structure, so its include folder for `skcms.h` is now in `${SKIA_DIR}/include/third_party/skcms` as opposed to `${SKIA_DIR}/third_party/skcms` and this is causing CMake to fail to populate `SKIA_SKCMS_INCLUDE_DIR` in the laf CMake files.  I submitted a PR to the laf repo to fix this, but I'm not sure if that's the right approach.  If it is then I would ask you to accept that PR and then update the version of laf used by Aseprite.

**Comment by dacap** [comment]
At the moment Aseprite must be compiled with the [aseprite-m71](https://github.com/aseprite/skia/tree/aseprite-m71) branch of Skia. The exact version to use will be always specified in the [INSTALL.md](https://github.com/aseprite/aseprite/blob/master/INSTALL.md#building-skia-dependency) guide. We cannot adopt the latest Skia version continuously because Google change the API from time to time. (So some refactors are needed to jump to new versions.)
