### ISSUE TITLE
Cannot auto-pick layer with the move tool on below half-alpha pixels

### ISSUE THREAD

**Issue by KashouC** [aseprite/aseprite#2156]
If you draw something with 100% alpha on the canvas on Layer 3, then move to Layer 4 and hold Ctrl and click it, it will select Layer 3, since it changes to the move tool and Ctrl with the move tool enables Auto Select Layer.

If you change the opacity of the entire layer in Layer Properties to below max alpha, you can still do this and select the correct layer.

However, if you directly reduce the alpha of the pixels using the Hue/Saturation tool or the Color Matrix, you cannot select the layer of the transparent pixel if the alpha is below 50% (it still works above 50%).

![testt](https://user-images.githubusercontent.com/17066488/65228967-b87e1e00-dacb-11e9-9462-b69d6cc1d637.gif)

**Comment by KashouC** [comment]
It specifically only not working <50% makes me think it might be intentional, but I figured I'd make an issue anyway.

**Comment by dacap** [comment]
It's intentional, but it might be confusing (even more when the chosen pixel is the composition of only one layer).

Something to think a little. One possibility would be to change the threshold if there are two or more layers composed (10%? the layer with more alpha?), and if there is only one layer in the pixel with alpha (1%).

**Comment by KashouC** [comment]
Yeah I don't know why it is like it is really, and it's not a big deal because I avoid transparencies as much as possible. Just found it weird to not be able to select the layer.
