### ISSUE TITLE
Crashed on the save dialog when I pressed the back button.

### ISSUE THREAD

**Issue by InstinctLoop** [aseprite/aseprite#2192]
The title of the issue is what happened.

Steps to reproduce:
On a clean install of aseprite, create a sprite (mine was 16x24 (width x height)) then click save and click the back button. The application just closes.

Version = 1.2.15-x64
From: Steam
System: Windows 10 [64 bit] (v10.0.18362 Build 18362)

**Comment by InstinctLoop** [comment]
[Crash Dump File.zip](https://github.com/aseprite/aseprite/files/3827990/Crash.Dump.File.zip)
If this helps...

**Comment by dacap** [comment]
Hi @InstinctLoop, thanks for reporting this. Actually I was able to reproduce this bug in this way (because in the first launch, there is no history to navigate/go back in the file selector):

1. Create a new sprite
2. Save it in a new folder
3. Create other sprite
4. Save it in other folder
5. Remove the first folder created in point 2 from the File Explorer
6. Create other sprite
7. Save other sprite and now navigate backward in the history and when we reach the deleted folder Aseprite crashes

The crash will always appear when a deleted folder is in the navigation history of the file selector and we reach that point through the backward/forward arrows in the dialog.
