### ISSUE TITLE
Out of date Installation Document (LLVM 8.0.0 linked 8.0.1 or higher needed)

### ISSUE THREAD

**Issue by Abel-Moremi** [aseprite/aseprite#2269]
Obtained the error;

  

- #error STL1000: Unexpected compiler version, expected Clang 8.0.1 or newer.

while running command 

- λ ninja -C out/Release skia 

as per the installation document, basically Clan is out of date

### Aseprite and System version

* Aseprite version: 1.3-dev
* System: Windows 10, Home

**Comment by dacap** [comment]
Hi @Abel-Moremi, what version/branch of Skia did you try to compile? did you clone the aseprite-m71 branch?

**Comment by Abel-Moremi** [comment]
- Yess i copied asepite-m71 branch... 

-  To be honest i dont know how to check Skia version and a quick google search did not reveal much... soo sorry i dont know

**Comment by raed21** [comment]
You can donwload 8.0.1 from the following link. [https://github.com/llvm/llvm-project/releases/tag/llvmorg-8.0.1](https://github.com/llvm/llvm-project/releases/tag/llvmorg-8.0.1)
It solved the issue for me

**Comment by Abel-Moremi** [comment]
Hi, @raed21 I solved it also by getting 9.0.1 [here](https://github.com/llvm/llvm-project/releases/download/llvmorg-9.0.1/LLVM-9.0.1-win64.exe) but the install docs need an update. I also opened a pull [here](https://github.com/aseprite/aseprite/pull/2270) to solve the issue.

**Comment by dacap** [comment]
Sorry about this one, I'm rewriting the compilation guide because we'll try to distribute pre-compiled versions of Skia (so no need to install clang at all for end-users). The Skia compilation instructions will be moved to the Skia repository (and we'll update it to clang 9.0.0). I think the pre-built binary 9.0.1 for Windows [is not ready available yet](http://releases.llvm.org/download.html).
