### ISSUE TITLE
Allow native menu on linux

### ISSUE THREAD

**Issue by codic12** [aseprite/aseprite#2354]
This should obviously be optional. Seeing that the macOS implementation has a global menu, this shouldn't be too hard, should it?
I ask because it would feel native (even without a global menu), and I (and many other linux users) use a macOS-esque native menu - thanks.

**Comment by dacap** [comment]
Hi @gsbhasin123 , actually it's quite hard because 1) macOS offers a native interface/framework to create menus (which are integrated to the desktop), and 2) Linux doesn't offer that, and even worse, it depends on the windows manager (GNOME, KDE, etc.). The best way to do something like this on Linux is supposing that we are going to use GTK or Qt and load these libraries dynamically (so no static dependency is created with GTK or Qt) and then create the menus in that way.

If you know other way (maybe a free desktop interface) to do this, please comment about it.

**Comment by gsbhasin123** [comment]
There is libdbusmenu: https://lazka.github.io/pgi-docs/Dbusmenu-0.4/index.html
But otherwise, I understand. In my experience, QT menus do look more native across both gtk and qt platforms, so they would be a better choice (IMO).

I'm also not sure what you mean by the menu depending on the window manager (assuming you didn't have a global menu, the menu would render the same with kde's kwin and gnome's mutter)

**Comment by dacap** [comment]
> depending on the window manager

As we don't depend on any complex library like gtk or qt, we don't have as pre-condition for the user to have those libraries installed (you need X11, xcursor, and now xinput but as it's dynamically loaded, you might not have it installed and Aseprite will run anyway).

We don't have plans to depend on Qt or GTK because that would make Aseprite less portable/have a huge dependency that doesn't make sense for such a simple use case. We prefer to depend only on X11 and libc statically, and load everything else dynamically if possible.

**Comment by dacap** [comment]
Just in case, in the open source world, I don't remember finding a project loading libraries dynamically (they use the dynamic version, .so, but the dependency is static). The best world would be to have a layer that tries to load GTK or Qt (only the needed API) dynamically, and if it's not found we can still run the program (generally that doesn't happen when you use the dynamic version of a library, if the .so is not found, the program doesn't start, and that is something we want to avoid).

**Comment by gsbhasin123** [comment]
I fully agree and would be willing to help with this (although I don't know C++)

**Comment by gsbhasin123** [comment]
Anywhere I can help with this?

**Comment by wwderw** [comment]
I tend to use portable dialog menus to help with this.  For Qt users that would mean have kdialog on the system though.  I think GTK users have a couple of options.
