### ISSUE TITLE
Tablet stabilizer + smooth lines

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#2371]
We should have some way to avoid shaky line and stabilize the tablet input (and the release of the tablet point) to paint smooth strokes/curves/lines.

Affinity has something like this: https://www.youtube.com/watch?v=yd0o8iKcq7A

Medibang: https://www.youtube.com/watch?v=_WCc78vKYAo

But it would be nice to investigate other options.

**Comment by Jasmitt** [comment]
Would love this

**Comment by not-surt** [comment]
Would a "complete line" option that ads an extra segment from the the end of the smoothed stroke to the mouse cursor position be useful?
I don't have any experience using stroke strabilisers so maybe it's expected behaviour but it seems weird to me that when I release the mouse button the stroke doesn't end at the mouse cursor.

**Comment by Cxve** [comment]
@not-surt I always use stroke stabilizers while drawing in GIMP. On higher stabilizer strength settings the stroke rarely ends up at cursor position.
I don't know if this also applies for other software, but that has been my experience with stroke stabilizers at least.
