### ISSUE TITLE
Missing frames on spritesheet generated on Unity (importing .ase files)

### ISSUE THREAD

**Issue by enol** [aseprite/aseprite#2407]
I've been importing .ase files directly into Unity with a self-generated tool inside the engine, avoiding the use of spritesheets (the script slices automaticatically each cell extracted form the .ase) but it seems that the duplicates are merged automatically, similar to the option added on the export panel since v1.2.16.2., only difference is that I'm not exporting the spritesheets.

Could it be that the newer .ase files work differently, and the information that erases duplicated cells is maintained through the process?

The latest version _without_ the enhanced export spritesheet window (v.1.2.15) works fine.

### Aseprite and System version

* Aseprite version: tested with v1.2.17 and v1.2.18, installers
* System: Windows

**Comment by dacap** [comment]
Hi @enol, .ase format didn't change significantly in these years, maybe an issue in that tool you are talking about? Are you taking care of the linked cels?

Anyway I don't understand a specific part: you comment that you're "avoiding the use of spritesheets / not exporting the spritesheets" but then talking about the "export spritesheet window", not sure if that was just a reference to identify version numbers of Aseprite. Take care

**Comment by enol** [comment]
I've been using the same tool since 2016 if I'm not mistaken... So I don't know what's really happening.

I mentioned the export sprite sheet window because the Aseprite versions that included the merge duplicates option (the last four?) are the ones that load the merged sprites into Unity. If I re-save the .ase on 1.2.15 it works just fine. It's like the .ase file changes the way is converted from one ver. to another.
As always thanks for the quick response.

**Comment by dacap** [comment]
Oh I imagine what could be happening, maybe that tool is importing .ase files using Aseprite from the command line (CLI)? if that's the case, I don't think it is using the `-merge-duplicates` parameter, but maybe `-sheet-pack` or `-sheet-type packed`, in that case (for packed sprite sheets) the sprite sheet will merge duplicates automatically anyway because it's using the packed version (the JSON file must be read). If you are not consuming the JSON (e.g. reading sprite sheets manually) I think you should be using other kind of sprite sheet (horizontal, etc).

Anyway could be a bug associated, but I would need more information (mainly how that unity tool is converting .aseprite to spritesheets, or the specific command line that is using).

**Comment by enol** [comment]
Changing the type of sheet pack could interfere with other features of our
importer but don't worry, 1.2.15 seems pretty stable so we'll keep
importing .ase files with it for a while  :)
In any case, thanks for your quick response.
