### ISSUE TITLE
Pixels outside of the sprite's bounding box don't get cropped/trimmed

### ISSUE THREAD

**Issue by CenTdemeern1** [aseprite/aseprite#2456]
Describe your bug report or feature request here
Pixels outside of the sprite's bounding box don't get cropped/trimmed
How to reproduce:
Draw something
Move it halfway outside the bounding box of the image
Crop/trim
And observe!

### Aseprite and System version

* Aseprite version: v1.2.21-dev (from releases)
* System: Microsoft Windows NT 10.0.18363.900

**Comment by dacap** [comment]
Hi @CenTdemeern1 I guess this issue was closed because the Sprite > Canvas command contains an option to trim the content outside the canvas:

![image](https://user-images.githubusercontent.com/39654/161549652-d816643f-7ddb-46b4-90e6-0c686308ed73.png)

Just leaving this comment in case other user see this in the future.

**Comment by CenTdemeern1** [comment]
I closed this because I realized I was stupid and it wasn't a bug
