### ISSUE TITLE
MacOS Menu Bar is non functional

### ISSUE THREAD

**Issue by btrdurfee** [aseprite/aseprite#2457]
Describe your bug report or feature request here
The macOS version builds successfully with the latest code base, but when running the app, the menu bar is non functional. You're unable to click any of the menu items, including the Apple menu. I hadn't built the source in a while, but the last time I did, I didn't have this issue.

### Aseprite and System version

* Aseprite version: v1.x-dev
* System: macOS 10.15.5

**Comment by dacap** [comment]
Hi @btrdurfee, this might be because when you run the compiled application from the command line the window is not activated (something that doesn't happen when it's executed from the .app bundle). You can try press Alt+tab to switch to other window and then back to Aseprite and the menubar should start working. Please confirm us if that does work.

**Comment by btrdurfee** [comment]
Yes, Alt-Tabbing from and back does make the menu bar work, but it also exposes some other odd behaviors. Two things I noticed when the app window is hidden behind another app: (1) When clicking on the dock icon while the app is running, nothing happens - the window should get focus and move to top; (2) When right-clicking on the dock icon while the app is running and selecting Show All Windows, it says "No Available Windows" even though there is an app window open. It should show the current app window and allow you to select it.

**Comment by dacap** [comment]
@btrdurfee can you check if these issues are present in the official release?
