### ISSUE TITLE
Zooming out below 100% uses bilinear interpolation

### ISSUE THREAD

**Issue by lenerdv2005** [aseprite/aseprite#2506]
When the sprite is at <100% zoom level, it becomes blurry (I guess because of bilerp)

**Comment by KashouC** [comment]
This is intentional. Below 100% zoom level you'd either have to use bilinear scaling or simply remove pixels which is arguably an even more inaccurate representation of visuals. You can switch to the old render engine in preferences -> experimental which doesn't use bilinear but it will still cull pixels, since you simply can't display pixels smaller than a pixel.

I think it might technically be bugged in practice when you've got screen scaling set to 200%, as 50% zoom level at 200% screen scaling is actually equal to 100% zoom.

**Comment by lenerdv2005** [comment]
Yeah, got it. I was just asking myself why it "suddenly" started using bilinear
