### ISSUE TITLE
[BUG] Pallet Color Changing

### ISSUE THREAD

**Issue by TheCynicalLiger** [aseprite/aseprite#2508]
# Describe your bug report or feature request here

### BUG
When you change the order of the pallet it will also change the sprite colors

**Before**
![before](https://i.imgur.com/E8NNLX1.png)

**After**
![before](https://i.imgur.com/duO9O3w.png)

## Aseprite and System version

* Aseprite version: Steam V1.2.25-x64
* System: Arch Linux

**Comment by dacap** [comment]
Hi @TheCynicalLiger, that is an expected behavior in [indexed color mode](https://www.aseprite.org/docs/color-mode/), you can press the "Remap" button to fix the colors after your resort the palette:

<img width="355" alt="Screen Shot 2020-09-10 at 16 40 05" src="https://user-images.githubusercontent.com/39654/92792876-4cec2b00-f384-11ea-990d-6d43dcd9d596.png">

**Comment by TheCynicalLiger** [comment]
oh ok thanks :+1:
