### ISSUE TITLE
Why -dev version suffix?

### ISSUE THREAD

**Issue by ryandesign** [aseprite/aseprite#2520]
Hi! I've downloaded Aseprite-v1.2.25-Source.zip from the releases page and compiled it from source. In the About box, it shows the version as "v1.2.25-dev". Why "-dev"? I would expect it to say just "v1.2.25". I would understand "-dev" if I had used some random commit from your repository, but I don't understand it when I've used your prepared source code tarball that corresponds exactly to a specific version.

### Aseprite and System version

* Aseprite version: 1.2.25, built from source
* System: macOS High Sierra 10.13.6

**Comment by dacap** [comment]
Hi there, that helps us to know if the version is the original one or a compiled one by the user (there is no other way we can check if the version compiled by the user). Those scenarios can generate a lot of user support just because a wrong way/flag is used to compile the program (e.g. debug mode). So we prefer to keep this in this way.
