### ISSUE TITLE
Window resizes by scaling

### ISSUE THREAD

**Issue by ryandesign** [aseprite/aseprite#2536]
While the mouse button is down when resizing the main Aseprite window, the window redraws itself by simply scaling the window to the new size. When the mouse button is released, the window redraws properly. The window should redraw itself properly continuously while the mouse button is down. Other Aseprite windows like Preview, Preferences, About already do redraw themselves properly while resizing (though it's questionable whether most of them even need to be resizable).

### Aseprite and System version

* Aseprite version: 1.2.25 built from source
* System: macOS 10.13.6

**Comment by dacap** [comment]
Oh I've made a comment in this issue but didn't appear. This is a known issue. And the solution is quite complex (because we need a cross-platform solution). Anyway there are plans to fix this in a near future. (The Preview window and others are a different kind of windows not related with the operating system windows, so they are handled in an easier way, anyway in v1.3 we will support multiple windows, and this will introduce this problem for those windows too.)

**Comment by dacap** [comment]
This issue was fixed in v1.3 and now was back ported to v1.2.28.
