### ISSUE TITLE
Line tool: modifiers inactive if held before drawing

### ISSUE THREAD

**Issue by buckle2000** [aseprite/aseprite#2537]
Let's say I want to draw many orthogonal lines. I suppose I should be able to hold down <kbd>Shift</kbd> and drag multiple times, but currently I have to first press LMB then Shift for every line I draw.

This is true for circle tool as well, and for Ctrl too.

### Aseprite and System version

* Aseprite version: 1.2.25-dev
* System: Linux

**Comment by dacap** [comment]
Hi there! I tried a quick fix for this one but found a problem with selection tools like Rectangle Marquee or Elliptical Marquee. When you press <kbd>Alt+Shift</kbd> to subtract:

![image](https://user-images.githubusercontent.com/39654/101955129-08b73380-3bdc-11eb-8040-c7f23167a85d.png)

It will start the rotation of the rectangle of ellipse too (because the <kbd>Alt</kbd> key is pressed). We have to think what to do in these cases.

**Comment by dacap** [comment]
Already some problems with Rectangular Marquee users:

* https://steamcommunity.com/app/431730/eventcomments/3109148389570182015/#c3109148389571806941
* Also reported in Discord server

**Comment by dacap** [comment]
We'll revert this change for selection-like tools, but the original feature for line tools will remain. So both worlds will be happy 
(I guess 😅 )
