### ISSUE TITLE
libasesprite. 

### ISSUE THREAD

**Issue by btrepp** [aseprite/aseprite#2560]
Hello, this is just a query foremost.

With the asesprite license, what are your thoughts about a libasesprite?. My use case here is I would like to just use asesprite files directly, rather than having to convert them to png/others for display first.

I do have access to 'shelling' out and calling the cli, but it would be nicer to have a more native integration. Ultimately I would only want to it support the 'export' features, being able to translate asesprite files into other files. This also helps as in development shelling out to the cli is fine, I own asesprite, but for any distribution I need to have a 'baking' step to convert to a distributable format.

### Aseprite and System version

* Aseprite version: any
* System: any

**Comment by dacap** [comment]
Hi there @btrepp, actually all the code to decode files is MIT licensed:

* https://github.com/aseprite/aseprite/tree/master/src/doc
* https://github.com/aseprite/aseprite/tree/master/src/dio

But the encoders are in the app project under the EULA (there are plans to migrate all that to the `dio` library in a future).

Anyway I would recommend you some other library that might be easy to integrate like:

* https://github.com/RandyGaul/cute_headers/blob/master/cute_aseprite.h

This issue is related to #2015 and #379

**Comment by dacap** [comment]
I'm closing this issue as other third-party libraries are better solving this (like the cute_aseprite.h). Maybe in a future we could offer a separated library, but it should be a C wrapper of the C++ API of Aseprite, which I don't know that that would be as useful as a header-only library solution.
