### ISSUE TITLE
Make Keyboard shortcuts layout independent

### ISSUE THREAD

**Issue by LightningAA** [aseprite/aseprite#2572]
Describe your bug report or feature request here

Basically, for fun I'm trying out the dvorak keyboard layout, but I've noticed I have to switch back to qwerty in aseprite to properly use the non-ctrl keyboard shortcuts (e.g. using the dvorak keyboard layout, I'd have to press the n key instead of the b key to pull up the pencil tool).
The way it ideally should work is that typing (e.g. entering a sprite name or a number) should be handled with the system's keyboard layout while keyboard shortcuts should be keyboard layout agnostic. This is how Godot, Blender, Unity, FL Studio etc. handle different keyboard layouts.

*This is a low priority issue, but if it's a simple fix then it would be nice to see it fixed.*

### Aseprite and System version

* Aseprite version: 1.2.25, Steam
* System: Windows 10

**Comment by dacap** [comment]
Hi @LightningAA, I'm testing other software like Affinity Photo and keyboard shortcuts always use the keyboard layout (with Ctrl key pressed or without Ctrl key pressed). Never saw the other behaviour but I should give a try to Godot, Blender, etc.

Anyway I would say that it looks like more a bug on those program, because I think the keyboard layout should be respected in any case, even more, on macOS there is an exclusive layout to use QWERTY for Command+key shortcuts and DVORAK for other cases (but it's a special option on macOS):

<img width="522" alt="Screen Shot 2020-11-30 at 11 20 51" src="https://user-images.githubusercontent.com/39654/100621296-42478f00-32fe-11eb-9660-847dcfc418ee.png">

**Comment by LightningAA** [comment]
> Anyway I would say that it looks like more a bug on those program, because I think the keyboard layout should be respected in any case, even more, on macOS there is an exclusive layout to use QWERTY for Command+key shortcuts and DVORAK for other cases (but it's a special option on macOS):

Actually I have something similar installed for Windows

I feel like the keyboard shortcuts should be the same regardless of keyboard layout because they have little to do with actual typing, and they're chosen based on where they're easy to press

**Comment by LightningAA** [comment]
Here's an example of what I'm talking about
[https://github.com/bradfeehan/Dvorak-QWERTY-Ctrl](https://github.com/bradfeehan/Dvorak-QWERTY-Ctrl)

One solution could be to have a dvorak keyboard shortcuts file for the non ctrl keyboard shortcuts that comes with aseprite (or is in a github repository like the themes are) that you can import in the keyboard shortcuts menu. I guess the biggest issue with this is the tooltips will still be off from the actual physical keys you need to press, but that probably really isn't too big of an issue.

**Comment by Amoo0001** [comment]
Please don't do this!  As someone who has been using Dvorak and other alternative layouts for over a decade, I would like to plead that you use the selected layout (Dvorak or whatever) regardless as to whether or not control is pressed.

Doing it any other way such as how LightningAA suggests is terrible for those of us who actually touch type in our chosen keyboard layout.  It's not fair to those of us who actually use these layouts to change how they work so one person who doesn't have it memorized yet can get visual feedback by looking at their QWERTY keycaps while they hold control.

If I press the B key, that is the one that would have had an "N" written on it had it been a physical QWERTY keyboard that I remapped to Dvorak, then I want it to function as a B no matter whether I have a modifier held or not.  Otherwise, what would happen if I lived in France and pressed Ctrl+A on my AZERTY keyboard that I had remapped to Dvorak?  If you QWERTY-remap all keys while control is held then it would emit Ctrl+Q despite the keycap showing A and it typing A in text.

Also, I own a physical Dvorak keyboard with QWERTY scancodes.  One that has the keys in the Dvorak layout and emits modified scancodes so you can tell programs that don't know about Dvorak that you have QWERTY and it just works as Dvorak.  If you remap my keys again then it will make it so I have to hit X to get the pen tool, despite it both typing X in text and showing X on the keycap!

You said "This is how Godot, Blender, Unity, FL Studio etc. handle different keyboard layouts" but I use half of those regularly at work and have used the rest before and I've never seen another program do this obscure remapping while a modifier key is held, nor should they!  It's possible I already remapped them and forgot, but I don't think I did, so I don't think that statement of yours was tested.  I can test all four of them on a friend's computer with a software Dvorak mapping later if confirmation is needed.

**Comment by LightningAA** [comment]
@Amoo001 I think you misunderstand what I was asking. I wasn't at all saying that aseprite should remap the ctrl shortcuts, that's the os's job. I was originally suggesting that the non-ctrl keyboard shortcuts should be keyboard layout agnostic, as that's what makes sense to me (I'm using a regular keyboard that has the dvorak layout installed in my system settings). Anyways, if you read what I wrote yesterday, I think the easiest solution is just to provide a keyboard shortcut file for those with a dvorak keyboard, which won't require any changes to asprite's code.

**Comment by Amoo0001** [comment]
I very well may have misunderstood.  I found what I thought you said to be very bizarre, so it's likely I misunderstood, in which case I apologize.

But does this mean you want to hit "X" to get the pen and so forth?  If so that doesn't sound intuitive to me at all but I could see some people who already have they Aseprite QWERTY layout memorized using something that until they learn Dvorak properly.  I wouldn't use it and I think it would also be a disservice to those learning a new layout, but if it's an optional feature that is also not the default for Dvorak users but something they choose separately then I wouldn't be against it... unless it took development time away from features that matter to me such as the upcoming tilemap editing features.  Sorry if I misunderstood.

**Comment by LightningAA** [comment]
I'm using [this](https://github.com/bradfeehan/Dvorak-QWERTY-Ctrl) as my keyboard layout on laptop (which just has a built in QWERTY keyboard like every other laptop, I haven't modified it at all). I would like it so when I hit the physical b key on my keyboard, it switches to the pen tool, right now I have to hit the physical n key. I think it should be this way because keyboard shortcuts aren't about typing, they're about the position of they key on the keyboard. For example, with Ctrl + C/V to copy/paste, the c and v keys are right next to each other on the qwerty layout and they're also close to the left hand so you can keep your right hand on your mouse.

**Comment by Amoo0001** [comment]
Oh, so you do want it that way.  How would it know that you have a QWERTY keyboard?  That's not the standard in many places, such as most of Europe, you know.  It's called "US-QWERTY" for a reason.  It's also not good for learning a layout.

I'm not against this being included if it's **not the default for Dvorak** and if **you make it yourself**, even though I think it's not to your benefit anyway.

People who use other keyboard layouts on a regular basis know where their layout's keys are, that's the whole point.  And keyboard shortcuts are very much "about typing".  If I press control+B then I want it to do "control+B", not "control+N" just because this key has an N written on it on **your** keyboard.

**Comment by LightningAA** [comment]
I disagree because keyboard shortcut layouts are optimized for qwerty keyboards, but I can kind of see your point.

**Comment by LightningAA** [comment]
I think I'll close this issue in favor of [this one](2644), which makes it easier to make custom keyboard layouts, unless someone requests to have it reopened.
