### ISSUE TITLE
Running script via cmd crash

### ISSUE THREAD

**Issue by NoelFB** [aseprite/aseprite#2621]
Running any script via command line crashes, *unless* I place the script directly beside my Aseprite.exe in Program Files. I've tried this with empty scripts and it always closes.

For example, if I run `aseprite --script test.lua`, and place `test.lua` inside the scripts directory, Aseprite will crash. However, if I place `test.lua` beside the Aseprite.exe in `C:/Program Files/Aseprite`, it will behave normally.

I tried running with `--verbose` and `--debug` and neither output anything. Aseprite did however create a crash `.dmp`, which opened in Visual Studio said the error was `The thread tried to read from or write to a virtual address for which it does not have the appropriate access`.

EDIT: I realized this is probably intended to always run the script from the execution location, rather than my expectation of running scripts installed in the `scripts` folder. I think maybe an error message of some kind might be useful in this case? Or it could fall back to the `scripts` folder?

### Aseprite and System version

* Aseprite version: v1.2.25, installer
* System: Windows 10 x64

**Comment by Gasparoken** [comment]
Thanks for this report. I can't reproduce the crash (current version 1.2.40).
Just in case: `aseprite --script test.lua` sentence will work at the command prompt only if you meet the following two conditions:
1. Your current path is the same folder as `Aseprite.exe` OR you have added the Aseprite folder (which contains Aseprite.exe) in your PATH environment variable (Do this to add the aseprite path: `set PATH=%PATH%;C:\your folder containing Aseprite.exe`)
2. Your script.lua is placed in the current path.

Otherwise it will fail.

The correct statement is to include the full path of the `exe` and `lua` files:
`"C:\Users\Cust....prite\Aseprite.exe" --script "C:\Users\Custo...ming\Aseprite\scripts\script.lua"`

**Comment by NoelFB** [comment]
Closing this as I just misunderstood the use. I assumed that since Aseprite has a scripts folder it would try to search relative to that path.
