### ISSUE TITLE
Cant turn Complied Aseprite file into a usable .exe from a extensionless file

### ISSUE THREAD

**Issue by toastontoast** [aseprite/aseprite#2693]
When compiling Aseprite using the last step `ninja aseprite` it only leaves a file with no extension, i tried using `./aseprite` in the /build/bin folder and it only returned with `Segmentation fault (core dumped)` and nothing else. Im at a lost here. 

 Aseprite and System  #version

* Aseprite version: v1.1.25, Portable (I think)
* System: Linux Ubuntu 20.04

**Comment by Amoo0001** [comment]
Oh dear, you do realize that .exe extensions are a Windows-only thing, right?  I don't use Linux anymore but it sounds like there may have been a problem with the build process.  I'm not saying this is why it went wrong, but generally when something like that would ever happen to me with software I was building from source, it was usually because I missed a step in the installation guide.

`./aseprite` in the `bin` folder is the correct way to launch Aseprite if you have build it but haven't installed it (yet).  You said you thought it was the portable version, but if it wasn't then once you install it, it should just be `aseprite`.

I haven't had my "morning" coffee yet so this might be gibberish, but I hope I was at least somewhat helpful.

**Comment by toastontoast** [comment]
Ooops total brain shutdown by me. I thought that aseprite when compiled (no matter the operating system) creates the program for all operating systems (.exe for Windows, .dmg for Mac, etc) but if i understand correctly only the operating system you compile it on is what the end product is. Total mistake on my part sorry for being a total noob.
