### ISSUE TITLE
Aseprite does not build

### ISSUE THREAD

**Issue by Magolor44** [aseprite/aseprite#2721]
Describe your bug report or feature request here

It errors out while building because apparently the aseprite binary does not exist even though it is installed.
Same thing happens with the AUR version.

### Aseprite and System version

Aseprite Version: Don't know
OS: Arch Linux

**Comment by dacap** [comment]
Hi @Magolor44, if you are using the steps from the INSTALL.md guide, you can show the compilation errors so maybe someone can help you. About the Arch Linux distribution, we don't support it.

**Comment by Yeyuehuke** [comment]
Because the aseprite-common from [aseprite-common.tar.gz](https://skia.googlesource.com/common.git/+archive/9737551d7a52c3db3262db5856e6bcd62c462b92.tar.gz)  does not exist any more. We should wait a packager pack it again. You can see details in [AUR Page](https://aur.archlinux.org/packages/aseprite/)

**Comment by yonderbread** [comment]
You could try modifying my build script for Ubuntu
https://gist.github.com/yonderbread/b363035fd60fd87857f6d59b4d92c0e3

**Comment by dacap** [comment]
From what I've tested I was able to compile Skia on Linux and macOS yesterday just ignoring the error of the inexistent common repository.
