### ISSUE TITLE
Exporting an indexed image that's using any palette other than the default causes project corruption

### ISSUE THREAD

**Issue by brainard52** [aseprite/aseprite#2728]
Describe your bug report or feature request here
Steps to reproduce:
1. Create a new indexed project. I chose 128x64 with a white background
2. Click the "Presets" button and choose "Game Boy"
3. Save the project
4. Export the project

### Aseprite and System version
* Aseprite version: 1.2.27, Steam
* System: macOS 11.3.1 (20E241) (M1 MacBook Pro)

**Comment by brainard52** [comment]
![Screen Shot 2021-05-17 at 10 50 49 PM](https://user-images.githubusercontent.com/1023838/118599466-68ee6a80-b764-11eb-9c0c-8ca2f39fac6b.png)

**Comment by not-surt** [comment]
Changing the palette doesn't modify the pixel indices, so the index of the white coloured pixels is now out of range for the new palette.
If you just want to be able to save press the "Remap Palette" button below the colour palette to correct the pixel indices before saving to PNG.

It'd probably be more user friendly if it gave a warning about out of range indices before saving, rather than an error after.

**Comment by brainard52** [comment]
I think an option that’s even more user-friendly would be to warn that it will flatten the colors when a smaller palette is selected and request confirmation.

**Comment by Gasparoken** [comment]
Good news, this was solved by https://github.com/aseprite/aseprite/pull/2934 on Aseprite v1.2.30
