### ISSUE TITLE
Tooltips clipped by window/popup edges

### ISSUE THREAD

**Issue by not-surt** [aseprite/aseprite#2764]
Tooltips are clipped by the edges of the parent window or popup.

![aseprite_tooltip_clipped](https://user-images.githubusercontent.com/1218087/121757934-ad520800-cb62-11eb-9415-ce4a54155baf.png)

### Aseprite and System version

* Aseprite version: v1.3 beta4
* System: Windows 10 Pro 10.0.18363 Build 18363

**Comment by dacap** [comment]
Thanks @not-surt, it's a known issue but it's nice to have the record about it here in Github.

We didn't fix it yet because some cross-platform native work must be done to create a little window for each tooltip yet (e.g. windows with transparency), but might be easier to fix than what we thought. We'll see.

Other possibility would be to convert tooltips into a native look (e.g. like native Windows tooltips), but I'm not sure about that one.

**Comment by dacap** [comment]
This will be fixed for v1.3-beta6
