### ISSUE TITLE
Not playing well with cmark 0.30

### ISSUE THREAD

**Issue by GAZ082** [aseprite/aseprite#2808]
`aseprite: error while loading shared libraries: libcmark.so.0.29.0: cannot open shared object file: No such file or directory
`
Had to downgrade to 0.29. Looks like a fine maming issue?

Archlinux.

**Comment by mohad12211** [comment]
you can compile aseprite to use its own cmark. just omit this flag when compiling ` -DUSE_SHARED_CMARK=ON `.
I think you can solve it by symlinking or something, like symlinking a file called `libcmark.so.0.29.0` with `libcmark.so.0.30.0` or something like that, you need to look it up first

**Comment by GAZ082** [comment]
@mohad12211 thanks buddy. Renamed the file and worked. I also noted there is a symlink to the latest lib version, libcmark.so. Wonder why its not being used by Aseprite instead of a particular version file.

Im just using the pre-compiled binary, Id be asking to the maintainer of the package or keep  this issue open?

**Comment by mohad12211** [comment]
This happened again, I compiled aseprite with cmark version `libcmark.so.0.30.0` and now there's a new version `libcmark.so.0.30.1`. there's a symlink to the latest version called `libcmark.so`, is there a way to use that symlink instead of a certain version? I either need to recompile aseprite with the latest version, or include libcmark by static linking

**Comment by dacap** [comment]
I think we're going to remove some USE_SHARED_CMARK flags in the near future to avoid this situations. Linux distros are not making this easier and we prefer to compile everything statically anyway.
