### ISSUE TITLE
i kinda confused ,, why the software is paid but heere available source code 

### ISSUE THREAD

**Issue by muafakul** [aseprite/aseprite#2833]
Describe your bug report or feature request here
...
...
...actualy i need the free version or something like that cause i still beginner and trash dumby poor

### Aseprite and System version

* Aseprite version: version number, installer/portable/Steam/beta/dev/commit-hash
* System: Windows/macOS/Linux, version, distribution

**Comment by mohad12211** [comment]
you can download the free trail version from [here](https://www.aseprite.org/trial/), however, you can not save your work, that's why it's just a trail version, you can buy the full version, or you can compile the source code yourself and use aseprite for your personal use, you can even use it for your commercial game, however you can't distribute the compiled binary with others. to compile aseprite follow the instructions [here](https://github.com/aseprite/aseprite/blob/main/INSTALL.md), for more information read the FAQ section [here](https://www.aseprite.org/faq/)

**Comment by muafakul** [comment]
use aseprite for your personal use, you can even use it for your commercial game


i kinda confused about personal and commercial 👍

**Comment by muafakul** [comment]
**just to make sure that i can save my work in this compile version right ?**

**Comment by dacap** [comment]
Hi @muafakul, you will be able to save files with the compiled version. It's an option for people that want to contribute code to Aseprite or that cannot afford the official pre-compiled version price.

Probably in the future, if you find Aseprite useful and can afford it, you can contribute with your purchase even after compiling it.

**Comment by muafakul** [comment]
and i can export to sprite sheet right ?

**Comment by mohad12211** [comment]
with the compiled version, yes you can @muafakul

**Comment by muafakul** [comment]
thanks ,and now i just found tutorial bout install without compiling, only download the exe .,,thank to myself

**Comment by dacap** [comment]
@muafakul that's against the EULA
