### ISSUE TITLE
UI Manager deleted before ui::Manager::getDefault()->theme() call

### ISSUE THREAD

**Issue by martincapello** [aseprite/aseprite#2981]
UI manager is already deleted before ui::Manager::getDefault()->theme() call.

![image](https://user-images.githubusercontent.com/5520828/135849700-269a24da-e908-4c37-af4b-3b6d0dcdf5f8.png)

![image](https://user-images.githubusercontent.com/5520828/135850046-207e49fd-caba-4a1a-b7a1-41c7b33af7b7.png)

### Aseprite and System version

* Aseprite version: 1.2.29
* System: Windows 10.0.19041

https://igarastudio.zendesk.com/agent/tickets/2756

**Comment by dacap** [comment]
This was already fixed with https://github.com/aseprite/aseprite/commit/2d3de1728c5c454d786b1ca05af0248d9abbf1f4 in [v1.3-beta12](https://github.com/aseprite/aseprite/releases/tag/v1.3-beta12) and [v1.2.34](https://github.com/aseprite/aseprite/releases/tag/v1.2.34)

Still reported in v1.3-beta11 which didn't include the fix: https://sentry.io/organizations/igara-studio/issues/3314057820/events/c4692c432c9245208f4910544638d721/
