### ISSUE TITLE
Dialog.bounds gets reset if the dialog is closed (cannot pass it to a second dialog)

### ISSUE THREAD

**Issue by IgnacioLuxP** [aseprite/aseprite#3018]
A common practice when writing the UI for a script with multiple tabs is to pass the bounds of the first dialog (dlgA) to a new dialog (dlgB) in order to move it to the dlgA's position. This does not work as expected in 1.3-beta6. The (x, y) for **dlgB**.bounds is reset to (0, 0), moving the second tab to the top left corner of the app's window. 

To reproduce, use the [Wizard Example script ](https://raw.githubusercontent.com/aseprite/Aseprite-Script-Examples/master/Wizard%20Example.lua) from the sample scripts. It occurs with any script that uses the same approach. 

**(edit) IMPORTANT:** This only seems to occur with the "UI with multiple windows" option enabled (in `Edit > Preferences > Experimental > UI with multiple Windows`)

The workaround seems to be to cache the previous dialog's bounds and pass this copy to the new dialog. The second time the dialogs are loaded, their bounds will retain their new position, but it's not the one received from the first one.

Please see the attached gifs.

### Aseprite and System version

* Aseprite version: 1.3-beta6 dev
* System: Windows 10 64bit English

### Attachments
No script, just try it out with `Wizard Example.lua`

#### 1.3-beta 6
![wizard dialog 1 3-beta6](https://user-images.githubusercontent.com/88293704/138302683-fb777dec-2ebf-4bae-a594-016d1f2d486b.gif)

#### 1.2.29
![wizard dialog 1 2 29](https://user-images.githubusercontent.com/88293704/138302718-3027b8e2-6017-4e8c-a477-9cfe8bbf9762.gif)

**Comment by iamOgunyinka** [comment]
Getting the source of this bug took quite a while but I think I know what is going on now (not a fix, more like a report on the _research_). (Please skip to the next paragraph if you're not interested in the technicalities, this is only detailed here for future reference) The problem here is that when you _activate_ the experimental "UI with multiple Window" in Preference, Aseprite uses a conceptual [Display](https://github.com/aseprite/aseprite/blob/beta/src/ui/display.h) that uses a different kind of bounds, different from the traditional bounds when that option isn't checked. When you read the bounds of a dialog, with that option checked, Aseprite uses a [different methodology](https://github.com/aseprite/aseprite/blob/04fb75a330920737fb11cadd0b3ff888a45e841c/src/app/script/dialog_class.cpp#L139-L149) to return the bounds. However, when you close the Window, the [flag](https://github.com/aseprite/aseprite/blob/04fb75a330920737fb11cadd0b3ff888a45e841c/src/ui/window.h#L107) Aseprite uses to track this `Display` is already [reset](https://github.com/aseprite/aseprite/blob/04fb75a330920737fb11cadd0b3ff888a45e841c/src/ui/manager.cpp#L1495) and thus, this methodology fails. 

The only hack I can come up with now is to cache the bounds before closing the window, like so:
```
local function prevPage(dlg)
  local bounds = dlg.bounds
  dlg:close()
  for i = 2,#dlgs do
    if dlg == dlgs[i] then
      local newDlg = dlgs[i-1]
      newDlg.bounds = Rectangle(bounds.x, bounds.y,
                                newDlg.bounds.width, newDlg.bounds.height)
      newDlg:show{ wait=false }
      return
    end
  end
end
```

Can this bug be fixed in a more elegant way? Perhaps but I would leave what to do in scenarios to someone smarter.
