### ISSUE TITLE
Colour Picker Indicators Vanish When Switching From Tileset-Active Document Workspaces to Non-Tileset Workspaces.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#3082]
When the Tile Picker is active (document has tiles; tile-placement mode is active; the Tile Picker has focus versus the Colour Picker), the Tile Picker indicators (the small triangles in the top-left/bottom-right corners of Colour Picker and Tile Picker swatches) do not reappear in the Colour Picker when tabbing to a document Workspace *without* tiles. The indicators do not reappear when new Colours are selected by any means (Eyedropper, direct selection from the Colour Picker, hotkey, mousewheel).

The problem seems to be that the ASEprite UI has the 'Picker indicators "locked" to Tile Map/Placement mode, and when the software switches to a Workspace with no tiles, the indicators fail to return to the Colour Picker and vanish with the Tile Picker when it is hidden. All drawing tools continue to work normally, but there is no indication in the Colour Picker as to which Foreground and Background colours are currently active.

Switching to any Workspace with a Tilemap-enabled document causes the Tile Picker to reappear as normal, complete with indicators. Selecting a colour from the Colour Picker (which returns focus to that selector), then tabbing back to the document Workspace without tiles solves the problem (the indicators are once again visible in the Colour Picker).

This recording may be clearer. 🔽 
![tile picker colour picker focus bug](https://user-images.githubusercontent.com/11544843/144321246-02be3867-3146-411a-a348-3945fd5ca603.gif)

Thanks for looking into it! :D 

..using ASEprite v1.3-b6 on Win10.

**Comment by iamOgunyinka** [comment]
@Gasparoken I may have found the source of this bug, I'll explain below and link a patch that works (please review and see if the implementation is worth using as a PR).

IIRC there's only one color bar for all opened documents. When we change views, we update the color bar with the palette and tiles of the site/document. Whenever we pick a tile from the tile set in the color bar, we [change the tilemap mode](https://github.com/aseprite/aseprite/blob/ff851157ccaadd66ef648c0f69bcddb7d2f62d02/src/app/ui/color_bar.cpp#L784) and this persists until we select color/pixels from the palette view. However, right now, the tilemap mode persists regardless of the view we are in and thus when we are in a document that has a pixel tilemap mode, the color picker "indicator" would not be drawn because the check to know if the [`paletteView` is Active](https://github.com/aseprite/aseprite/blob/ff851157ccaadd66ef648c0f69bcddb7d2f62d02/src/app/ui/palette_view.cpp#L845) returns `false`. 

We need a way to know what the active tilemap is and correct set it when we switch between documents/views. This tilemap mode could be saved per document and thus restored in a color bar when a view is active. Please take a look at this [implementation](https://github.com/iamOgunyinka/aseprite/commit/04b3e45de043676d9a2a9a83f88263b944ae381e) to see what I mean and if there are better ways of solving this bug.

**Comment by Gasparoken** [comment]
Thank you very much @iamOgunyinka! I'll take a look today.

**Comment by dacap** [comment]
Hi there @iamOgunyinka, one possible solution might be changing `ColorBar::onIsPaletteViewActive()` to ask for `canEditTiles()` if it's in tiles mode (`m_tilemapMode == TilemapMode::Tiles`). So the palette view is active if we cannot edit tiles (i.e. we are not in a tilemap layer).
