### ISSUE TITLE
[scripting] Selection:select replaces selection

### ISSUE THREAD

**Issue by not-surt** [aseprite/aseprite#3093]
In the scripting API Selection:select replaces the selected pixels rather than adds too them.
From the documentation (https://github.com/aseprite/api/blob/main/api/selection.md#selectionselect) it is described as "Selects the given rectangle" which sounds to me like it should mark the pixels in the rectangle as selected, so adding them to the selection, not replace the selected pixels.
If it's meant to be the latter then it is redundant with the Selection constructor taking a rectangle and doesn't allow any selection of more complex shape than a single rectangle. (I am aware I can use app.useTool with the selection tools, but that's rather heavy-weight for my purpose of building a selection per-pixel.)

Example script:
```
local selection = Selection()
selection:select(Rectangle(10, 10, 20, 20))
selection:select(Rectangle(40, 40, 20, 20))
app.activeSprite.selection = selection
```

### Aseprite and System version

* Aseprite version: v1.3-beta7-x64, Steam
* System: Windows 10 Pro, Version 10.0.19043 Build 19043

**Comment by dacap** [comment]
Hi @not-surt, thanks for reporting this. Actually the expected behavior of `:select()` is to replace the whole selection, you can use `:add()` method to add (there is `:subtract()` and `:intersect()` too).

The main issue I guess is that those are undocumented methods. I'll add this information in https://github.com/aseprite/api/blob/main/api/selection.md ASAP
