### ISSUE TITLE
Please Help! Marquee Tool becomes invisible in the greyscale mode

### ISSUE THREAD

**Issue by terbasthegood** [aseprite/aseprite#3274]
Describe your bug report or feature request here
I use greyscale mode a lot. But I realized that the marquee tool becomes invisible (during the selection phase) in that mode. If I switch to RGB color mode, it becomes visible.

**Comment by Gasparoken** [comment]
Hi @terbasthegood. I cannot reproduce it. What's your Aseprite version and OS?

**Comment by behreajj** [comment]
I was able to reproduce this. I suggested [terbasthegood](https://github.com/terbasthegood) post the issue here rather than on the [Steam forums](https://steamcommunity.com/app/431730/discussions/0/3275815186864662887/). I'm using Windows 10. This happens in both versions 1.2.34-x64 and 1.3-beta14-x64.

I'd post a screen shot, but there's not much to see. Instead, here are some reproduction steps:
1. Press `M` (or equivalent hotkey) to switch to marquee tool.
2. Move mouse cursor over sprite canvas.
3. Press down mouse button.
4. Drag mouse.
5. Expected behavior is for a white outline to preview selection.
6. Release mouse button.
7. White preview outline is replaced with marching ants.

In grayscale mode, step 5, the white preview outline, doesn't appear.

The white preview may be skinnier and harder to see on larger canvases. I tried this on a small canvas, the same size for different color modes, so that is not the issue.

In the meantime, I suppose one could copy and paste a 256-length gray palette and/or use the `Gray` section of the color picker while in RGB color mode, then convert to grayscale before saving/export.

Thanks,
Jeremy

**Comment by terbasthegood** [comment]
Thanks behreajj, I'm happy that you reproduced the issue. Since there definitely is a problem. No white preview visible. I hope the devs will do something about it soon.

**Comment by Gasparoken** [comment]
Thanks @behreajj and @terbasthegood. I was able to reproduce it, but only in Windows 11 and Aseprite 1.3beta14.
I cannot reproduce it in Windows 11 and Aseprite 1.2.34.1 (@behreajj could you confirm?).
Both Aseprite versions on MacOS are fine.

**Comment by behreajj** [comment]
Today I only see it in 1.3 beta on Windows 10. Thought I checked, but could be I didn't switch over like I thought I did. I'll mention it if I encounter it again.
