### ISSUE TITLE
Closing the Undo History pane takes several minutes for long histories.

### ISSUE THREAD

**Issue by oceanhahn** [aseprite/aseprite#3281]
Closing the pane for Workspaces with dozens or hundreds of undo states normally takes a few seconds, but as the length of the undo history grows into thousands, the time it takes to close the Undo History pane can drag on well beyond sixty seconds and even into **multiple minutes (!) for undo stacks with several thousand history states.**
During this time, ASEprite becomes unresponsive and Windows treats the software as unresponsive and as potentially having crashed. 

Whatever ASEprite is doing also _occasionally **does** causes the software to crash to Desktop,_ although this has only happened to me twice over dozens of invocations (both times after having scrolled the histories instead of immediately picking "Initial State" (mercifully, it opens the pane to the top of the history and not the bottom) and closing the pane).

From my experience, the wait increases linearly with the number of Undo states on the list: a Workspace with about 270 states took ~4.5 seconds to close the Undo History pane, while one with ~3500 states took a little less than two minutes. The longest I have had to wait in v1.3-b11-x64 has been **over six minutes, waiting for a list of nearly 10,300 events to close**.

It may be worth pointing out that the pane opens practically instantly when it is called and the time it takes closing is uneffected by how I interact with it (moving the window or choosing new history points to undo/redo to) while it is open, or whether it is interacted with at all. The only thing affecting the time it takes is the number of undo states present. The wait time seems to be consistent regardless of the number of other Workspaces/Documents I have open at a time as well.

This bug is super-irritating, and thanks for taking a look at it! :D 

..using ASEprite v1.3-beta11-x64 on Win10.

**Comment by oceanhahn** [comment]
Incidentally, if you can sort out what is causing this, could you let me know what it was?
I am seriously wracking my brains here trying to imagine why _closing a window_ should be so slow. 😅 

Thanks again! :D

**Comment by Gasparoken** [comment]
Thanks @oceanhahn for this report. I was able to reproduce it. In a time profiling, I saw an intensive use of Widget::removeChild() function, which require the execution of _platform_memmove$VARIANT$Haswell. from lib system_platform.dylib
<img width="760" alt="Screen Shot 2022-05-12 at 11 58 29" src="https://user-images.githubusercontent.com/32165475/168109005-610c99c3-a5af-40c5-94ad-6cd9851b0a63.png">
Perhaps, we should change the way all ListItemWidgets populate a ListBox, since only a few ListItemWidgets need to be rendered in the UndoHistoryWindow.

**Comment by oceanhahn** [comment]
Thank you for looking into it! 
Out of curiosity, how many steps was the file for it to take 9.42sec?

And since I am asking, what is the significance of the time-13 tag? I see the time-x tags a lot and it every time my curiosity is piqued. ^^

Thanks again; looking forward to whatever you can do to speed this up a bit! <3

**Comment by Gasparoken** [comment]
I'm just run a simple lua script to generate 300000 app.useTool commands:
```
for i=0,300000,1 do
	app.useTool{ tool="pencil", points={Point(0,0), Point(999, 0), Point(999, 999), Point(0, 999), Point(0,0)} }
end
print("Done")
```
Ha! _time-x_ are new labels for internal use. These are related to the complexity of a possible solution, and therefore, with the time that it can consume.

**Comment by dacap** [comment]
The backtrace is quite confusing because it's jumping from the `UndoHistoryWindow::detachDocument()` to the `OptionsWindow::ExtensionItem` dtor (?)

Anyway it's highly probable that the bottleneck [is here](https://github.com/aseprite/aseprite/blob/e823ee37e9ac86d606e0060784c57e6e9e654e09/src/app/commands/cmd_undo_history.cpp#L197). Deleting items from the beginning of the list instead of deleting items from the back to the front (that alone should improve the performance avoiding the memmove).

> Perhaps, we should change the way all ListItemWidgets populate a ListBox, since only a few ListItemWidgets need to be rendered in the UndoHistoryWindow.

`ListItemWidgets` doesn't exist, but I'm pretty sure that you are talking about the list of `ListItem` inside a `ListBox` (a `WidgetsList`, the `Widget::m_children`). In this case the only way to avoid populating a full `ListBox` would require a filling it dynamically + creating a pseudo-size hint from `onSizeHint()` and keeping items on-sync with the scroll. *I don't recommend to do this* because it will add a lot of complexity to the ListBox while in this case we can (should) solve it creating a customized widget if it's needed (we generally don't create custom widgets until it's required). E.g. a custom widget could paint `undo::UndoState`s directly from `DocUndo`, without creating items/etc. A similar case is the `app::FileList` widget.

**Comment by oceanhahn** [comment]
Huh. Looks like it might also hit the Preferences pane as well? Not nearly as severely but noticeably, to the tune of two or three seconds to close? It also seems to have the same Listbox in it, albeit with only a dozen or so entries.
Might be worth looking at as well if the whole thing is being refactored?

Anyway now you know! ^^;
Thanks again~

**Comment by oceanhahn** [comment]
I am getting lag closing the Keyboard Shortcuts window (which also uses ListBoxes) now, too. Normally, the pane closes fairly quickly, but now it takes a few seconds.

Is it possible that there is some kind of memory congestion delay here or what? o.o

> Ha! time-x are new labels for internal use. These are related to the complexity of a possible solution, and therefore, with the time that it can consume. 

I also just now noticed that the time-# labels follow the Fibonacci sequence, and that is petty neat! :y

**Comment by dacap** [comment]
I've already found several bottlenecks in the UI code to handle these cases (tomorrow I'll write down the details). Anyway I will rewrite the UndoHIstory window with a custom widget so there is no need to create/destroy ListItems for each Undo state,

**Comment by oceanhahn** [comment]
I thank you and everyone who uses the Undo History pane on the regular thanks you. <3
I am also glad to see that it turned out to be a much less sophisticated issue than initially expected!

Now just gotta hang in there until the next release~ ;)

**Comment by oceanhahn** [comment]
...this is kind of a longshot but does this problem also hit the filename input ComboBox in the Save As.. pane?
Sometimes I enter a few characters of a new file name and ASE populates a pulldown list of files with similar names, but if the list is long and I type more characters, pruning the newly-irrelevant filenames lags the window out.

It seems like a longshot that it would be the same problem as all of these other sometimes-severe lag issues, but the circumstances are all very similar and it might be worth checking? 

![image](https://user-images.githubusercontent.com/11544843/169454172-a132c211-6510-4856-b664-85f3148c2208.png)
In this case, I have a number of files beginning "ex" in the low three digits, but every time I type a character, it has to rebuild the list (I am guessing) and it holds up the process by four to six seconds _per character_ until I get through to the third or fourth.

In any case, possible related..?
Thanks for looking (farther) into it! :D

**Comment by dacap** [comment]
Thanks @oceanhahn for your help with this issue. I'll take a look to the filename combobox, it's highly probable that it's the same problem.

**Comment by dacap** [comment]
Details of the bottlenecks:

* Deleting items from *front to back* instead of *back to front* (this generates a lot of `memmove()` to update the items in the `std::vector` when we erase each item in the front):

```diff
--- a/src/app/commands/cmd_undo_history.cpp
+++ b/src/app/commands/cmd_undo_history.cpp
@@ -194,7 +194,7 @@ private:

   void clearList() {
     ui::Widget* child;
-    while ((child = actions()->firstChild()))
+    while ((child = actions()->lastChild()))
       delete child;

     actions()->layout();
```

* About the File > Open > File name combobox, it's a similar issue (we have to delete items in reverse order):

```diff
--- a/src/ui/combobox.cpp
+++ b/src/ui/combobox.cpp
@@ -202,8 +202,12 @@ void ComboBox::deleteItem(int itemIndex)

 void ComboBox::deleteAllItems()
 {
-  for (Widget* item : m_items)
-    delete item;                // widget
+  // Delete all items from back to the front, in this way
+  // Widget::removeChild() doesn't have to use linear search to update
+  // m_parentIndex (or std::find() in previous versions).
+  auto end = m_items.rend();
+  for (auto it=m_items.rbegin(); it != end; ++it)
+    delete *it;                // widget

   m_items.clear();
   m_selected = -1;
```

* Other problem is when we delete/add widgets, there is a global container used to update all widgets when the theme is changed (this collection was a `std::list`, which is the slowest container in C++ to be used for linear searches, in `removeWidget()` you can see `std::find()`, that was a problem):

```diff
--- a/src/ui/intern.cpp
+++ b/src/ui/intern.cpp
@@ -15,32 +15,31 @@
 #include "ui/widget.h"
 #include "ui/window.h"

-#include <list>
+#include <memory>
+#include <set>

 namespace ui {
 namespace details {

-static std::list<Widget*>* widgets;
+static std::unique_ptr<std::set<Widget*>> widgets;

 void initWidgets()
 {
   assert_ui_thread();
-
-  widgets = new std::list<Widget*>;
+  widgets = std::make_unique<std::set<Widget*>>();
 }

 void exitWidgets()
 {
   assert_ui_thread();
-
-  delete widgets;
+  widgets.reset();
 }

 void addWidget(Widget* widget)
 {
   assert_ui_thread();

-  widgets->push_back(widget);
+  widgets->insert(widget);
 }

 void removeWidget(Widget* widget)
@@ -49,11 +48,12 @@ void removeWidget(Widget* widget)

   ASSERT(!Manager::widgetAssociatedToManager(widget));

-  auto it = std::find(widgets->begin(), widgets->end(), widget);
-  if (it != widgets->end())
-    widgets->erase(it);
+  widgets->erase(widget);
 }

+// TODO we should be able to re-initialize all widgets without using
+//      this global "widgets" set, so we don't have to keep track of
+//      all widgets globally
 void reinitThemeForAllWidgets()
 {
   assert_ui_thread();
```

* Bottleneck calculating the text size for each `ListItem` multiple times. This kind of cache was tried in the past in the `Widget` (I don't remember why I didn't keep it), at the moment the cached text length will be used only in `ListItem`:

```diff
--- a/src/ui/listitem.cpp
+++ b/src/ui/listitem.cpp
@@ -60,8 +60,16 @@ void ListItem::onSizeHint(SizeHintEvent& ev)
   int w = 0, h = 0;
   Size maxSize;

-  if (hasText())
-    maxSize = textSize();
+  if (hasText()) {
+    if (m_textLength >= 0) {
+      maxSize.w = m_textLength;
+      maxSize.h = textHeight();
+    }
+    else {
+      maxSize = textSize();
+      m_textLength = maxSize.w;
+    }
+  }
   else
     maxSize.w = maxSize.h = 0;

@@ -78,4 +86,10 @@ void ListItem::onSizeHint(SizeHintEvent& ev)
   ev.setSizeHint(Size(w, h));
 }

+void ListItem::onSetText()
+{
+  Widget::onSetText();
+  m_textLength = -1;
+}
+
 } // namespace ui
--- a/src/ui/listitem.h
+++ b/src/ui/listitem.h
@@ -26,9 +27,11 @@ namespace ui {
     bool onProcessMessage(Message* msg) override;
     void onResize(ResizeEvent& ev) override;
     void onSizeHint(SizeHintEvent& ev) override;
+    void onSetText() override;

   private:
     std::string m_value;
+    int m_textLength = -1;
   };

 } // namespace ui
```

* The most complex change was to remove the linear search (`std::find`) used in this method:

```diff
--- a/src/ui/widget.cpp
+++ b/src/ui/widget.cpp
 void Widget::removeChild(Widget* child)
 {
   ASSERT_VALID_WIDGET(this);
   ASSERT_VALID_WIDGET(child);
-
-  WidgetsList::iterator it = std::find(m_children.begin(), m_children.end(), child);
-  removeChild(it);
+  ASSERT(child->parent() == this);
+  if (child->parent() == this)
+    removeChild(m_children.begin() + child->m_parentIndex);
 }
```

The whole patch is too big to share here, but the basic solution is storing a `m_parentIndex` which is the index where the child widget is located in its parent (`m_parent`).

Anyway the undo history has other big issue which is that it re-generates all undo states for each change (or when we change documents). I'll rewrite it using a custom widget because the amount of additions/deletions of items is insane.

**Comment by oceanhahn** [comment]
Adding results per your request on Discord, @dacap: 
Tested this yesterday with a considerable undo history queue and the pane closed immediately. The delay issues closing the Preferences Pane and list updates in the Save As.. and Open filename ComboBoxes have similarly been eliminated.

Thanks again for getting this done so quickly; it really makes my life a lot easier, if not longer! ❤️

**Comment by dacap** [comment]
It's great to hear that @oceanhahn <3 thanks for reporting and testing the issue.
