### ISSUE TITLE
en.ini question

### ISSUE THREAD

**Issue by ghost** [aseprite/aseprite#3288]
Hi

While working on my Dutch translation, I have something I don't understand.

In en.ini:

auto_show_selection_edges = Automatically show selection edges after modifying the selection

auto_show_selection_edges_tooltip = <<<END
Uncheck this if you want to keep the
selection edges option as you wish.
END

Doesn't it have to be "CHECK this if you want to keep the selection edges option as you wish." ?

**Comment by dacap** [comment]
Hi @pixelartgirl! It looks like the message was introduced in dd82f6bbcc63d5f44d3a0de5ddb700562a6f5b47, I have to admit that both messages are a little confusing, maybe @Gasparoken would like to take this one.

**Comment by pixelartgirl** [comment]
Thx. I wait until it's clear for me, because I can't translate it this way.

**Comment by Gasparoken** [comment]
Thanks @pixelartgirl for mentioning this. "Uncheck this if you want to keep the selection edges option as you wish." is right, but I agree that it can be confusing.

My intention in dd82f6bbcc63d5f44d3a0de5ddb700562a6f5b47 was:
auto_show_selection_edges UNCHECKED = the selection edges will be showed/hidden according to the flag _View > Show > Selection Edges_ "as you wish" (i.e.: without automatic behavior).

All the next sentences are valid:
1. "Check this if you want automatically re-show Selection Edges after selection modifications."
2. "Check this option to automatically force 'Checked' the option View > Show > Selection Edges after selection modifications."
3. "Uncheck this if you want the show/hide state of Selection Edges respond strictly to View > Show > Selection Edges option."

I'll choose 2 because 1 is almost the same description as the option itself, and 3 is the the tip for the negative case (unchecked case).

**Comment by Gasparoken** [comment]
I'll leave the purpose of 'auto_show_selection_edges' here:
Hiding Selection Edges is convenient when you make a very complicated selection with several corners and individual pixels (this happens when using the Magic Wand Tool on a high resolution image and many colors), this action can slow down the editor. Therefore, hiding the selection edges can be useful in these cases to speed up the editor. Often hiding the Selection Edge is for once, then we prefer to keep showing the selection edges. That's why 'auto_show_selection_edges' can help the artist.

**Comment by dacap** [comment]
@pixelartgirl we still have to reword those paragraph, I'd recommend you to keep the English version as it's in your file and translate it in the future.

I would change the text to this but it still must be confirmed by @Gasparoken:
```
auto_show_selection_edges = Show selection edges automatically when it's modified
auto_show_selection_edges_tooltip = <<<END
When checked, the View > Show > Selection Edges option will be enabled
each time we modify the selection. Uncheck this in case that you want
to hide the selection edges completely later, e.g. to avoid visual
noise or performance issues.
END
```

For more information about this option we can write it down in the [Preferences section](https://www.aseprite.org/docs/preferences/) in the docs (the *Selection* section is still pending to be written).

**Comment by Gasparoken** [comment]
`auto_show_selection_edges = Show selection edges automatically when it's modified`
This Ok for me.

About the tool tip, I agree with the checked part. The uncheck part, the "completely later" phrase confuses me. I understand better the next tip:
```
auto_show_selection_edges_tooltip = <<<END
When checked, the View > Show > Selection Edges option will be enabled
each time we modify the selection. Uncheck this in case that you want
to keep selection edges hidden when View > Show > Selection Edges
option is disabled, e.g. to avoid visual noise or performance issues.
END
```

And for https://www.aseprite.org/docs/preferences/ I'll complete some documentation, no problem.

Can I proceed @dacap?

**Comment by pixelart-girl** [comment]
Does this mean the en.ini on github now has the new string?

Sorry I deleted my account yesterday because making a script was too much. I have autism...

PixelArtGirl

**Comment by Gasparoken** [comment]
> Does this mean the en.ini on github now has the new string?
Yes, you can go ahead and stay strong!
Thank you @pixelart-girl!
