### ISSUE TITLE
Can this be compiled with VSCode?

### ISSUE THREAD

**Issue by 3prm3** [aseprite/aseprite#3329]

**Comment by martincapello** [comment]
Hey there. I will try to clarify a bit: as far as I know, VSCode is just a text editor (very powerful indeed because of the use of extensions), it is not a compiler. 
Maybe you were asking if you can use it to develop in the same way one can use Visual Studio 2022 (or earlier versions). In this case, Visual Studio is an IDE (Integrated Development Environment), so the compiler tools are tightly integrated (and are shipped) with the text editor.
You might try to search some extension for VSCode that could allow you to program in C++ and use a previously installed compiler, but I'm not aware of such extension. 

Hope it helps.
