### ISSUE TITLE
Can't dock to the main tab

### ISSUE THREAD

**Issue by KasumiArai** [aseprite/aseprite#3453]
![can't dock aseprite](https://user-images.githubusercontent.com/8582123/182541477-9190d0ec-9151-42ea-b2b8-97d7534e4029.gif)
Tabs can no longer be dragged to the area where the tab bar is by default.

Aseprite v1.3-beta-19-x64, Steam, Windows 10.

**Comment by Gasparoken** [comment]
Thanks for this report @KasumiArai. I cannot reproduce this bug (Windows and MacOS, Aseprite 1.3-beta19).

Just in case, could you share your preferences file with us? (Aseprite preferences are stored in a 'aseprite.ini' file in the [configuration folder](https://www.aseprite.org/docs/preferences-folder/). You can access this folder from _Edit > Preferences > Locate Configuration File_).

**Comment by dacap** [comment]
Hi @KasumiArai, I'm trying to reproduce it. Try hidding the Preview. I was able to reproduce it (probably if the Screen Scaling is changed, or probably only if the Preview window is visible)

**Comment by dacap** [comment]
Even more, just pressing F7 to switch the preview window while we have a tab dragged, will enable/disable the docking.

**Comment by dacap** [comment]
Some final notes:

1. The behavior is quite random (more reproducible with Screen Scaling=100%, and can happen in several sides of the dockable areas, for example: we cannot dock at the top but the sides work, etc.)
2. The visibility of the Preview window helps to reproduce it
3. It's a bug present since the first v1.3-beta1 (this was important for me to know, because I already have the v1.3-beta20 packages compiled and didn't want to introduce a possible regression fixing this :sweat_smile: )

**Comment by KasumiArai** [comment]
Here's the preferences file if that is still helpful:
[aseprite.zip](https://github.com/aseprite/aseprite/files/9255449/aseprite.zip)
Yes, screen scaling at 100%, yes, preview window generally. I'll see if toggling restores it for me when it starts
