### ISSUE TITLE
`bmp_file_header` fields are incorrectly set on bmp export

### ISSUE THREAD

**Issue by Arecher** [aseprite/aseprite#3534]
### Aseprite and System version

* Aseprite 1.3-beta21-x64
* Windows 10

Thought I would make this a separate bug report. Contributors at the Godot Engine project have looked into the bmp files not properly importing, and found that something about the bmps is in fact incorrecly set.

>The fields bmp_file_header.bmp_file_size and bmp_info_header.bmp_size_image are incorrectly set

Here is the specific post, seems like something that might need investigating further:
https://github.com/godotengine/godot/issues/66238#issuecomment-1256442592

**Comment by Gasparoken** [comment]
Thanks again. I'll review it ASAP.

**Comment by Gasparoken** [comment]
I did a patch for this and saved `test.bmp`. Could you testing this example in your Godot engine?
[test.bmp.zip](https://github.com/aseprite/aseprite/files/9637027/test.bmp.zip)

The bad calculation of bmp image size (`biSizeImage`) is done here:
https://github.com/aseprite/aseprite/blob/ae889d4ae3aa6897dae905a4ff3738484e874417/src/app/file/bmp_format.cpp#L1215-L1217
`biSizeImage` was calculated based on the old 24 bits (3 bytes). But now, if the BMP is inferred to have alpha content, the file will be 32 bpp (4 bytes per pixel). I forgot to change it at https://github.com/aseprite/aseprite/commit/bdcabdedf3e5f575a5b7a3532f119ec1a08d75aa

It'll be fixed in the next release.

**Comment by Arecher** [comment]
Yes, that test .bmp imports correctly into Godot!

**Comment by Gasparoken** [comment]
Thank you for your feedback! Perhaps the new feature in https://github.com/aseprite/aseprite/issues/3532 is no longer needed. We'll review it next week.

**Comment by Arecher** [comment]
This fix would resolve all my problems, so the new feature wouldn't be required anymore for my specific use-case. Unless there are other apps that don't handle specific bmp files well, I think it could be closed. (After all, it can always be reopened if other users run into these apps!)

And thank you for all the effort you put in! ❤️
