### ISSUE TITLE
Trial save bug

### ISSUE THREAD

**Issue by mar123beheima** [aseprite/aseprite#3544]
If you select the sprite with ctrl + a or ctrl + t and copy it with ctrl + c it will copy it to your clipboard

### Aseprite and System version

* Aseprite version: Any asperite version
* System: Windows

**Comment by martincapello** [comment]
Hey there 👋 thank you for taking the time to file an issue! However, this is actually expected behavior 😅 
The only thing the trial version must not allow to do is to save the work you made. You can copy your sprite and paste it in another program, but in doing so you lost all the features that the Aseprite's format offers such as layers, frames, palette, etc.
