### ISSUE TITLE
Theme regressions

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#3709]
Some problems with the recent changes in Screen Scaling=100% and UI Scaling=200% (not high priority as it's not the default configuration):

* The layer name is not in the middle of the row:

![image](https://user-images.githubusercontent.com/39654/221970269-5afb31f5-599e-4003-beb9-87df747a4b0f.png)

Before:

![image](https://user-images.githubusercontent.com/39654/221970629-63492229-2e0d-4478-8c90-679d7dc15f12.png)

Just in case review this with: #2676, #2119

**Comment by dacap** [comment]
Tab label is a little higher (not sure what is better):

![image](https://user-images.githubusercontent.com/39654/221972732-eb05e6d0-1729-47f9-91de-cb30544b3f77.png)

**Comment by ElderlyGlek** [comment]
> Tab label is a little higher (not sure what is better):
> 
> ![image](https://user-images.githubusercontent.com/39654/221972732-eb05e6d0-1729-47f9-91de-cb30544b3f77.png)

The old tab label is better in my opinion.

**Comment by ElderlyGlek** [comment]
I think these screenshots may be needed:

* 200% screen scaling and 100% UI scaling:

![Correct scaling](https://user-images.githubusercontent.com/69088106/222717665-842ea514-eae3-4e70-bae6-fe54f0afcc11.png)

* 100% screen scaling and 200% UI scaling:

![Incorrect scaling](https://user-images.githubusercontent.com/69088106/222717668-50df88ae-ee0f-466f-a264-02cc85695312.png)

After changing the scale, you need to restart Aseprite, as the buttons behave completely incorrectly (as in the screenshot).

**Comment by dacap** [comment]
@ElderlyGlek several issues are known when changing ui scaling, related to #2571

**Comment by martincapello** [comment]
Okay, previous version have the same issue but as the coordinates are not adjusted, there are cases where the difference is "half" pixel instead of:

<img width="443" alt="ss100_uis200" src="https://user-images.githubusercontent.com/5520828/223803481-b0fd40d0-ce15-4e42-a9a0-939850331ffc.png">

<img width="444" alt="ss200_uis100" src="https://user-images.githubusercontent.com/5520828/223803504-64d90353-7e37-4ad1-aeb5-263b50a63761.png">

If you pixel-compare the position of the tab text and layer's name you will see the 0.5 pixel difference when using UI scale 100% and screen scale 200%.
