### ISSUE TITLE
Possible regression in -save-as, doesn't autodetect frame number at the end when exporting multiple tags

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#3733]
Possible regression using:

```
--batch "${FILE}" 
--save-as="${GAME_ASSETS}/Images/GameSheet/${BASENAME}_{tag}_1.png" 
--data="${GAME_ASSETS}/Animations/${BASENAME}.json" 
--list-tags
```

Now

```
--batch "${FILE}" \
--save-as "${GAME_ASSETS}/Images/GameSheet/${BASENAME}_{tag}_{frame1}.png" \
--data "${GAME_ASSETS}/Animations/${BASENAME}.json"  \
--list-tags
```

Report: https://community.aseprite.org/t/aseprinte-not-exporting-correctly-with-1-3-rc1-arm/17253

EDIT Initial issue fixed with: e865374805f61609604e59a04004578a5633b656

**Comment by niedzielski** [comment]
I think I am seeing a regression that's either this issue or closely related (happy to open a new ticket).

This is the CLI invocation (note the filename-format argument) and [file](https://github.com/oidoid/mem/blob/cd9fe88/src/mem-mono-3x3.aseprite):

```
aseprite --batch --filename-format 'dist/char/mem-mono-3x3-{tag}-10x.bmp' --inner-padding 10 'src/mem-mono-3x3.aseprite' --scale 10 --save-as /dev/null --tagname-format='{title}--{tag}'
```

On v1.3-rc1-x64 I get the expected filenames:

```
mem-mono-3x3-00-10x.bmp
mem-mono-3x3-01-10x.bmp
mem-mono-3x3-02-10x.bmp
...
```

On rc2, I get what I believe is the frame number tacked on:

```
mem-mono-3x3-00-10x1.bmp
mem-mono-3x3-01-10x2.bmp
mem-mono-3x3-02-10x3.bmp
```

**Comment by dacap** [comment]
Hi @niedzielski, yes, it looks like a regression of the regression. I'll check this ASAP.

**Comment by dacap** [comment]
@niedzielski I think if you use 

```
aseprite --batch --inner-padding 10 'src/mem-mono-3x3.aseprite' --scale 10 --save-as 'dist/char/mem-mono-3x3-{tag}-10x.bmp' --tagname-format='{title}--{tag}'
```

It should work. I'll review why this problem happens with --filename-format.

**Comment by dacap** [comment]
@niedzielski After investigating, the problem with [-filename-format](https://www.aseprite.org/docs/cli/#filename-format) is that it doesn't do a [-split-tags](https://www.aseprite.org/docs/cli/#split-tags) as [-save-as](https://www.aseprite.org/docs/cli/#save-as) does automatically.

So your original CLI could be solved with:
```
aseprite --batch --split-tags --filename-format 'dist/char/mem-mono-3x3-{tag}-10x.bmp' ...
```
Anyway I'd highly recommend you to use -save-as directly as it detects the {tag} and does the -split-tags automatically.

I think I'll close this issue as it's working as expected (it looks like the -filename-format without -split-tags for tags with one frame was working just by mistake, but the new behavior is the expected one).

**Comment by niedzielski** [comment]
@dacap, thank you! I think this is working as hoped for my use-case. In case it's helpful for you, I will note:

1. Using `--split-tags` seems to break both a) sheet packing options (neither `--sheet-pack-rows` and `--sheet-pack-columns` is respected) and b) `--filename-format='{title}--{tag}--{frame}'` always yields a frame of 0. I discovered these issues by trying to blindly jam `--split-tags` into similar recipes I had.
2. Using the CLI correctly is becoming increasingly sophisticated. I think more docs around argument ordering and incompatible configurations (eg, `--split-tags` with `--sheet-pack-rows`) would be helpful. In my mind, the point of the CLI is so that artists don't have to learn Lua to batch export and the docs really help. I think one of Aseprite's great features is the JSON format and the CLI that generates it!

I realize neither is likely at the top of your list but mention it because I think it's an important part of Asesprite. I am happy to make issues if you like but didn't want to waste the effort if not.

Thanks again for the quick help!
