### ISSUE TITLE
Trim Sprite option is ignored

### ISSUE THREAD

**Issue by Geokureli** [aseprite/aseprite#3740]
v.1.2.4-x64 for Mac
[example.zip](https://github.com/aseprite/aseprite/files/10935090/example.zip)

The above example .aseprite file is 512x512, if I select `Sprite > Trim` it becomes 201x148. When I export with `Trim Sprite` enabled I expect the json frames to have a sourceSize of `{ "w": 201 "h": 148 }` but it is actually `{ "w": 512, "h": 512 }`

<img width="582" alt="Screenshot 2023-03-09 at 1 11 26 PM" src="https://user-images.githubusercontent.com/2609513/224130078-a24c7c4d-5b9e-4eaa-aba0-e7e55540e011.png">

**Comment by Gasparoken** [comment]
'Trim Sprite' option on 'Export Sprite Sheet' works only to trim the whole sprite before its frames are included in the sprite sheet, but it hasn't influence to 'sourceSize' field. 'Trim Sprite' is useful to get a sprite sheet of a smaller size.
The Json data must be able to reconstruct the animation at its original size, that's why that size is displayed.

Just in case: [Difference between 'Trim Sprite' and 'Trim Cels'](https://community.aseprite.org/t/export-sprite-sheet-difference-between-trim-sprite-an-trim-cels/17365)

This is not a bug.

**Comment by Geokureli** [comment]
Should there be a different checkbox for this? It would save me the trouble of resizing and re-trimming the image every time i add/edit frames

**Comment by Gasparoken** [comment]
This can be done through a simple script, even with a little extension (i.e. adding a custom command in the File menu)

**trimSpriteBeforeExport.lua**
```
app.command.AutocropSprite{}
app.command.ExportSpriteSheet{ui=true}
app.command.Undo{}
```
This script trims the sprite > open the export sprite sheet dialog > finally 'undo' the 'Trim Sprite' command.

You're right, 'Trim Cel' always trims the same or more than 'Trim Sprite', then it seems like Trim Sprite does nothing.

**Comment by Geokureli** [comment]
thanks for the tip, and for answering my questions
