### ISSUE TITLE
Calling `print` function within the `onpaint` method causes and additional dialog to be rendered

### ISSUE THREAD

**Issue by thkwznk** [aseprite/aseprite#3746]
Demo code to replicate the issue:

```lua
if app.apiVersion < 21 then
    print("API version is lower than 21")
    return
end

local dialog = Dialog("Canvas Resize Test")

dialog --
:canvas{
    width = 200,
    height = 200,
    onpaint = function(ev)
        local context = ev.context

        print(context.width, context.height)
    end
} 

dialog:show()
```

Preview:

![canvas-print-issue](https://user-images.githubusercontent.com/10217876/224553708-f9dc16c6-4601-4e3c-9a39-fe841c2e7fe9.gif)

### Aseprite and System version

* Aseprite version: 1.3-rc1-x64, Steam
* System: Windows 11

**Comment by dacap** [comment]
@martincapello I wasn't able to reproduce this bug on Windows, Linux, or macOS (main and -rc1), is there some special step to reproduce it?

**Comment by martincapello** [comment]
No, just used the demo code. In macOS make sure that you are using multiple windows feature and also that you click on the script from the apple menu bar, not from the Aseprite menu...I will double check on windows now...

**Comment by martincapello** [comment]
Just tested in Windows and it seems that when you run the script from the menu, sometimes it reproduces the issue...I didn't realize this until now. If you assign a key shortcut to run the script, it seems that this issue happens always. So, try assigning a key shortcut to run the script.
I did this, and now it seems that the issue is not actually fixed, because it still happens when using the keyboard shortcut...will investigate.
