### ISSUE TITLE
Effects apply to all layers

### ISSUE THREAD

**Issue by BlueStaggo** [aseprite/aseprite#3753]
I tried to apply an effect to a single layer (color curve, brightness/contrast, convolution matrix, etc.). The preview is a lie, because when I apply the adjustment, it applies to every layer and not just the layer I have currently selected.

https://user-images.githubusercontent.com/71090710/225115973-85678ccd-df0a-42c1-95de-34758c7c760b.mp4

### Aseprite and System version

* Aseprite version: v1.3-rc1-x64, Steam beta
* System: Windows 11 21H2

**Comment by Gasparoken** [comment]
Thanks for this report. The preview on **All** layers is a known issue: https://github.com/aseprite/aseprite/issues/841.

Anyway you can apply the effect only to **Selected** layer instead of **All** layers.
<img width="450" alt="Screenshot 2023-03-16 at 10 33 45" src="https://user-images.githubusercontent.com/32165475/225633703-0a0804d6-d4f8-46c3-9471-23c89a55897a.png">
