### ISSUE TITLE
Problems with scripts (and the the program itself) creating big windows

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#3839]
If a script creates a window that is big enough in such a way that its title bar is not visible, the window cannot be moved and it's super confusing to the user. E.g.

* https://community.aseprite.org/t/extension-palette-helper/14429/16?u=dacap
* https://community.aseprite.org/t/extension-palette-helper/14429/22?u=dacap

We should check the visibility of any window that is created, the title bar must be visible (maybe a scrollbar?). Probably a problem only in the one-window interface (check if it's an issue for #3556)

**Comment by martincapello** [comment]
As far as I was able to see, I can confirm that this is only an issue for the one-window interface, because window movement is handled by the OS when using the UI with multiple windows. 
However a window might have a size bigger than the current display resolution, I'm not sure if we should do something about this, I believe that it should be the UI designer responsibility to take into account this possibility..BUT, when developing an extension using a `Dialog` one doesn't have much flexibility, so we should support the possibility to add scrollbars to `Dialog` or maybe just adding a new `Tab` control would be enough to let the dev distribute the controls to avoid giant windows.

So, I believe we must:
- Prevent moving a window in such a way that its title bar is being hidden when using the single-window UI.
- Add a new `Tab`widget.
- Add scrollbars to `Dialog`.

**Comment by dacap** [comment]
About the scrollbars, menu boxes introduce scrollbars automatically if needed: https://github.com/aseprite/aseprite/blob/c527d68c648bc244a3f8952dd0c8ddf645968fbf/src/ui/menu.cpp#L138
