### ISSUE TITLE
Problem of not being able to save work on macOS 10.11 series

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#3984]
In the last month, we received 3 support tickets with problem of not being able to save work on macOS 10.11 series.

Possible issue on native "Save As" menu.

Console message trying to Save As:
```
An unknown error occurred executing the command. Please save your work, close the program, try it again, and report this bug.

Details: unknown exception caught. This can be bad memory access, division by zero, etc.
```

Internal references:
https://igarastudio.zendesk.com/agent/tickets/4939
https://igarastudio.zendesk.com/agent/tickets/5018
https://igarastudio.zendesk.com/agent/tickets/5035

### Aseprite and System version

* Aseprite version: 1.3rc5
* System: macOS 10.11.3 and 10.11.6

**Comment by dacap** [comment]
Probably a release blocker (i.e. we cannot release v1.3 with this bug), I'll try to get a macOS 10.11.3 (I think I have an old Macbook with 10.11, but I'm not sure)

**Comment by dacap** [comment]
I tried to create a macOS VM on Parallels Desktop with El Capitan (10.11), but basically it's impossible to find an image to install this old OS.

From the developer forum: https://developer.apple.com/forums/thread/44984

I'll try to test this in a pretty old MacBook 2012. Anyway the solution might be just disable the native file selector in OS X 10.x series (and enable only since 11.x)

**Comment by dacap** [comment]
Tested in my old MacBook (OS X 10.13) and it worked:

![Screen Shot 2023-09-13 at 09 18 45](https://github.com/aseprite/aseprite/assets/39654/95b7b441-5b0c-4434-a2e8-56c51dfb6c4e)

We've disable the native file selector for 10.11 or older versions.
