### ISSUE TITLE
The Aseprite file explorer is gone

### ISSUE THREAD

**Issue by TechBlade9000** [aseprite/aseprite#4051]
The custom asprite file explorer seems to be missing and uses the default Windows version instead

Aseprite version: v1.3-rc6

**Comment by dacap** [comment]
Hi @TechBlade9000, actually we've changed the default option now as it's the "most expected" way to select files by most (new) users. Anyway you can still go back to the Aseprite file selector unchecking the *Edit > Preferences > Experimental > Use native file dialog* checkbox.

In some way we'd like to make this option more visible (e.g. a button in the dialog to switch between both dialogs, I remember some old Photoshop version had something similar to this, not sure if they still are doing so). Also we'd like to provide a way to show a folder in a tab (some kind of folder browser that is always opened) in a near future.

**Comment by dacap** [comment]
We'll have a new more accessible option in *Edit > Preferences > General > Show Aseprite file dialog*
 
![Screenshot 2023-10-04 at 16 55 39](https://github.com/aseprite/aseprite/assets/39654/f30d21c2-6140-4f47-88ab-ecd8197d8d8b)

(The old option in "Experimental" will still exists because there are too much documentation/forum posts referencing it.)
