### ISSUE TITLE
Tilemap cel image saveAs call leads to segmentation fault.

### ISSUE THREAD

**Issue by zarstensen** [aseprite/aseprite#4069]
### Issue
When calling Image:SaveAs() on a image from a cel in a tilemap, a segmentation fault happens which leads to the app exiting.

### Reproduce

Run a script with the following code snippet with the attached [aseprite file](https://github.com/aseprite/aseprite/files/12719091/tilemap-crash.zip) open, and observe the app crash.
```lua
app.sprite.layers[1].cels[1].image:saveAs("image.png")
```

### Aseprite and System version

* Aseprite version: 1.3-rc6-x64 and commit 19b54ff
* System: Windows 10.0.19045

**Comment by dacap** [comment]
Thanks @zarstensen, I was able to reproduce it.

This case is interesting because a tilemap layer cel is an image with indexes/references to the tileset, but I think that the expected behavior would be to save an image of the rendered tilemap as it looks in the canvas (instead of the tilemap data/indexes as an indexed image).
