### ISSUE TITLE
Sometimes may appear rendering shadows on text.

### ISSUE THREAD

**Issue by TakWolf** [aseprite/aseprite#4199]
Sometimes may appear rendering shadows on text. When triggering UI element redrawing then return to normal.

* Aseprite version: 1.3.2-dev-build
* System: macOS 14.0 m1-pro

This issue has already appeared in version 1.3-rc.

<img width="1040" alt="image" src="https://github.com/aseprite/aseprite/assets/6064962/e539b6cd-efe6-474d-b882-07cf5a9ee92f">

I used a custom font in theme and I'm not sure if it's related to it.

```xml
 <font name="fusion-pixel-10px-proportional" type="truetype" antialias="false" file="./fonts/10/fusion-pixel-10px-proportional-zh_hans.ttf"/>
```

**Comment by martincapello** [comment]
I couldn't reproduce this issue. I've downloaded the font you mention from https://github.com/TakWolf/fusion-pixel-font/releases/tag/dev-2024.01.04 and added the font configuration to my fonts.xml.
However, I had to use this path `10/fusion-pixel-10px-proportional-zh_hans.ttf` instead of the one you mention, maybe because I put the font file inside of `.../data/fonts/10` directory.
Then I updated the font element in my theme.xml:
```xml
<font id="default" font="fusion-pixel-10px-proportional" />
```
Also I've downloaded and installed the simplified Chinese language extension from:
https://github.com/J-11/Aseprite-Simplified-Chinese/releases/download/1.3-rc1/Aseprite.1.3rc1.aseprite-extension
I've tried in Aseprite v1.3.2 and the current dev version from the main branch. I'm also using macOS 12 on a macbook pro m1.

With this setup I wasn't able to reproduce this issue. Maybe you have something different (besides the macOS version)?
Or maybe there are some specific steps that I can't find...

**Comment by martincapello** [comment]
Thank you for recording a video showing the issue! I've actually tried to do that...with no luck.
But what I'm able to see in your video is that your windows have a title bar bigger (in height) than mine...maybe because I just took the default aseprite theme and just changed the font, nothing else. So if you could share the theme you are using with us I can check if it is because of that. Please send it to support@aseprite.org if you can share it. Or maybe we can download it from some url...just let me know.

**Comment by TakWolf** [comment]
The theme I am using is here: 
https://github.com/aseprite-quest/aseprite-unified-pixel-theme/releases
I don't think it's anything special, it's just that the default theme has been modified with the OpenType font.


Some supplements:

<img width="362" alt="image" src="https://github.com/aseprite/aseprite/assets/6064962/921f42a3-4bd2-4cc9-a6cb-334359d8aeb9">

To reproduce the issue, it must be closed `UI with multiple windows`.

At this point, if the parent window is overwritten or the child window exceeds the screen range, the problem will occur.


Additionally, this seems to be unrelated to the operating system. I tested on Windows 10 and found the exact same issue.
