### ISSUE TITLE
Translation migration to Weblate

### ISSUE THREAD

**Issue by lufog** [aseprite/aseprite#4210]
A [small translation project](https://github.com/lufog/aseprite-language-russian) that I have been maintaining since 2019 on my own in my free time, in my repository. It was [imported into the Weblate](https://hosted.weblate.org/projects/aseprite/aseprite/ru/) service, and any mention of me as the author who worked on this translation was lost in the process. Please either reset the translation and start it again (without using my repository as an import source) or indicate attribution as required by CC BY 4.0. Let me clarify, I will not work on the translation in Weblate, I will only maintain my repository. If it is used as a source, please do not remove the attribution.

**Comment by TakWolf** [comment]
Hello, @lufog the imported behavior is my personal behavior,  not aseprite official.

I'm sorry for the offense. As @dacap  said, currently the translations have not been merged to master, so your translation will not be used. I apologize for any inconvenience caused.

**Comment by dacap** [comment]
I've just updated the Weblate project https://hosted.weblate.org/projects/aseprite/aseprite/ removing the Russian translation and others from third-parties.

We'll only integrate translations that are uploaded from original authors 👍

**Comment by lufog** [comment]
@dacap, I tried, but got 1500+ `Has been translated` errors. Not sure what to do with this... 🤷‍♂️

**Comment by dacap** [comment]
@lufog I'm a little lost here (I'm new with the weblate interface), just in case you can try these options:

<img width="416" alt="image" src="https://github.com/aseprite/aseprite/assets/39654/8527ae39-3159-43db-9f9e-fab28024f13c">

But probably @TakWolf can help us to solve this.

**Comment by TakWolf** [comment]
Hi @lufog, Weblate only accepts standard '.ini' format files, so the old aseprite '.ini' will lose the strings like the following fragments:

```ini
some_key = <<<END
Here
is
the 
text.
END
```

We need to convert to:

```ini
some_key = Here\nis\nthe\ntext.
```

You can use the following file to complete the import:

https://github.com/aseprite-quest/aseprite-unified-languages/blob/master/data/ru.ini 

This is the just format conversion of the final node of your translation, without text changes.

You should use the following options:

![image](https://github.com/aseprite/aseprite/assets/6064962/2fc987ce-fd12-4329-aa03-68451fafe54b)

This will be completely replaced with your translation.

Attention, due to https://github.com/aseprite/aseprite/issues/4208

Follow strings will be lost and needs to be supplemented later after issues is fixed:

```
[color_bar]
remap_palette = Remap Palette
remap_palette_tooltip = Matches old indexes with new indexes
remap_tiles = Remap Tiles
remap_tiles_tooltip = Matches old tiles with new tiles

[commands]
RemoveFrame = Remove Frame
RemoveFrameTag = Remove Tag
RemoveLayer = Remove Layer
RemoveSlice = Remove Slice
```

Additionally, you need to check the follow strings format which adjust in https://github.com/aseprite/aseprite/commit/84187ad1ec04e8b2cadb53c5f45d2c22044ba523

```
PaletteEditor = Switch {0} {1} {2}
PaletteEditor_Edit = Edit Palette Mode
PaletteEditor_And = and
PaletteEditor_FgPopup = Foreground Color Popup
PaletteEditor_BgPopup = Background Color Popup
```

The above are all the issues that need attention, hoping to be helpful to you.
