### ISSUE TITLE
Copy-Paste error: Too much data to uncompress for the image

### ISSUE THREAD

**Issue by Gasparoken** [aseprite/aseprite#4291]
Sometimes copying and then pasting an image produces an error:
`Too much data to uncompress for the image, and the image isn't pasted.`
A small change to the image (such as a pixel color change) can allow copy and paste operation without error.
Reported here: https://community.aseprite.org/t/too-much-data-to-uncompress-for-the-image/21157
Also reported here (Internal): https://igarastudio.zendesk.com/agent/tickets/5763 includes a sample image.

### Aseprite and System version

* Aseprite version: 1.3.2
* System: Windows and macOS

**Comment by dacap** [comment]
@martincapello found some related issues/posts/tickets too:

* https://igarastudio.zendesk.com/agent/tickets/5644
* https://community.aseprite.org/t/too-much-data-to-uncompress-for-the-image/21157
* https://community.aseprite.org/t/first-day-pasting-from-one-sprite-to-another-and-it-wont-uncompress/20941

And today we've received https://igarastudio.zendesk.com/agent/tickets/5773 for the same issue.

**Comment by dacap** [comment]
When this happens the last `err` is `Z_OK`:
<img width="602" alt="image" src="https://github.com/aseprite/aseprite/assets/39654/08f24050-fae6-43a3-b96a-608dc45f69d5">

If we skip to line 179 (instead of throwing the exception) the `next_out` will be `address_end` and `avail_out` will be zero which are correct values. After the next `inflate()` in line 182 the `err` will be `Z_STREAM_END`, so it looks a correct alternative to end the decompression process.

I'll post a fix for this.
