### ISSUE TITLE
Get a GraphicsContext to modify an Image/Sprite

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4330]
I though there were an issue created for this one, anyway it would be nice to be able to get a GraphicsContext to modify an Image. The tricky part here is to be able to undo all the modifications when the GraphicsContext is not used anymore.

Requested in the past and recently:
* ~~https://community.aseprite.org/t/how-to-draw-a-sprite-with-graphics-context/20572~~
* https://community.aseprite.org/t/why-is-this-returning-a-nil/21525

The function `wrap_docimage_in_sksurface()` can be used for this purpose (not sure if this would work on all color modes).

EDIT: The crossed out link is about drawing in a GraphicsContext received in the onpaint event, so it is actually a different issue, also it is not actually an issue, since the user was trying to draw an sprite using GraphicsContext::drawImage, which receives an Image as a parameter, not an Sprite. Someone from the community gave the user a right answer, so there is no need to create an new github issue.

**Comment by martincapello** [comment]
I've a couple of questions about this issue:
1) How https://community.aseprite.org/t/how-to-draw-a-sprite-with-graphics-context/20572 is related to getting a GraphicsContext from an image? I'm asking because the user seems to only want to draw an image on the onpaint's GraphicsContext.
2) Why should the user be able to undo all the modifications made to an image through its GraphicsContext? Shouldn't the GraphicsContext be a low-level api thing to just modify the images directly?

**Comment by dacap** [comment]
> 1. How https://community.aseprite.org/t/how-to-draw-a-sprite-with-graphics-context/20572 is related 

Probably I misread the topic in the forum, from the title I thought it was related to "how to draw a sprite using a graphics context."

> 2. Why should the user be able to undo all the modifications made to an image

The best solution will be to just ignore the undo and modify the image directly (just like [Image:drawPixel()](https://www.aseprite.org/api/image#imagedrawpixel) does and documents), so if the user wants undo info they can just [patch the image](https://www.aseprite.org/api/image#imagedrawimage).

**Comment by martincapello** [comment]
> Probably I misread the topic in the forum, from the title I thought it was related to "how to draw a sprite using a graphics context."

Makes sense. I'll see if I found an issue for this to move the link to its description. In case I can't find it, I will create a new one.

> The best solution will be to just ignore the undo and modify the image directly (just like [Image:drawPixel()](https://www.aseprite.org/api/image#imagedrawpixel) does and documents), so if the user wants undo info they can just [patch the image](https://www.aseprite.org/api/image#imagedrawimage).

 🥳

**Comment by martincapello** [comment]
I've tried to locate the wrap_docimage_in_sksurface function without any success...where can I find it?

**Comment by dacap** [comment]
I think it's `make_skcanvas_for_docimage()`, probably not 100% functional because different color modes (for RGB images it should work correctly).

**Comment by martincapello** [comment]
Oh, I have just realized that convert_image_to_surface is converting the image into a surface, not getting something that I can use to draw onto the image...

**Comment by martincapello** [comment]
At the end `make_skcanvas_for_docimage()` didn't worked for me because once I have the `SkCanvas` I tried to call  `SkCanvas::makeSurface` to create the surface, but it turned out that the surface returned points to a new canvas, and then when I modify the surface, that new canvas is modified, not the one I've created by calling `make_skcanvas_for_docimage()`.

For this reason I've created a new method `make_sksurface_for_docimage` that creates the surface I need. I'm about to create a PR.
