### ISSUE TITLE
Ctrl key alone is not useful to drag brush size value

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4484]
From: https://community.aseprite.org/t/ctrl-z-and-lost-brushstrokes/22112

Configuring <kbd>Ctrl</kbd> key to drag the brush size:
![image](https://github.com/aseprite/aseprite/assets/39654/0cb5523c-30b1-4bb2-8d9a-79246869d182)

Then each time we use <kbd>Ctrl+Z</kbd>, the first stroke is ignored.

**Comment by Liebranca** [comment]
Note: this would happen with commands other than undo, long as the keys overlap, because the mouse wasn't released when leaving the dragging value state because of command execution.

Seemingly fixed [here](https://github.com/Liebranca/aseprite/commit/d540107531fc75be3169c317df082aaf791487e6), but I made a mistake setting up the branch (my bad). I'll correct this when I have a minute, apologies for the inconvenience.

**Comment by dacap** [comment]
> Seemingly fixed [here](https://github.com/Liebranca/aseprite/commit/d540107531fc75be3169c317df082aaf791487e6), but I made a mistake setting up the branch (my bad). I'll correct this when I have a minute, apologies for the inconvenience.

No problem about that! remember to create the PR when you have a commit (or send me an email in case you have some question). Generally we don't pull directly from other repos and we test/merge from PRs.
