### ISSUE TITLE
Instructions on how to compile for windows and linux?

### ISSUE THREAD

**Issue by RakibRyan** [aseprite/aseprite#4562]

**Comment by dacap** [comment]
Hi @RakibRyan, you can find the compilation instructions for these platforms in the INSTALL guide: https://github.com/aseprite/aseprite/blob/main/INSTALL.md

**Comment by derVedro** [comment]
Compilation from the release source tarball is doomed to failure because of the absence of third party stuff. Since extracting downloaded tarball or zip file doesn't create a local repository, you can not just pull them through `git submodule update --init --recursive`. Perhaps this should be mentioned to the INSTALL.md.

**Comment by dacap** [comment]
> Compilation from the release source tarball is doomed to failure

Known issue from GitHub, that's why we release a full .zip with the whole source code in Releases: https://github.com/aseprite/aseprite/releases

The install guide tells how to get the source code in a correct way: https://github.com/aseprite/aseprite/blob/main/INSTALL.md#get-the-source-code

Probably we could clarify the GitHub download button is useless, but I don't know if that will prevent this problem in the future (it's a UX problem in the GitHub website, I don't know why they don't fix it or offer a way to disable the button).

**Comment by derVedro** [comment]
Indeed, I did not read this point carefully. The section explicitly says Aseprite-v1.x-Source.zip. I complete missed that moment and out of habit took the last entries that github offers on releases page. Thanks!
