### ISSUE TITLE
New option to "Reset Symmetry to View Center"

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4638]
Requested here: https://community.aseprite.org/t/option-to-show-symmetry-center-in-my-canvas-position/19185

The name could be "Reset Symmetry to Editor Center" or something like that ("to View Center" is confusing). We could drop the "Reset" word too.

**Comment by S4HRKBOY** [comment]
Hello, @dacap!  I wanted to ask if it would be okay trying to implement this feature? Due to the low complexity tag i thought this would be a good first issue ^^. If a feature as a first contribution is not advised (i.e. stated in CONTRIBUTING.md) i can also search for a bug to fix. I managed to get Aseprite built on my system and did a little overview of the codebase.

**Comment by dacap** [comment]
Hi @S4HRKBOY, sure! you can give a try to implement this, it shouldn't be too hard as it's a new option similar to the one that already exists. I'll assign this issue to you, thanks!

**Comment by S4HRKBOY** [comment]
Hi @dacap! I think i got the right place for the code to add another Symmetry-Option and got it working with using the `Editor::activeEditor()` and the resulting bounds. I wanted to ask if i interpreted the request correctly and added a little video with a demonstration.
[Screencast from 09-06-2024 12:18:32 AM.webm](https://github.com/user-attachments/assets/7fae5868-fd59-491c-ac50-e2867136c286)

**Comment by dacap** [comment]
> wanted to ask if i interpreted the request correctly and added a little video with a demonstration.

Hi @S4HRKBOY it looks great! that is exactly how it should work.

**Comment by S4HRKBOY** [comment]
Ok then i would do a PR for this feature.
