### ISSUE TITLE
Disable cursor preview on Preview window

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#4721]
Sometimes it's useful to see the cursor preview in the Preview window to see how the sprite will look if we paint a pixel in the cursor position, at least that was my initial idea.

Some users find this troublesome: https://community.aseprite.org/t/preview-window-cursor/22880

The best would be to disable the cursor preview on the Preview window and add an option to re-enable just in case some user wants it back.

**Comment by S4HRKBOY** [comment]
Hello @dacap. I wanted to ask if i could work on this issue?

**Comment by dacap** [comment]
Hi @S4HRKBOY, sure you can take it  👍

**Comment by S4HRKBOY** [comment]
Hello @dacap! I have a little question for this issue. I looked through the code and have the following problem. I identified that one location where i could manipulate the brush_preview is the BrushPreview::show function (which is pretty big ^^) which gets called in the editor class. My Problem (or more my idea) here is that the AppEditor and PreviewEditor share the memory addresses for Session relevant objects like Doc*, Sprite*, Site*, etc. Because of that i was only able to enable and disable the preview Brush in both Editors through code. I also think that the copying of objects like sprite, doc is discouraged (sometimes indicated with the DISABLE_COPYING(...) Macro. I wanted to ask if i am missing something here and i hope this question is too nooby :X.

**Comment by dacap** [comment]
@S4HRKBOY as this brush preview will depends on the editor (visible on a regular AppEditor, hidden on PreviewEditor), you can ask this information to the editor. For example, in `BrushPreview::show()` you could ask something like:

```c++
void BrushPreview::show(const gfx::Point& screenPos)
{
  if (!m_editor->useBrushPreview())
    return;
...
```
Adding a new `Editor::useBrushPreview()` method asking if it's the preview (`m_docView->isPreview()`) and the user preference (as we should be able to switch this preview back on).

You don't have to copy any doc/sprite/object or deal with the active session, this is a UI problem.
