### ISSUE TITLE
bug: can't delete super-group

### ISSUE THREAD

**Issue by ghost** [aseprite/aseprite#4846]
if you make the following group group/layer setup, the group 4 can't be deleted because the "delete layer" menu-item is disabled.
All ohter groups can be deleted however.

group/layer setup:

![afbeelding](https://github.com/user-attachments/assets/e269b152-1d69-41cd-8829-635f35e11614)

group 4 can't be deleted:
![afbeelding](https://github.com/user-attachments/assets/7f43d092-2d18-4e77-8fe8-b60044b657b4)

### Aseprite and System version

* Aseprite version: 1.3.10
* System: Windows

**Comment by MapleGecko** [comment]
@divoomgirl The reason the option is diabled here is because your timeline cannot be empty.

In your setup, Group 4 includes every other groups and layers in your timeline. Deleting that group would be the same as deleting your entire timeline, which is why the option is diabled.

Creating a new layer or group outside of Group 4 would enable the option to delete it again :)
