### ISSUE TITLE
question: somebody interested to add aseprite support to Tiled?

### ISSUE THREAD

**Issue by ghost** [aseprite/aseprite#4847]
Hi

Is maybe somebody interested to add aseprite support to Tiled?

https://www.mapeditor.org/

https://github.com/mapeditor/tiled/issues/4109

**Comment by bjorn** [comment]
We have just developed https://github.com/mapeditor/qaseprite based on the MIT-licensed parts of Aseprite. I expect to ship this plugin with Tiled in the next release, provided we can get it to compile on the relevant platforms (currently only confirmed to work on Linux).

Please do let us know if this approach to compiling a part of Aseprite into the plugin isn't alright with the licensing or if there are any changes you'd recommend. Even if I find the licensing of Aseprite unfortunate in general, I really appreciate that these lower level parts are available under a free license.

This issue can be closed, in any case.

**Comment by dacap** [comment]
Thanks @bjorn for sharing and to develop that plugin. There is no problem in using the MIT licensed code. I think you are the first one to use some of our MIT code in this way, and it was licensed this way for this kind of purposes. So it's really welcome! :+1:  

As a side note, I'd like to move the encoder too to dio library, but just due to lack of time it hasn't been done yet (progressively we should move more parts of the whole file IO to the dio library).

**Comment by pixelgirly** [comment]
Thanks so much @bjorn
