### ISSUE TITLE
macOS Aseprite App Keeps Unhiding

### ISSUE THREAD

**Issue by mrbrownjeremy** [aseprite/aseprite#4857]
The Aseprite app will unhide and unminimize itself when hidden or minimized. Mercifully, it doesn't force its way to the front, but it is still distracting to have it pop over my other windows when I don't want it visible. 

I recently updated from v1.3.2 to 1.3.10. As far as I can remember this hadn't been an issue before. In terms of troubleshooting, I've tried restarting Aseprite, which didn't help. I haven't not tried a system reboot yet, but can once I've ended my work for the day.

### Aseprite and System version

* Aseprite version: 1.3.10
* System: MacBook Pro 16" 2021 M1 Max running Sequoia 15.1.1

**Comment by dacap** [comment]
Thanks @mrbrownjeremy, I was able to reproduce it.

**Comment by dacap** [comment]
Internal notes: as far as I was able to see, the issue is with `ui::execute_from_ui_thread`, which wakes up the event queue, and [EventQueueOSX::wakeUpQueue()](https://github.com/aseprite/laf/blob/c6cd70ad9743197a05c7af5b5dd4c71ea61926f3/os/osx/event_queue.mm#L133) looks like is unhiding the window.

**Comment by dacap** [comment]
Internal notes: as far as I was able to see, the issue is with `ui::execute_from_ui_thread`, which wakes up the event queue, and [EventQueueOSX::wakeUpQueue()](https://github.com/aseprite/laf/blob/c6cd70ad9743197a05c7af5b5dd4c71ea61926f3/os/osx/event_queue.mm#L133) looks like is unhiding the window.

**Comment by mrbrownjeremy** [comment]
You rock—thank you!
