### ISSUE TITLE
libcurl error in Visual Studio 2012

### ISSUE THREAD

**Issue by Sarseo** [aseprite/aseprite#606]
so there i am, sitting at my desk, and - maybe this has happened to you before - i had this insatiable urge to do some spriting again.  i know i'm not that talented, but when you've done so much coding in a day, the brain just needs a little creative stimulation, right?

having such fond memories of aseprite, i figured it's time to reinstall it.  i get to the website and -- WOAH!  it's $10 now?  i thought this was open source... oh it is... but... the pre-compiled binaries cost money now... donations weren't working?  what?  where was i able to donate before?  surely i'm not the only one who finds this a little suspicious...

well, i'm a programmer.  *i'm going to take a crack at compiling this myself* i say to myself.  and hey, if it turns out to be quick and simple, i'll pay for it anyway.  i had no idea these guys were hurting for money and i liked aseprite last time i used it.  but then... what if it's not quick and simple?  what if there's this one bug during compilation that hasn't been fixed?

![image](https://cloud.githubusercontent.com/assets/6164918/6564494/a5905f2c-c66e-11e4-9938-af7cbbaca1a1.png)

the above screenshot was taken from Visual Studio 2012 update 4 on Windows 7 (64-bit).  needless to say, it doesn't build, and as pointed out, that included library path is probably the problem.  hmmm... why would that path be off, but not the rest?  well, anything i say would just be speculation, but it does look suspicious that none of the other library paths are broken, doesn't it?

alright, so the easy fix is to just change the path here to *..\lib\libcurl.lib*, correct?

but shouldn't the developers be fixing the cmake lists?  i'm not an expert in cmake (in fact, i use the gui.  look ma!  i can use cmake!)  so i shouldn't touch it.  but something was bothering me about that one library path... it was practically screaming a whisper into my ears: "why would we fix this?  buy the binaries!  give us munnies!"

i had my doubts, so i had to investigate further.

the answer (in case anyone is interested) is under "\third_party\curl\lib\CMakeLists.txt".  line 111:
```
if(MSVC)
  if(NOT BUILD_RELEASE_DEBUG_DIRS)
    # Ugly workaround to remove the "/debug" or "/release" in each output
    set_target_properties(${LIB_NAME} PROPERTIES PREFIX "../")
    set_target_properties(${LIB_NAME} PROPERTIES IMPORT_PREFIX "../")
  endif()
endif()
```
i don't know what all the above does, but i certainly don't care about "/debug" or "/release" being injected into my build paths.  you can either comment out the above, or just remove "../" from the above.

naturally, i'm not going to do that, because i already built the darn thing.  but again, i heard the screaming whisper in my ears: "we may not have gotten your munnies, but others will give up sooner. mwahahah!" -- no, the creators of my beloved pixel art editor have stooped to such levels?

unsatisfied with believing that, the only other possibility is the library itself.  so i went and investigated this libcurl library and downloaded version 7.21.6 (included with aseprite's source) which you can get here: http://curl.haxx.se/download/

looking under *lib/CMakeLists.txt* inside that library i was relieved to discover the same text was there also.  soon after, the whispers went away, and i felt relieved.

well that's the end of that, i think.  feeling kind of bad for all that suspicion, i went back to aseprite's website to pay for the product and support it's development -- waaaait a second... let's back up here...

okay, i'm not a cmake expert, like i said, but if MSVC = MicroSoft Visual C (which should be on), why isn't BUILD_RELEASE_DEBUG_DIRS set to on (since that's a more explicit flag)?

i decided to look for where that setting is being toyed with.  i found this: *\third_party\CMakeLists.txt* line 35:
```
if(ENABLE_UPDATER AND NOT USE_SHARED_CURL)
  set(BUILD_RELEASE_DEBUG_DIRS 1)
  add_subdirectory(curl)
endif()
```
now this one **isn't** a curl cmake script.  this is a bonafied aseprite cmakelist.txt file.  hm... looks like it's being enabled, but why isn't it?

going up one more directory (we're now at *\third_party\curl\CMakeLists.txt*) and taking a look at line 83:
```
if(MSVC)
  option(BUILD_RELEASE_DEBUG_DIRS "Set OFF to build each configuration to a separate directory" OFF)
  mark_as_advanced(BUILD_RELEASE_DEBUG_DIRS)
endif()
```
well that doesn't do us a lot of good.  that's inside the 3rd-party lib.  it's being set to "OFF".  now i'm no cmake expert (already mentioned i know), but my gut tells me that a subdir setting overrides a superdir setting...

being limited in my experience with cmake, i turned to stack overflow for my answer: http://stackoverflow.com/questions/3766740/overriding-a-default-option-value-in-cmake-from-a-parent-cmakelists-txt

so if we make the following change to the aforementioned *\third_party\CMakeLists.txt*:
```
if(ENABLE_UPDATER AND NOT USE_SHARED_CURL)
  set(BUILD_RELEASE_DEBUG_DIRS ON CACHE BOOL "Strange that the developer did not do this...")
  add_subdirectory(curl)
endif()
```
running cmake again with this change (again, i use the gui because i'm a windows nerd), it works!  a nice and happy visual studio 2012 project with no build errors out of the box.

then i stared at the doctext i typed in the above example, and i heard the screaming whispers again: "someone else will have the same trouble you had... and pay me instead!"

could just be me and my wild speculations, but as i reflect on the past hour of troubleshooting and writing this up and not making a cent for my time, i am still not sure if i've done the right thing by solving the problem thus preventing (likely common) windows users frustration and the snare-like push towards simply buying the binaries, or if i've done the wrong thing by potentially hurting someone's profits and thus damaging the improvement of my once-beloved spriting tool.

the world of open-source... is it really free?  or is it just meant to exploit those such as myself whose OCD can't stop them from fixing stuff...

... i'm probably still going to just pay for the binaries to support the project still. -_-  which is sad, because i no longer feel the urge to do any spriting now.

**Comment by dacap** [comment]
Hi there, if you don't want to pay for something, you don't need to justify yourself, don't worry, I'll not feel bad about it :smile:

The source code is available for programmers (C++ programmers). Open source is open for people who knows how to fix/change things, that is the whole case of the "freedom" in code, in other case we are just lying to ourselves. If you cannot see and change the code anyway (because lack of knowledge), open source is just not "open".

I think that I've spent an incredible amount of time making Aseprite compilable in 3 platforms and give a product fully open source. But sometimes I cannot test all toolchains, and something will be wrong (e.g. I compile regularly only on Windows, and I use Ninja/makefiles, I don't use Visual Studio solutions/IDE to compile). In those cases, I expect help from other people. It's quite hard to keep the master (or any) branch clean/compilable when you are developing (even when you make tags, when a release is more important for customers than a compilable repository).

I would like to ask you some questions. Do you think that the time you have spent compiling the program is more valuable that the years I've spent programming the product? Do you really think that modifying a couple of lines in some scripts worth something? Do you think you can give customer support, add new features, and fixing bugs? Do you really think that the whole point of a product is just the "compiling" process? Please say "no", please, I'll be depressed some days in other case :disappointed: 

I'll tell you something because I fell like you think that I've made the compilation process "difficult" on purpose: I've done a lot (A LOT) to make Aseprite easily compilable. Even sometimes I've taken decisions (stupid decisions) driven just by the whole idea to make a "easily compilable" program. Some of those decisions are:

* I avoided Boost libraries (a huge set of C++ libraries)
* I've included all third party libraries in the same repository (something you should not expect in other open source programs)

I think that you aren't a C++ programmer, otherwise (just because those two items) you should be grateful to me. I hope you can see the work behind Aseprite, and that sometimes is more important to give a good end-user product instead of a zero-error-compiling-process (E.g. in my list of priorities, bugs in the product are more important than bugs in the compiling process, so I've to dedicate more time fixing bugs in the product).

About some specific points:

> Strange that the developer did not do this...

I don't use the cmake GUI tool, so [my change](https://github.com/aseprite/aseprite/commit/7c9303e91dddac70da3c6430f504ec65f573a64d) was enough to create a working solution from the command line (sorry it didn't work with the cmake GUI tool). And please notice that this change was not needed for me (I compile with Makefiles anyway), so basically I was doing something for other person (and it worked for that person at the moment).

> donations weren't working? what? where was i able to donate before? surely i'm not the only one who finds this a little suspicious...

We're still [accepting donations](http://www.aseprite.org/donate/), and there are two links inside the program to donate (`Support this project` at the status bar, and `Help > Donate` menu) and I've made [a Pledgie campain](https://pledgie.com/campaigns/17819). Nothing worked. Basically it's quite hard to live with donations (at least 12 years show me that). Moreover, it's hard to live selling a product, if knowing that makes you happy.

P.S. In the future I'll be making more intelligent decisions, so expect to compile all third party libraries by hand, I've to update all of them, and I'll not be including their source code anymore in the repository. Just to avoid third party (security) bugs.

**Comment by Sarseo** [comment]
Sorry for being so harsh.  I get bent out of shape when I see a business
strategy that seems odd to me.

* Do you think that the time you have spent compiling the program is more
valuable than all the years I've spent programming the product?
You've written a fantastic program.  There's no doubt about that.
Everyone's time is valuable.  This was me trying to make a point, so no.  I
don't think that at all.

* Do you really think modifying a couple of lines in some scripts worth
something?
I do.  It's tiny compared to the work you've done, but it's still a couple
lines of scripting that involved troubleshooting and learning to achieve.

* Do you think you can give customer support, add new features, and fixing
bugs?
I do it for a living, so yes?

* Do you really think that the whole point of a product is just the
"compiling" process?
No.  I guess it baffles me that not more people use Visual Studio for
compiling.  I could just use the visual C compiler from the command line,
but I don't see the value in it.  I'd have to create a build script, which
I've done before (vcvars and cl and all that), but my main platform is
Windows so I haven't found a need to yet.

I also tried cmake from the command line (first thing I did next), and it
didn't work.  I don't know why it would work for you.  CMake from command
line still uses the same CMakeList scripts, doesn't it?

I am a programmer, despite what you think.  Most of my experience is C# and
Java, but I'm familiar enough with C/C++ to call myself a C++ programmer.
I broke down the steps I took in my entire post to demonstrate that I knew
what I was doing.  I even went as far as making sure my suggested changes
did not change any 3rd-party libraries (which only a programmer should know
not to do).  You'd have probably gotten something vague or a question
lacking important details, but I know what it's like to get a bug report
that only says: "It's broken, and not working, fix it!".  I didn't want to
do that.  In fact, if I knew how to contribute directly on github, I
might've just done that instead.  But I wanted to make a point as well (I'm
sorry for that), and obviously you would've discovered something this small
eventually anyway.

I'm going to donate anyway.  I was thinking about it all day yesterday.  I
think you deserve it, especially for reading my post and replying with all
this (thank you).


What strikes me as "unethical" is that you're not actually selling
anything.  You're just selling a different format of information, an extra
step in the development lifecycle.  I can appreciate you want to make
something for your time - heck I make a worthless sum at my current job,
which is why I'm considering a different career.  I mean it could be worse,
you could force an annoying popup in the program, or lock the program down
after 30 days, but that's cheap and rude to end users.  But it's also
something that targets artists, whom most would probably not be capable of
going through the process I have.  I know what I've said probably bothers
you since you've dedicated such a large amount of time to this project, and
I have no other alternative I could suggest for earning something for it
all.  I'm sorry for that.

That said, it's not my place to tell you how to do business.  I'm just
giving you my thoughts on the subject.


Thank you very much for getting back to me. :)  Again, I'm sorry if my post
was rude.  You are welcome to delete it and such.


Sarseo

**Comment by dacap** [comment]
> Sorry for being so harsh.

Don't worry at all :+1: 

> > Do you think you can give customer support, add new features, and fixing bugs?
>
> I do it for a living, so yes?

Well, I was talking about Aseprite customer support, new features, and bug fixing :smile: 

> CMake from command line still uses the same CMakeList scripts,
> doesn't it?

It should, so it's a really strange behavior. Maybe cmake GUI prefers `option()` values instead of inline `set()` as default values to fill the `CMakeCache.txt` file. I'll give a try to the whole solution creation process using the command line and the GUI, and try your change, maybe that `set(BUILD_RELEASE_DEBUG_DIRS ON)` is better than `set(BUILD_RELEASE_DEBUG_DIRS 1)`.

> I'm familiar enough with C/C++ to call myself a C++ programmer.

So you know, C++ toolchains are a complete mess, it's a pity, but is the current state-of-the-art :sob:

> I broke down the steps [...], but I know what it's like to get a bug report that only says: "It's broken, and not working, fix it!".  I didn't want to do that. [...] But I wanted to make a point as well (I'm sorry for that)

Don't worry. You can share with me any opinion you like, but I'd prefer them in comments, or tweets, or emails (or a link to a specific blog post). I know you wanted to describe the whole thinking process, anyway I'd prefer short issues and to the point: problem+fix-business issues :wink:

> I'm going to donate anyway.  I was thinking about it all day yesterday.  I think you deserve it, especially for reading my post and replying with all this (thank you).

Thank you! Anyway you'll prefer to buy it: https://gumroad.com/l/aseprite
If you need to use PayPal, contact me at support@aseprite.org

> What strikes me as "unethical" is that you're not actually selling anything. You're just selling a different format of information, an extra step in the development lifecycle.

I'm [selling several things](http://www.aseprite.org/faq/#What-do-I-get-when-I-buy-Aseprite). Code signing certificates aren't cheap. Also I'm using a clean Windows virtual machine to create official binaries and an untouched MacBook to compile both binaries (to avoid viruses). This build "infrastructure" isn't cheap. I'm a registered Apple developer, and member of [BizSpark program](http://www.microsoft.com/bizspark/), that means in the future I'll renew a MSDN subscription :cry: 

> heck I make a worthless sum at my current job, which is why I'm considering a different career.

You shouldn't give up if you really like to program. Don't give up!

> That said, it's not my place to tell you how to do business. I'm just giving you my thoughts on the subject.

I appreciate them. If that is your concern, Aseprite is actually [my only job](https://twitter.com/davidcapello/status/571402109041692672) ([more info](http://blog.aseprite.org/post/109885153230/aseprite-1-0-9-and-other-news)), so it's working pretty well, it could be a lot better, but I can afford a live with it.

Best regards and thanks to share your thoughts!

**Comment by Sarseo** [comment]
Yah, I should've probably just sent an email.  Sorry about that. :(

Personally, I think C++ is a mess in general.  I love the language, but
compilation has always been a hassle for me.  Not to mention the whole
C++11 -> C++14 mess of things.

I forgot about the code signing and all that overhead.  I can't say if I
agree that the ends justify the means, but I sympathize and understand what
you're saying.  I used to like programming, but I got into it because I
wanted to make video games, not business apps, and spending 6 years doing
it, it feels like a thankless profession with knowledge and experience in
technology that goes obsolete in 2-4 years anyway.  Still, I'll keep at it
until it becomes necessary or convenient to switch. :)

I had no idea this was your only job as well.  I'm glad it's sustainable.
If I spot anything else that I think I can fix, I'll be sure to let you
know (with a little more tact next time. ;).

You made an awesome application - there's a reason I came back to download
it again. ;)


Sarseo

**Comment by dacap** [comment]
Done. It was giving problems again so I've included [your fix](https://github.com/aseprite/aseprite/commit/2c408e4c98b9cc0d775309f17100cd0b882f4671). I think this is a new cmake behavior (maybe 3.0), but I cannot tell for sure why this problem appeared again.

> If I spot anything else that I think I can fix, I'll be sure to let you know (with a little more tact next time. ;).

And every contribution will be welcome!

> You made an awesome application - there's a reason I came back to download it again. ;)

Thanks for your kind words!
