### ISSUE TITLE
Menu-View-Home problem

### ISSUE THREAD

**Issue by blackmiaool** [aseprite/aseprite#649]
If home page is shown , click the "Menu-View-Home" option have no effect.So I decide to make it disable on this condition , but I found getHomeView is a private method .... 
In addition , I think it's better that jump to home page when click Home option on menu.

**Comment by dacap** [comment]
The last one. I was thinking to implement that View > Home should focus/jump the Home tab when it's not selected. (And do nothing if it's visible and selected.)

Recommendation: Instead of making getHomeView() public, you could try to add a new public member function to MainWindow, something like MainWindow::selectHomeView()

**Comment by dacap** [comment]
Fixed with #653
