### ISSUE TITLE
Improve handling of overlapping frame tags in the Timeline

### ISSUE THREAD

**Issue by dacap** [aseprite/aseprite#768]
If we define two or more tags in the same frame range (or sharing frames), it's not easy enough to handle/select/modify them.

**Comment by jpnk** [comment]
here's a rough idea i wanted to share:
- the timeline widget contains tabs corresponding to different frame tags. each tab displays the same timeline but differently.
- you start with a default tab corresponding to the animation that's gonna play when you press **Enter**.
- then you select some cells on one or more layers (or frames if you're selecting from all the layers) and press **F2** to create a new frame tag. this will create a new tab for that tag.
- on each tab created this way all unrelated cells and layers are greyed out.
- on the default tab all the cells that belong to a frame tag are (possibly) colorcoded and trying to change them causes a switch to the corresponding tab. since all the tabs display the same timeline the switch shouldn't be too disorienting.
- ultimately as you move all separate animations into individual tabs the default tab becomes a map of your entire composite animation.

again, this is a very rough idea but i hope it makes it easier to create the kind of composite animation i described in #767.

**Comment by oceanhahn** [comment]
Aa, it is quite similar to what I had suggested. @jpnk, what do you think of the mockup I made in #920?
