### ISSUE TITLE
Add Windows (Super) Key as Modifier for the Keyboard Shortcut Menu

### ISSUE THREAD

**Issue by raetiacorvus** [aseprite/aseprite#796]
Because some WM and Linux Distros use the Alt Modifier Key as Window Action Key (Window Movement etc.) it would be nice if it would be possible to use the Windows key instead for some people, but it should not be changed as default on Linux because some WM and Distros use the Windows (Super) Key as Default Window Action Key.

So there would be three possible solutions:
- Add the Windows Key as part of the Modifier Selection in Keyboard Shortcuts customization.
- Implement a switch or button in the options or keyboard shortcuts menu that changes all alt shortcuts with windows key shortcuts.
- Keep things as they are and have people either modify shortcuts that they use keys other than alt and windows or have them change the Window Action Key to something else then Alt. 

Deciding for and if necessary implementing one of the solutions should close #83  #205  and #235 .

**Comment by sirblackheart** [comment]
Sorry for the many commits, i did amends and did not know github would behave this way.
For further steps it is probably best to take a look how Inkscape handles this.
So it would be probably best to inform linux users about the alt key issue in some form and how they can handle the problem.
Inkscape has a FAQ entry in its wiki that describes how they can either change the modifier key in Inkscape or how to change the Window Action Key in some of the more popular WMs.
[Example in the Inkscape Wiki](http://wiki.inkscape.org/wiki/index.php/Frequently_asked_questions#How_can_I_make_Alt.2Bclick_and_Alt.2Bdrag_work_on_Linux.3F)

**Comment by dacap** [comment]
Thanks for the patch @sirblackheart, I'll take a look in these days. (Just a comment, should we use `Windows` or `Win` text in the key string?)

**Comment by dacap** [comment]
Meanwhile (just a rant) I wonder why Window Manager developers (GNOME, KDE, Xfce, fluxbox, IceWM, etc) don't change the default modifier to the `Win` key instead of the `Alt` key. I see this as the most incompatible thing with PC/Windows programs (and even with OS X apps too). Almost all graphics programs that I know use `Alt` modifier.

Indeed, the `Win` key is just perfect for this case. E.g. `Win` key+mouse drag: resizes the window.

`Win` key = everything related to the window manager.

Anyway, I think that some day the world will be better. When text files with CRLF and tabs don't exist anymore, and window managers don't grab the `Alt` modifier.

#### Possible solution
> (that should be provided by window manager developers)

There should be a library to get the state of the `Alt` modifier on each window manager, so we can know if the `Alt` key is used by the WM or not. If it is we could give alternative keyboard shortcuts.

Or a better (and straightforward) solution would be: WMs should do the same that major OS vendors do: Just leave the `Alt` key for apps.

/endofrant (sorry)

**Comment by sirblackheart** [comment]
Sure Win is fine and probably nicer on the eye, i was unsure which to choose between Win and Windows. So with my next commit I switched to Win for Windows and to Super for Linux.

**Comment by Viomi** [comment]
Personally, I think the most straight-forward option is to just make a setting for it. Use win key vs use alt key.

Openbox actually lets you keybind whatever you want in rc.xml, so I can make my window manager use Win key instead of alt key. The only issue is, it already has quite a few options that use the Win key as it is. So I'll have to work around and try and find a way to have alt-f1 and win-f1 both be useable without taking up alt :/

**Comment by sirblackheart** [comment]
As Aseprite already has the nice feature to import and export Keyboard Shortcuts, maybe Aseprite should just ship with an alternative version of the Keyboard Shortcuts as importable.

**Comment by dacap** [comment]
I'm not used to the `Super` denomination (mainly because I've never customized a WM and I almost do console work on Linux). I find quite interesting that there is a Ubuntu page talking about [What is the "Super" key?](https://help.ubuntu.com/stable/ubuntu-help/windows-key.html)

You people know better than me, should we call this `Win` or `Super` on Linux?

**Comment by sirblackheart** [comment]
I am mostly operating on Gnome-Shell as my WM and it uses Super for the Win Key in its Settings. As it seems so does Openbox. Wikipedia [article](https://en.wikipedia.org/wiki/Super_key_(keyboard_button)) on the super key. I think if you start to do any key mapping on linux you probably have to learn/know what the super key is. Alternatively both names could be shown on linux at least in the select accelelerator dialog or just make it clearer by moving it in the right order like the cmd modifier in the add accelerator dialog or both?
![super_acc](https://cloud.githubusercontent.com/assets/1131371/13460432/c3ea97c2-e07a-11e5-82fb-3a33d96662ae.png)

**Comment by dacap** [comment]
> I think if you start to do any key mapping on linux you probably have to learn/know what the super key is.

Completely agree on this one. I've a little idea. I'll merge the PR and then add tooltip to the "Super" checkbox.

**Comment by dacap** [comment]
As a side note: I have a private branch with some changes for the whole keyboard behavior (e.g. to fix AltGr+[ in Spanish keyboard and several keystrokes combinations). But it needs more work and testing on the three platforms (Win, OSX, Linux). Also I'm waiting to discard the Allegro back-end to continue that branch.

**Comment by Viomi** [comment]
@dacap If you need someone to test that private branch some more, I'm running Arch Linux 64bit w/ Openbox and could easily throw up some other window managers for testing.

**Comment by dacap** [comment]
Yesterday I've started working on the branch to fix all keyboard issues with international keyboard (e.g. altgr+[), etc. Coming soon in v1.1.10.
