### ISSUE TITLE
Symmetry axis handles disappear as you zoom in

### ISSUE THREAD

**Issue by jpnk** [aseprite/aseprite#873]
A possible solution is to stick them to viewport borders.

**Comment by TheKK** [comment]
Hi, @jpnk
Could you help me checking if this problem still exist? If so, could you please describe how to reproduce. Thanks :)

**Comment by dacap** [comment]
Hi @TheKK, the problem is still present in `master` branch. Symmetry handles are not visible when the sprite is bigger than the viewport (e.g. you zoom in to a huge zoom factor). A possible solution as @jpnk said is to keep symmetry handles in the viewport boundaries. (It shouldn't be so hard to fix this issue modifying [StandbyState::Decorator::getSymmetryHandles](https://github.com/aseprite/aseprite/blob/master/src/app/ui/editor/standby_state.cpp#L674).)

**Comment by TheKK** [comment]
I gave this a try. The logical part is quite simple (2537b76cda1b76e7e94), but unexpected behaviour from `app::Editor::setEditorScroll` stuck with me.

![untitled](https://cloud.githubusercontent.com/assets/5238484/11613589/5645b0f6-9c61-11e5-8b5b-2d00045a1949.png)

This is what we'll get If we do scrolling via `app::Editor::setEditorScroll` with argument `blitValidRegion` as true (I guess this is for performance optimization). Since I'm still not familiar with the architecture and design of aseprite, I think I'll need your advice to solve this, @dacap.

Btw, this glitch happened if we scroll by:
- Drag with mouse middle button
- Hand tool
- Space + ArrayKey shortcut

not happened by:
- drag the scroll bars of editor view (because it call `ui::View::setViewScroll` directly)

**Comment by dacap** [comment]
@TheKK the issue is tricky. I was testing and the problem is that symmetry handles move along the scroll (their position changes when the scroll changes). It's a situation that isn't found in other Editor's states. I was trying to fix this problem but I'll need more time.

**Comment by dacap** [comment]
@TheKK now you can create a PR to fix this issue, the commit 562106c6f0263468d6a427a7b2a614145c61cb2b fix the scroll issue

**Comment by TheKK** [comment]
Thanks for your help, @dacap. I'll take a look inside your commit and see what's going on exactly.
