### ISSUE TITLE
Can 'Jump to Next Frame' looping in tagged frames?

### ISSUE THREAD

**Issue by alivegames** [aseprite/aseprite#879]
Tag feature is a Lifesaver for me, i use it to manage massive characters. But i have a issue with it.

If i have 'Idle'(Frame 1 to 4) and 'Run'(Frame 5 to 9) two animation, when i finished the last frame of 'Run' (Frame 9) and press the next frame button, editor jump to 'Frame 1'. But I want jump to the first frame of 'Run', it is 'Frame 5' .
![image](https://cloud.githubusercontent.com/assets/6963993/11461877/7016d228-9746-11e5-98f7-2e050788b721.png)

Please tell me if have any way to do this.

And i have another request, when i export file using command, can 'Run' animation first frame start at zero ? Sorry for the trouble
![image](https://cloud.githubusercontent.com/assets/6963993/11461900/c60f3490-9746-11e5-9b38-28ca8e69158a.png)

**Comment by dacap** [comment]
Dup #556

**Comment by lazcht** [comment]
this seems to be bugging the new version again? or is it just me?

(the tag button in the preview box doesn't seem to work as well?)
![2018-12-14_16-35-33](https://user-images.githubusercontent.com/45871611/49995321-5df4e600-ffbe-11e8-976e-e03a378ff33c.gif)

also i'm totally new to github so sorry if i should post a new one instead, let me know. my version is Aseprite v1.2.10-beta4-x64

**Comment by dacap** [comment]
@lazcht sorry but I'm not sure if I understood the GIF 😅 Are you using `,` and `.` keys to move through frames? or the arrow keys? See that there is a difference between arrow keys (that do not loop the tag) and `,` and `.` keys that they do loop inside the tag:

![image](https://user-images.githubusercontent.com/39654/50003147-75fa4480-ff81-11e8-801d-7665acbcc8f2.png)

**Comment by lazcht** [comment]
sorry of the lack of clarity, my problem was the same with the thread starter's. which is, I can't navigate and loop frames inside a tag, instead of looping back on the first frame within tag, it's always back to the first frame. but now i have found my source of problem:

I did change the keyboard shortcut of the next & previous frame with` .` and `,` in `Menus` section, here: 
![image](https://user-images.githubusercontent.com/45871611/50006037-fc913f00-ffde-11e8-9d2c-0339bd099cad.png)
 and I just noticed Aseprite have similar field (is it the same, though? except the ones in Menus doesn't have the tag option) regarding the frame navigation on the `Commands` section, so since I "accidentally" replaced the `Go to Previous/Next frame with the same tag` function with the `Go to Previous/Next frame`, figures why it was not working. 

thanks for the quick response @dacap ! sorry for the trouble :')
