### ISSUE TITLE
--frame-tag does export all frames in v1.1.1 instead of tag frames.

### ISSUE THREAD

**Issue by bfloch** [aseprite/aseprite#897]
I have an .ase where on one layer there is 4 non overlapping tagged animations.
`Aseprite.exe --batch --frame-tag "MoveN" player_v001.ase --save-as "out\test.gif"`

The gif or pngs always show all the frames, not only the specified tag. This is also true for `--sheet --ignore-empty`.

Using the dialog works like expected.

**Comment by TheKK** [comment]
This might relate to #894.

Currently, `--frame-tag` only affects argument `--data` and `--sheet`. As I know `--save-as` and `--sheet` perform totally separated actions. (you can use them the same time to get sprite sheet and images for each frames)

Maybe we can redesign these arguments and commands to make batch actions more intuitive and easy-to-use, like `aseprite info --layers --tags` or `aseprite export --sheet -o XXX.png`?

**Comment by bfloch** [comment]
If that is the place for discussing it: Yes, I would be in favor of having the CLI a bit reworked simply because so far the interface rarely does what I expect it to do.
In case you use the internal json and workflow it might be ok - but if you want to pass your work to something like texture packer and are only interested in automation of the workflows with the CLI it is quite counter-intuitive.

Here is the use case that I am interested in:
- Have an .ase represent the animation for a particular character. Suppose player.ase
- The character has multiple layers and each animation cycle is represented by a tag.
So far so good.
Now I want with the help of the CLI either
- Export merged layers for each tag mirrored in the file name: player_tag_001.png ...
- Export split layers for each tag mirrored in the filename: player_layer_tag_001.png

Ultimately this would be what I want to do as this can be easily send to other external tools, as opposed to using the spritesheet and json data - and as I understand this should be the reason for having a CLI at the first place.

**Comment by dacap** [comment]
Hi @bfloch. The frame tags is a new feature from [v1.1-beta1](http://www.aseprite.org/release-notes/#aseprite-v1-1-beta1) and we're adding missing parts to the CLI progressively (the UI is priority).

1. To export merged layers it should be: `-b player.ase --filename-format "{path}/{title}_{tag}.{extension}" --save-as player.png`
2. To export split layers it should be: `-b --split-layers player.ase --filename-format "{path}/{title}_{layer}_{tag}_{frame001}.{extension}" --save-as player.png`

Both commands have issues:

1. `{frame}` is the global frame, not local to the tag, #894 indicates that we need this new "local frame" or "tag frame" (e.g. `{tagframe}`)
2. `--split-layers` is removing tags in some way (so instead of `_{tag}_` we get `__`)

I'll fix these issues ASAP and there will be a v1.1.2 this week.

Note: About redesigning the CLI, I'm not sure that would be a good idea, at least backward compatibility must be kept, and having two CLIs is not something I'd love to see. I've create [this issue](https://github.com/aseprite/aseprite/issues/901) in case someone want to help with a better CLI.

**Comment by hepari** [comment]
![kuruna-staff-atk1](https://cloud.githubusercontent.com/assets/10383640/15252058/83d5bcda-192c-11e6-94c3-0c55fdbef99a.gif)

@dacap I'm sorry to bother you, but if you could spare some time to help me again, it would be greatly appreciated.
The history says this is 'added' to the v1.1 milestone...
Is it possible to **export different animations of one .ase file under their respective frametag names**?

For this example, I would like to have 'filename-ready.gif' , 'filename-idle.gif', and so on.

![2016051316001](https://cloud.githubusercontent.com/assets/10383640/15252019/5c97b380-192c-11e6-9055-9f98568bcad0.png)

**Comment by dacap** [comment]
@hepari actually it's not possible, but I'd like to add this soon (maybe in v1.1.5.5), keep in touch

**Comment by hepari** [comment]
@dacap That's great to hear. I'm using Aseprite to organize my game assets, and I must say it's proving itself to be a nearly perfect solution. Can't wait to see that feature in action!

**Comment by dacap** [comment]
I was working on this issue, but the change is so big that I'd prefer to include this in the v1.2 beta branch. I'll try to make it available on Steam beta branch maybe next week (or a couple of weeks with other new features). Keep in touch.

**Comment by hepari** [comment]
@dacap Ahh, okay. Then I will opt into the beta branch once it's up :) Thank you for letting me know!

**Comment by dacap** [comment]
This will be available in v1.2-beta1.

**Comment by hepari** [comment]
Thank you for letting me know, David!
I've opted into the beta branch now.
