### ISSUE TITLE
We'll always get logs from App::CoreModules even we doesn't speficy -v argument 

### ISSUE THREAD

**Issue by TheKK** [aseprite/aseprite#899]
This is quite tricky. We will get log from App::CoreModules no matter we use `-v` or not. Here's the reason:

The `-v` take effect after constructing App::Modules, but we have to create App::CoreModules before anything else. Here's the lines decide if we log to console or not:

``` cpp
void verbose_log(const char* format, ...)
{
  if (app::logger_instance && !app::logger_instance->isVerbose())
    return;
....
```

In fact, we get logs even if app::logger_instance is nullptr and that's the reason causes this issue. The tricky part is that after we fix this to:

``` cpp
void verbose_log(const char* format, ...)
{
  if (!app::logger_instance || !app::logger_instance->isVerbose())
    return;
....
```
to make it works more reasonably, then we'll never get log from App::CoreModules because it's always the first one to be created! One solution in my mind is making LoggerModules as one member of App::CoreModules, but I have no idea if LoggerModule is **core** enough as the role it plays. The other solution could be moving LoggerModule from App::Modules and create it before App::CoreModules, but this solution is quite dirty and I can't accept it :P

**Comment by dacap** [comment]
I have been there :smile:

Sometime back I tried to get rid of `aseprite.log` file when `-v` is not specified (I remember creating `AppOptions` class before `App` for that purpose, and `log` argument in `ResourceFinder`). I don't know why I abandoned the task. I'll dedicate some minutes to see what can be done. (Maybe we can merge `app::CoreModules` and `app::Modules`.)

**Comment by dacap** [comment]
I don't remember exactly [why I split `Modules` into `CoreModules`](https://github.com/aseprite/aseprite/commit/73658399cc917deac5db6c89c1de176b0cb5b4c2#diff-2508dc1897fe294f5e3c9cfa438357caL96)

**Comment by dacap** [comment]
I've push a new branch [logger-as-first-module](https://github.com/aseprite/aseprite/tree/logger-as-first-module), if you want to [take a look](https://github.com/aseprite/aseprite/commit/9e638e8c56c45070fb7869d92ab28de1335cf882).

**Comment by TheKK** [comment]
I believe `CoreModules` makes dependency relation more clear, at least to me. Otherwise it would be hard to find out which module should be created first without digging into lots of codes.

Is this your original idea about creating `CoreModuls`? And do you think keeping `CoreModules` would be a good idea?

**Comment by dacap** [comment]
> I believe CoreModules makes dependency relation more clear, at least to me. Otherwise it would be hard to find out which module should be created first without digging into lots of codes.

Actually `CoreModules` is a private class/member of App instance. So it has the same scope as `Modules`. Basically `CoreModules` and `Modules` looks the same to me.

About the order of initialization of modules, it's given by the order of members in `Modules` class, which I think it's better than having modules distributed in two classes.

> Is this your original idea about creating CoreModuls?

I think that I remember why I've created `CoreModules` in the first place. The key is in the [`App::preferences()` member](https://github.com/aseprite/aseprite/commit/73658399cc917deac5db6c89c1de176b0cb5b4c2#diff-2508dc1897fe294f5e3c9cfa438357caR527). When we call the `Modules` constructor (`m_modules = new Modules`) it's probable that some module will look at the `Preferences` singleton (`App::instance()->preferences()`), and as `m_modules = ...` is not yet executed (because we're processing the right-hand side of the statement, the `new Modules`) we don't have a valid `m_modules` member yet (so it's `nullptr` until all modules are constructed).

> And do you think keeping CoreModules would be a good idea?

I'm not sure if it's longer necessary. Tomorrow I'll debug some code to see who needs the `Preferences` instance in `Modules` initialization. And if it's better to handle this in other way (e.g. without using singletons on initialization as first step.)
