### ISSUE TITLE
Artifacts in lists when scrolling on OS X

### ISSUE THREAD

**Issue by neighbordog** [aseprite/aseprite#963]
When scrolling through lists (for example the **palette list** or the **keyboard shortcuts**) it creates artifacts, which seem to based on the content of the lists themselves, basically rendering the list elements unreadable.

![palette-artifacts](https://cloud.githubusercontent.com/assets/2954089/13021739/1b0cf470-d1dd-11e5-8495-2cacd79ec9d1.png)

The artifacts disappear when hovering over them with the cursor. This also means that this bug is not as much present when using the scroll wheel, since the cursor has to be placed in the list in order to do so.

I tested this on two different devices (even though they have a similar setup, regarding to hardware etc.)

Operating System: Mac OS X (10.11.2)

**Comment by Async0x42** [comment]
This also happens to me on Windows 10, however I noticed it in the keyboard shortcuts list

**Comment by dacap** [comment]
Hi there! I've noticed the same problem. It's highly probable that it was introduced in the new-scroll branch merge e985227d954565c2b9094d3d1ea8121661b07352

**Comment by dacap** [comment]
Internal note: the problem is visible only on widgets inside a `ui::Viewport` that contains sub-children. E.g. it's in all `ui::ListBox`es: palettes, recent files/folders, news, keyboard shortcuts, etc. The problem isn't present in the sprite editor and files list because they are just one big widget (they don't have sub-children).
