### ISSUE TITLE
With multiple frames have saving and exporting be able to switch

### ISSUE THREAD

**Issue by Sheepolution** [aseprite/aseprite#968]
I hate it when I work on an animation, and I press CTRL + S to save, leaving me with multiple images. Now I have to go in that folder and delete 12 images. It's in my muscle memory to press CTRL + S, and you don't always work on animations, so I keep forgetting that I have to do CTRL + E instead.

So I would love to have these be able to switch. I feel like getting them as separate files is something a lot of people want anyway? Maybe have CTRL + S pop-up the export window, and put "Save as separate files" in there?

**Comment by dacap** [comment]
Hi @DaanHaaz, I'm thinking to add a confirmation dialog before we save a sequence of images. Something like: `Do you really want to save the following files: frame1.png, frame2.png, ...`. This is not a complete fix for your problem, but at least you'll know that you've pressed Ctrl+S instead of Ctrl+E

By what you said it looks like you are using Import Sprite Sheet and Export Sprite Sheet to edit animations. My recommendation is that you should work with `.aseprite` files. In this way you have the original animation in one file, and you can export the sprite sheet with Ctrl+E (at least you don't need to import it anymore). Also this workflow will be improved when #138 and #126 are ready.

**Comment by dacap** [comment]
Sorry, the warning message is already implemented for the next release: commit 978145ba7a5ad0b1f2909a6cfa0d1406126985cf fixing #902

**Comment by Sheepolution** [comment]
Solved a long long time ago.
