### ISSUE TITLE
Steam Linux - Aesprite fails to launch with "missing executable" error

### ISSUE THREAD

**Issue by arcooke** [aseprite/aseprite#986]
Three things.  When installing Aseprite via Steam on Linux, I receive a "missing executable" error. Looks like the executable is indeed missing, I don't see it anywhere in the install directory.

![](http://i.imgur.com/l1PeBIK.png)

Also, the deb package on Humble Bundle is outdated, it still points to 1.1.1, and Mac/Win both have 1.1.2

Lastly, the Linux version on Steam downloads Windows installers for the c++ runtime packages

![](http://i.imgur.com/hVWcrKC.png)

**Comment by dacap** [comment]
Hi @arcooke, it looks like there are a couple of Steam client bugs here. I didn't provide Linux binaries yet, and they show Aseprite on the software listing (that's why there is a missing executable, it's not ready yet).

About the second problem, there is a checkbox in the internal Steam website to indicate that Aseprite depends on VC runtimes, and I find quite interesting that the Steam client is downloading they anyway on Linux (should be a kind of filter or something).

I think that these issues should be reported at: https://github.com/ValveSoftware/steam-for-linux/issues But I'll look at this later. Thanks for reporting these problems!
