### ISSUE TITLE
Feature Request: Add FILE_SUPPORT_GET_FORMAT_OPTIONS for load

### ISSUE THREAD

**Issue by devil-tamachan** [aseprite/aseprite#992]
Feature Request: Add FILE_SUPPORT_GET_FORMAT_OPTIONS for load

**Comment by dacap** [comment]
Hi @devil-tamachan, could you please give me more details about this? What file format would need this flag? Do you have a patch for an extra file format to use these options?

I generally add things that are used in the program and remove all dead code, so I need some kind of use case for this.

**Comment by devil-tamachan** [comment]
I write AzDrawing1/2 (.adw) importer now. However, Window(line 445) doesn't not working properly. So, I need FILE_SUPPORT_GET_FORMAT_OPTIONS for load in FileOp::createLoadDocumentOperation().

adw_format.cpp http://pastebin.com/TQe5z97M
adwimport_settings.xml http://pastebin.com/hiCxHyhC

**Comment by dacap** [comment]
Why doesn't `load_widget` work? Are you using the command line? or UI? What error do you have? I don't think the flag will be useful in this case, you might check if the UI is available (`fop->context()->isUIAvailable()`). Also would you contribute this patch as a PR? Or how you will distribute this patch?

**Comment by devil-tamachan** [comment]
Hi dacap, I using UI. When I run line 445-451, Aseprite has frozen. After completing the azw importer, I'm going to pull request.

**Comment by dacap** [comment]
Some points about this:

1. You will need to [sign our CLA](https://github.com/aseprite/opensource/blob/master/sign-cla.md#sign-the-cla) to contribute a PR
1. Instead of using the load_widget function, you can use the auto-generated widget (see gif format, `#include "gif_options.xml.h"` and how the `GifOptions` is autogenerated in `build/src/app/gif_options.xml.h`)
1. Debug the line that is frozen the program
1. There is a lot of things to do in a code review for that code, please keep it clean, I guest you have in this state because is a temporal copy.
1. Use English comments
1. Use the same coding style that in other files (e.g. see `fli_format.cpp`).
1. And what is the `adw` format? What other program support this file format? Is this a common file format?

**Comment by devil-tamachan** [comment]
Thank you for your help.
3.  line449: window->openWindowInForeground();
  I think so window is in conflict with progress dlg.
7. AzDrawing2 is specialized in the line. https://www.google.co.jp/search?hl=ja&tbm=isch&q=AzDrawing2

I using some source code from AzDrawing (GPLv3 - linux version, https://osdn.jp/projects/azdrawing/) So I can't sign your CLA & pull request. I'm sorry.

**Comment by dacap** [comment]
As an alternative you could try to use your own implementation to decode az/adw/this file format. Anyway I don't think AzDrawing is globally known (e.g. as gif/png files)
